app/controllers/admin/payout_reports_controller.rb
The amount provide in the JSON is in the currency that will be deposited into the publishers uphold account. To counteract this we should lookup by the `documentId` provided or the `probi`  amount
=> Better lookup of invoices

app/controllers/api/v1/publishers_controller.rb
Return the status_update ID in the response upon successful API call
=> Update publishers_status_updates API

app/assets/stylesheets/pages/browser_user_home.scss, app/views/browser_users/_how_it_works.html.slim
=> Fix CSS for out-of-place copy button

app/controllers/publishers_controller.rb
=> Eliminate erroneous devise flash messages. Closes #2620

.travis.yml, app/assets/stylesheets/pages/browser_user_home.scss, app/controllers/publishers_controller.rb, app/controllers/uphold_connections_controller.rb, app/jobs/sync/channel_stats_job.rb, app/models/application_record.rb, app/views/admin/publishers/show.html.slim, app/views/browser_users/_how_it_works.html.slim, config/database.yml
🐛 Fix YouTube rate limiting
💫 Fix some CSS and flash messages
=> Release 2020-04-17

app/models/application_record.rb, app/views/admin/publishers/show.html.slim, config/application.rb
=> Follower DB fix. 

app/jobs/enqueue_publishers_for_payout_job.rb, app/services/eyeshade/create_snapshot.rb, app/views/admin/publishers/show.html.slim, config/application.rb, config/database.yml
🐛 Updated TOS flow for peer-to-peer
✨ Take snapshots for payment amounts
=> Release 2020-04-23

app/services/eyeshade/create_snapshot.rb, app/services/promo/models/peer_to_peer_registration.rb, app/services/promo/registration_getter.rb
🐛 Add a slash
🐛 Include content-type in header
✨ Add referral caps
=> Release 2020-04-28

config/secrets.yml
Closes https://github.com/brave-intl/publishers/issues/2668
=> Include cap for peer-to-peer

app/jobs/two_factor_authentication_removal_job.rb, test/fixtures/two_factor_authentication_removals.yml, test/jobs/two_factor_authentication_removal_job_test.rb
=> Resolve 2FA Issue

app/assets/stylesheets/admin/style.scss, app/controllers/admin/cases_controller.rb, app/helpers/admin_helper.rb, app/javascript/packs/admin_case.js, app/models/case.rb, app/views/admin/cases/_sidebar.html.slim, app/views/admin/cases/_table.html.slim, app/views/admin/cases/show.html.slim, app/views/admin/shared/_sidebar.html.slim
Closes #2303
Closes #2302
Closes #2068
* Rename some general translation strings
* Increase the pagination limit from 20 to 50
* Introduce ability to `OR` together search queries. Ex: Searching for `status:open status:in_progress` shows cases which are open or in progress
* Add ability to re-open case
=> Case System improvements

package.json, yarn.lock
This is currently blocked by `webpack-dev-server`. Issue located here - https://github.com/webpack/webpack-dev-server/issues/2559
=> Fix yargs-parser JS Vulnerability

app/javascript/views/admin/payments/Payments.tsx, app/javascript/views/statements/Statements.tsx, app/javascript/views/statements/statements/StatementDetails.tsx, app/models/views/user/statement_overview.rb, app/models/views/user/statements.rb
Fixes 2 bugs 🐛 
- Payment page couldn't load because of the lack of IntlProvider
- Rate card information wasn't showing up for admins
=> Fix admin payment page

app/javascript/views/admin/payments/Payments.tsx, app/javascript/views/statements/Statements.tsx, app/javascript/views/statements/statements/StatementDetails.tsx, app/models/views/user/statement_overview.rb, app/models/views/user/statements.rb
:bug: Fix the admin payment page
=> Release 2020-05-08

app/jobs/payout/uphold_job.rb
Right now the manual payout report doesn't work
=> Fix manual payout report job

app/jobs/cache_uphold_tips.rb, app/models/cached_uphold_tip.rb, app/models/uphold_connection_for_channel.rb, app/services/publisher_statement_getter.rb, app/services/uphold/models/transaction.rb, db/migrate/20200508194824_create_cached_uphold_tips.rb, db/schema.rb
To prevent us from having a 
1. Register a channel
1. Connect an uphold account 
1. Move funds into the connected card on Uphold
1. Click "View Statement"
1. See the cached uphold transaction
=> Cache Uphold Tips

app/jobs/cache_uphold_tips.rb, app/jobs/payout/uphold_job.rb, app/models/cached_uphold_tip.rb, app/models/uphold_connection_for_channel.rb, app/services/publisher_statement_getter.rb, app/services/uphold/models/transaction.rb, db/migrate/20200508194824_create_cached_uphold_tips.rb, db/schema.rb
:bug: Fix timeouts for Statements due to a large number of direct uphold tips
:bug: Fix manual payout report
=> Release 2019-05-08 (2)

app/controllers/concerns/search.rb, test/controllers/concerns/search_test.rb
🐎  Remove requests to prevent excess data use
=> Release 2020-05-11

app/controllers/concerns/search.rb, config/initializers/rack-attack.rb, test/controllers/concerns/search_test.rb
☮️ Remove rack-attack limitation for public API
=> Release 2020-05-12

app/controllers/publishers/omniauth_callbacks_controller.rb, app/javascript/locale/en.ts, app/javascript/views/statements/Statements.tsx, app/javascript/views/statements/statements/StatementDetails.tsx, app/javascript/views/statements/statements/statementDetails/DetailSection.tsx, app/jobs/cache_uphold_tips.rb, app/models/cached_uphold_tip.rb, app/models/views/user/statement_overview.rb, app/models/views/user/statements.rb, app/services/publisher_statement_getter.rb, app/services/uphold/models/transaction.rb, app/services/youtube_channel_getter.rb, config/locales/en.yml, db/migrate/20200510205028_change_cached_uphold_tips_to_uuid.rb, db/schema.rb
🐛  Fix statement bugs
🐛 Have warning for Youtube Quota
=> Release 2020-05-12 (2)

db/migrate/20200513201529_add_unique_index_to_cache_uphold_tips.rb, db/schema.rb, lib/tasks/database_updates/remove_duplicate_tips.rake
=> Add unique index for Uphold Transaction ID

lib/tasks/database_updates/backfill_publisher_statuses.rake
Publisher Statuses that were never created are causing some issues
=> Backfill Publisher Statuses

app/services/initializable.rb
=> Fix symbol underscore bug

app/services/initializable.rb
🐛 Fix NoMethodError due to type mismatch.
=> Release 2020-05-21

Gemfile, Gemfile.lock, config/sidekiq.yml
🐛 Reduce number of times refresh stats is called.
=> Release 2020-05-27

config/locales/ja.yml
Related to https://github.com/brave-intl/publishers/pull/2709
=> Type fix/patch 3

app/jobs/cache/browser_channels/main.rb
in Cache::BrowserChannels::Main.
=> Include channels with no uphold verification connection to be enqueued

app/jobs/cache/browser_channels/responses_for_prefix.rb, app/models/channel.rb, app/models/paypal_connection.rb, app/models/site_banner_lookup.rb, protos/channel_responses.proto, protos/channel_responses.rb, test/jobs/cache/browser_channels/prefix_list_test.rb, test/jobs/cache/browser_channels/responses_for_prefix_test.rb
♻️ Wallet state expanded (#2771)
🐛 Closes #2773
=> Release 2020-06-25

db/migrate/20200626073545_remove_wallet_status_from_site_banner_lookups.rb, db/schema.rb
🐛 Fix unused column `wallet_status`
=> Release 2020-06-26

app/services/uphold/client.rb, app/services/uphold/models/address.rb, app/services/uphold/models/card.rb, app/services/uphold/models/transaction.rb, app/services/uphold/models/user.rb
Fixes `api_base_uri` for users
Connect your UpholdConnection
=> Fix api_base_uri

app/models/concerns/referral_promo.rb, app/models/uphold_connection.rb, lib/tasks/expire_promo_codes.rake
* Add the `REFERRAL_KYC_REQUIRED` flag to existing users 
Run `rails expire_promo_codes`
=> Require KYC for existing publishers

app/models/concerns/referral_promo.rb, app/models/uphold_connection.rb, app/services/uphold/client.rb, app/services/uphold/models/address.rb, app/services/uphold/models/card.rb, app/services/uphold/models/transaction.rb, app/services/uphold/models/user.rb, lib/tasks/expire_promo_codes.rake
🐛  Fix the UpholdConnection api_base_uri
✨ Set the require KYC flag for publishers who aren't KYC'd or are in a country which does not require KYC.
=> Release 2020-06-30

Gemfile.lock, app/services/publisher_balance_getter.rb, config/services.yml, test/controllers/api/v1/stats/publishers_controller_test.rb
For some reason Gemfile.lock wasn't included in the release PR.
=> Fix deploy

Gemfile.lock, app/services/publisher_balance_getter.rb, config/services.yml, test/controllers/api/v1/stats/publishers_controller_test.rb
:bug: Add timeout for connections to Eyeshade
:bug: Fix Fastly Connection in Staging
=> Release 2020-07-08

config/environments/test.rb, test/controllers/api/v1/stats/publishers_controller_test.rb
🐛 Fixes problem where UTC time wasn't being considered due to `Date.now`
=> Fix UTC test breakage

app/javascript/components/errorBoundary/ErrorBoundary.tsx, app/javascript/views/walletServices/LastDepositInformation.tsx, app/javascript/views/walletServices/WalletServices.tsx
:bug: Multiple calls are made to `wallet/latest/` due to the re-rendering and [`useEffect()` react hook](https://reactjs.org/docs/hooks-effect.html)
1. Log into the dashboard
2. Open the network tab
3. See only one request is made
=> General Bug Fixes

app/javascript/components/errorBoundary/ErrorBoundary.tsx, app/javascript/views/walletServices/LastDepositInformation.tsx, app/javascript/views/walletServices/WalletServices.tsx
:bug: Prevent multiple calls from being made to `/wallet/latest`
=> Release 2020-07-14

config/heavy_sidekiq.yml, config/sidekiq.yml, test/jobs/sidekiq_configuration_test.rb
The module for this job was updated previously but wasn't corrected in this YML config.
=> Correct the module name for ChannelTransfers

app/controllers/api/v1/promo_registrations_controller.rb
1. Step one
2. Step two
3. Step three
=> Do not try to send mail to uninitialized publisher

app/controllers/api/base_controller.rb
1. Step one
2. Step two
3. Step three
=> Message #alerts channel in slack if API auth token is used from a non whitelisted IP

app/controllers/api/base_controller.rb, app/services/payout/potential_payment/uphold_service.rb, test/services/payout/potential_payment/uphold_service_test.rb, yarn.lock
🔒 Bump elliptic from 6.5.2 to 6.5.3 
✨ Message #alerts if API Auth Token is misused
🐛 Fix it so referral countries will be paid
=> Release 2020-07-31

db/migrate/20200813170145_add_referral_code_index_to_promo_registration.rb, db/schema.rb
1. Step one
2. Step two
3. Step three
=> Add index on referral_code column of promo_registrations table

db/migrate/20200813170145_add_referral_code_index_to_promo_registration.rb, db/schema.rb
⚡ Add index to speed up referral code lookups.
=> Release 2020-08-13

app/controllers/api/v1/promo_registrations_controller.rb, app/mailers/application_mailer.rb, app/mailers/publisher_mailer.rb, config/secrets.yml
✨ Updates the from email for the brand bidding emails.
=> Release 2020-08-24

config/locales/en.yml
=> Change automated brand bidding email sent

app/helpers/settings_helper.rb, app/views/publishers/_paypal_connection_panel.html.slim, app/views/publishers/settings/index.html.slim
Closes the following Sentry issues
https://sentry.io/organizations/brave-software/issues/1784014570
https://sentry.io/organizations/brave-software/issues/1871494410
https://sentry.io/organizations/brave-software/issues/1871493501
=> Fix settings page

app/helpers/settings_helper.rb, app/views/publishers/_paypal_connection_panel.html.slim, app/views/publishers/settings/index.html.slim
=> Release 2020-09-01 (Part 2)

app/jobs/update_gemini_default_currency_job.rb, app/models/gemini_connection.rb
Only runs recipient and default currency code when user has completed KYC.
=> Add checks for verified users

app/jobs/update_gemini_default_currency_job.rb, app/models/gemini_connection.rb
:sparkles: Add checks for verified users.
=> Release 2020-09-02

config/locales/en.yml
Updates the subject for the Brand bidding email to be "suspended" rather than "frozen"
=> Update Brand Bidding Subject

app/controllers/api/v1/publishers_controller.rb, app/views/admin/publishers/index.html.slim, db/migrate/20200903184106_add_performance_improvements.rb, db/schema.rb
⚡ Some performance improvements for Publishers (Indexes, Publisher's list)
🐛 Fix issue where the API could move a publishers status from `only_user_funds`
=> Release 2020-09-03

config/environments/production.rb, config/environments/staging.rb, config/initializers/content_security_policy.rb
=> Set a Content-Security-Policy

app/controllers/payment/connection/stripe_connections_controller.rb, app/javascript/views/routes.ts, config/routes.rb, lib/tasks/update_feature_flag.rake
:bug: Fixes Stripe Routing
1. Load application locally
2. Run `rails 'update_feature_flag[stripe_enabled, true]'`
3. Connect Stripe
4. No infinite loading indicator 😄
=> Update Stripe Routing

Gemfile, Gemfile.lock
=> Downgrade Rack

Gemfile, Gemfile.lock
=> Release 2020-09-16

lib/tasks/assets.rake
=> Read SHA from Environment

Dockerfile
:bug: Fix the banner upload for EKS deployments.
=> Release 2020-09-28

app/controllers/admin/publishers_controller.rb
Caches the total entries on the homepage
=> Cache Total Entries

app/models/concerns/user_feature_flags.rb
:bug: Fixes issue where multiple features enabled causes the query not to return true.
=> Fix invoice scope

package.json, yarn.lock
🔒 Fixes security vulnerabilities 
Tests pass
=> Fix JS Vulnerabilities

app/models/site_banner_lookup.rb, package.json, yarn.lock
🔒 Remove JS Security Dependency Alerts
⚡ Introduce reader for `SiteBannerLookup`.
=> Release 2020-10-06

app/models/concerns/referral_promo.rb
1. Step one
2. Step two
3. Step three
=> disable referral signups

app/controllers/concerns/search.rb
Closes #2916 
Cost breakdown:
```
"Nested Loop  (cost=237924.74..238608.30 rows=645094 width=339)"
"  ->  HashAggregate  (cost=237924.65..237925.25 rows=200 width=16)"
"        Group Key: channels.publisher_id"
"        ->  Append  (cost=1000.09..237918.56 rows=12176 width=16)"
"              ->  Gather  (cost=1000.09..25514.16 rows=10 width=16)"
"                    Workers Planned: 1"
"                    ->  Nested Loop  (cost=0.08..24513.16 rows=6 width=16)"
"                          ->  Parallel Seq Scan on site_channel_details  (cost=0.00..3111.98 rows=6 width=16)"
"                                Filter: ((brave_publisher_id)::text ~~* 'illenium%'::text)"
"                          ->  Index Scan using index_channels_on_details_type_and_details_id on channels  (cost=0.08..3566.86 …
```
=> Perf search improvement: Switch away from joins and use UNION instead. Cost analysis in pull request

app/controllers/concerns/search.rb
⚡ Use replica for querying the admin publishers index
=> Release 2020-10-15

app/services/base_api_client.rb
excludes eyeshade proxy when reaching out to eyeshade
1. Step one
2. Step two
3. Step three
=> added if statement for adding proxy

app/assets/stylesheets/pages/home.scss, app/controllers/admin/publishers_controller.rb, app/controllers/publishers_controller.rb, app/services/base_api_client.rb, app/views/admin/publishers/show.html.slim, app/views/publishers/home.html.slim
⚡ Limit the number of channels being loaded for each publisher and on admin
=> Release 2020-10-28

app/controllers/publishers_controller.rb, config/locales/en.yml, config/locales/ja.yml
=> Tell users that the referral program is winding down

app/controllers/publishers_controller.rb, app/javascript/locale/ja.ts, app/services/payout/gemini_service.rb, app/services/payout/service.rb, config/locales/en.yml, config/locales/ja.yml
🐛 Contest token preventing people from signing in
⏲️ Referral program wind-down messaging
🐛 Fix translations for cases on the main home page
=> Release 2020-11-10

app/controllers/admin/payout_reports_controller.rb, app/controllers/publishers_controller.rb, app/helpers/payout_helper.rb, app/helpers/publishers_helper.rb, app/jobs/set_payout_in_progress_job.rb, app/views/publishers/_payout_status.html.slim, test/controllers/admin/payout_reports_controller_test.rb, test/jobs/set_payout_in_progress_job_test.rb
Closes https://github.com/brave-intl/publishers/issues/2950
=> Get rid of payout_report_generating in favor of payout_in_progress

app/controllers/uphold_connections_controller.rb, app/models/channel.rb, lib/tasks/cut_out_low_referral_codes.rake
1. Step one
2. Step two
3. Step three
=> Added job to set lockout time

app/controllers/uphold_connections_controller.rb, app/models/channel.rb, lib/tasks/cut_out_low_referral_codes.rake
➖ Disable referral code creation
=> Release 2020-11-18

config/locales/en.yml
https://twitter.com/davidwalshblog/status/1330140832238886914?s=19
1. Step one
2. Step two
3. Step three
=> Minor typo correction

app/jobs/enqueue_emails_for_promo_publishers_job.rb, app/jobs/promo/email_breakdowns_job.rb, app/mailers/publisher_mailer.rb, app/models/channel.rb, app/models/concerns/user_feature_flags.rb, app/views/publisher_mailer/promo_breakdowns.html.slim, config/sidekiq.yml, test/controllers/api/v1/stats/referral_codes_controller_test.rb, test/fixtures/channels.yml, test/fixtures/site_channel_details.yml, test/models/channel_test.rb, test/models/site_channel_test.rb
:sparkles: Feature flag for top publishers
:sparkles: Feature flag for those who want daily promo emails
=> Release 2020-11-30

app/controllers/admin/publishers_controller.rb, app/javascript/views/admin/components/userNavbar/components/TopNav/TopNav.tsx
🐛 Payout namespace fix
⚡ Login via TOTP on users
=> Release 2020-12-09

app/controllers/admin/publishers/publisher_status_updates_controller.rb, app/controllers/admin/publishers/publisher_whitelist_updates_controller.rb, app/controllers/api/v1/publishers_controller.rb, app/models/publisher.rb, app/models/publisher_whitelist_update.rb, app/views/admin/publishers/_wallet_info.html.slim, app/views/admin/publishers/publisher_status_updates/index.html.slim, config/routes.rb, db/migrate/20201215124546_add_publisher_whitelist_updates.rb, db/schema.rb, test/controllers/admin/publishers/publisher_whitelists_controller_updates_test.rb, test/controllers/api/v1/publishers_controller_test.rb
* Add publisher_whitelist_updates table
* Add PublisherWhitelistUpdates model, controller
* Expose UI to enable admins to use API
* Add test for PublisherWhitelistUpdatesController
View status
Update status
1. Step one
2. Step two
3. Step three
=> Add support for admins adding and removing whitelists

app/controllers/admin/publishers/publisher_status_updates_controller.rb, app/controllers/admin/publishers/publisher_whitelist_updates_controller.rb, app/controllers/admin/publishers_controller.rb, app/controllers/api/v1/publishers_controller.rb, app/javascript/views/admin/components/userNavbar/components/TopNav/TopNav.tsx, app/models/publisher.rb, app/models/publisher_whitelist_update.rb, app/views/admin/publishers/_wallet_info.html.slim, app/views/admin/publishers/publisher_status_updates/index.html.slim, config/routes.rb, db/migrate/20201215124546_add_publisher_whitelist_updates.rb, db/schema.rb, test/controllers/admin/publishers/publisher_whitelists_controller_updates_test.rb, test/controllers/api/v1/publishers_controller_test.rb
1. Step one
2. Step two
3. Step three
=> Release 2020-12-15

app/jobs/enqueue_emails_for_promo_publishers_job.rb
Co-authored-by: Albert Wang <=>
1. Step one
2. Step two
3. Step three
=> Fix breakdown sidekiq job (#2987)

Gemfile, Gemfile.lock
Remove PG gem which doesn't seem to be used at all
=> Upgrade Puma gem to 5.1.1

Gemfile, Gemfile.lock, app/jobs/enqueue_emails_for_promo_publishers_job.rb, app/jobs/promo/email_breakdowns_job.rb, config/sidekiq.yml
1. Step one
2. Step two
3. Step three
=> merge to prod

.github/workflows/codeql-analysis.yml
This PR enables CodeQL, a semantic code analysis engine by Github, to scan for security issues on this repo.
By default it will scan on the following interval:
- Every new commit against the default branch (in this case master)
- Every new pull request against the default branch (in this case master)
- Once per week on **Sunday at Midnight UTC** which can be seen in the newly created .github/workflows/.codeql-analysis.yml file under the -cron flag under schedule. 
To learn more about the analysis tool and why we are using it please see: https://codeql.github.com/docs/codeql-overview/ for information about codeQl, and [this](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) blog post for a little …
=> PLEASE MERGE - Enables Security Code Scanning

config/initializers/fastly.rb, config/services.yml
* Access base url from anywhere (#2470) (#2472)
🐛 Use base url for paypal redirect
* Remove requests to prevent excess data use (#2689) (#2691)
🐎  Remove requests to prevent excess data use
* Release 2020-05-12 (2) (#2696)
* Fix Statement Bugs (#2690)
* Have warning for the quota (#2692)
Co-authored-by: Albert Wang <amwang217@gmail.com>
* Handle cases where there isn't an uphold_connection for a channel (#2789) (#2790)
* Show CSV in a more clean way (#2982)
Co-authored-by: Albert Wang <amwang217@gmail.com>
* Fix the columns being selected
* updated ip check to cloudfront
* fixed config key
* fixed logs
Co-authored-by: Albert Wang <amwang217@gmail.com>
Co-authored-by: Cory McDonald <cmcdonald@brave.com>
Co-authored-by: Cory McDonald <cory@corywmcdonald.com>
Co-authored-by: eV (㋎) …
=> Converted to cloudfront (#3000)

app/jobs/cache/browser_channels/responses_for_prefix.rb, config/secrets.yml
1. Step one
2. Step two
3. Step three
=> fixed permission control for s3_rewards2

config/sidekiq.yml
1. Step one
2. Step two
3. Step three
=> upped max dead jobs

app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/verify_site_channel.rb
1. Step one
2. Step two
3. Step three
=> removed connection wait

app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/verify_site_channel.rb
1. Step one
2. Step two
3. Step three
=> removed connection wait (#3023)

app/jobs/cache/metrics/uphold_kyc_by_country_job.rb, app/jobs/cache_browser_channels_json_job.rb, app/jobs/cache_browser_channels_json_job_v2.rb, app/jobs/cache_browser_channels_json_job_v3.rb, app/jobs/cache_browser_channels_json_job_v3_p1.rb
1. Step one
2. Step two
3. Step three
=> converted queue as string to default

app/jobs/cache/metrics/uphold_kyc_by_country_job.rb, app/jobs/cache_browser_channels_json_job.rb, app/jobs/cache_browser_channels_json_job_v2.rb, app/jobs/cache_browser_channels_json_job_v3.rb, app/jobs/cache_browser_channels_json_job_v3_p1.rb
1. Step one
2. Step two
3. Step three
=> prod patch 2020-02-09_1

.irbrc, Gemfile, Gemfile.lock, app/jobs/promo/email_breakdowns_job.rb, app/models/stats_redshift/referral_download.rb, config/application.rb, config/database.yml
Reverts brave-intl/publishers#3041
=> Revert "Fetch confirmation info from Redshift"

app/helpers/publishers_helper.rb, app/models/bitflyer_connection.rb, app/models/potential_payment.rb, app/services/payout/bitflyer_service.rb
1. Step one
2. Step two
3. Step three
=> Updates for payout

db/migrate/20210227024418_add_bitflyer_is_verified_to_potential_payments.rb, db/schema.rb
1. Step one
2. Step two
3. Step three
=> Add payout migration for bitFlyer

app/controllers/application_controller.rb
Closes #3057
Tested locally by setting default language on Firefox to Japanese.
=> Fix locale detection

.gitignore, app/jobs/cache/browser_channels/main.rb
=> Refresh all prefixes every 24 hours

test/controllers/u2f_authentications_controller_test.rb, test/features/log_in_test.rb, test/jobs/create_uphold_channel_card_job_test.rb
1. Step one
2. Step two
3. Step three
=> added => nil for :authenticate! calls

app/jobs/channels/approve_channel_transfer_job.rb
1. Step one
2. Step two
3. Step three
=> Update bF deposit id on channel transfer

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/helpers/publishers_helper.rb, app/jobs/cache/browser_channels/main.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/channels/approve_channel_transfer_job.rb, app/jobs/enqueue_publishers_for_payout_job.rb, app/models/bitflyer_connection.rb, app/models/potential_payment.rb, app/services/payout/bitflyer_service.rb, db/migrate/20210227024418_add_bitflyer_is_verified_to_potential_payments.rb, db/schema.rb, test/controllers/u2f_authentications_controller_test.rb, test/features/log_in_test.rb, test/jobs/create_uphold_channel_card_job_test.rb, test/jobs/enqueue_publishers_for_payout_job_test.rb
Reverts brave-intl/publishers#3073
=> Revert "Release 2020-03-09"

db/migrate/20210227024418_add_bitflyer_is_verified_to_potential_payments.rb, db/schema.rb
Reverts brave-intl/publishers#3067
=> Revert "Add payout migration for bitFlyer"

app/jobs/cache/browser_channels/prefix_list.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb
1. Step one
2. Step two
3. Step three
=> Stop running v4 Channels API on dev

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/helpers/publishers_helper.rb, app/jobs/cache/browser_channels/main.rb, app/jobs/cache/browser_channels/prefix_list.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/channels/approve_channel_transfer_job.rb, app/jobs/enqueue_publishers_for_payout_job.rb, app/models/bitflyer_connection.rb, app/models/potential_payment.rb, app/services/payout/bitflyer_service.rb, db/schema.rb, public/creators-landing/yarn.lock, test/controllers/u2f_authentications_controller_test.rb, test/features/log_in_test.rb, test/jobs/create_uphold_channel_card_job_test.rb, test/jobs/enqueue_publishers_for_payout_job_test.rb, yarn.lock
Reverts brave-intl/publishers#3092
=> Revert "Release 2021-03-10"

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/helpers/publishers_helper.rb, app/jobs/cache/browser_channels/main.rb, app/jobs/cache/browser_channels/prefix_list.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/channels/approve_channel_transfer_job.rb, app/jobs/enqueue_publishers_for_payout_job.rb, app/models/bitflyer_connection.rb, app/models/potential_payment.rb, app/services/payout/bitflyer_service.rb, db/schema.rb, public/creators-landing/yarn.lock, test/controllers/u2f_authentications_controller_test.rb, test/features/log_in_test.rb, test/jobs/create_uphold_channel_card_job_test.rb, test/jobs/enqueue_publishers_for_payout_job_test.rb, yarn.lock
Reverts brave-intl/publishers#3098
=> Revert "Revert "Release 2021-03-10""

app/controllers/health_checks_controller.rb
Closes https://github.com/brave-intl/publishers/issues/3083
May test locally with
`curl -v http://0.0.0.0:3000/health-check`
=> Health-check updates to measure mailer queue depth

config/initializers/session_store.rb
Part of https://github.com/brave-intl/publishers/pull/3096
=> Filter out sessions older than a day

app/javascript/locale/ja.ts, config/locales/ja.yml, config/locales/views/publishers/security/ja.yml, public/creators-landing/src/locale/ja.js
1. Step one
2. Step two
3. Step three
=> Update translation strings

app/models/publisher.rb
1. Step one
2. Step two
3. Step three
=> Activate BitFlyer

app/controllers/payment/connection/bitflyer_connections_controller.rb
Reverts brave-intl/publishers#3122
=> Revert "Don't change the global value of the default_locale. This affects other user's sessions"

app/controllers/application_controller.rb, app/controllers/payment/connection/bitflyer_connections_controller.rb
=> Release 2021-03-21 -2

app/models/publisher.rb
=> Perf: Fix lookup of existing publishers by using the preferred way

Gemfile.lock
1. Step one
2. Step two
3. Step three
=> Bitflyer integration

app/jobs/cache/browser_channels/main.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/channels/approve_channel_transfer_job.rb, app/models/channel.rb, app/models/site_banner_lookup.rb, test/jobs/cache/browser_channels/responses_for_prefix_test.rb, test/jobs/channels/approve_channel_transfer_job_test.rb, test/jobs/channels/transfer_channels_job_test.rb
Closes https://github.com/brave-intl/publishers/issues/3114
=> After a channel transfer, a job gets enqueued to update the publisher list

config/locales/ja.yml
Closes https://github.com/brave-intl/publishers/issues/3078
=> Change こんにちわ to こんにちは .

.env.example, Gemfile.lock, README.md, app/controllers/payment/connection/bitflyer_connections_controller.rb, app/models/publisher.rb, app/services/publisher_token_authenticator.rb, yarn.lock
1. Step one
2. Step two
3. Step three
=> Release [2021-03-30]

app/assets/stylesheets/theme/nav.scss
Changes this:
Into this:
Resolves #3152
Look at the dashboard account avatar; is it fixed? :)
=> Improves Avatar Aesthetics

app/assets/stylesheets/theme/nav.scss, app/jobs/cache/browser_channels/main.rb
🐛 ⚡ Excess running of perf list sync
=> Release 2021-04-01

app/assets/stylesheets/theme/nav.scss
🐛 Narrow bitflyer permissions scope.
=> Release 2021-04-02

app/jobs/cache_browser_channels_json_job_v3.rb
1. Step one
2. Step two
3. Step three
=> removed distro call and used empty array

.gitignore
Add IntelliJ to the git commit file
=> Add IntelliJ to the git commit file

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .gitignore, CODE_OF_CONDUCT.md, Dockerfile, app/assets/stylesheets/theme/nav.scss, app/javascript/views/statements/Statements.tsx, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/cache_browser_channels_json_job_v3.rb, config/locales/ja.yml, test/fixtures/publisher_notes.yml, test/jobs/cache/browser_channels/responses_for_prefix_test.rb, test/mailers/previews/publisher_mailer_preview.rb, test/mailers/publisher_mailer_test.rb
🖌️ Temporarily hide statements UI
⚡ Perf improvements on V4 channel response
=> Release 2021-04-15

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .gitignore, CODE_OF_CONDUCT.md, Dockerfile, app/assets/stylesheets/theme/nav.scss, app/controllers/concerns/search.rb, app/javascript/views/statements/Statements.tsx, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/cache_browser_channels_json_job_v3.rb, config/locales/ja.yml, test/fixtures/publisher_notes.yml, test/jobs/cache/browser_channels/responses_for_prefix_test.rb, test/mailers/previews/publisher_mailer_preview.rb, test/mailers/publisher_mailer_test.rb
Improving publisher search speed.
=> Release 04-16-2021

package.json, public/creators-landing/yarn.lock, test/features/admin_test.rb, yarn.lock
To get the admin publishers payments fix in.
=> Release 05-10-2021

app/javascript/views/statements/Statements.tsx, app/services/publisher_statement_getter.rb, app/services/publisher_transactions_getter.rb, test/services/publisher_transactions_getter_test.rb
I believe the views are fixed in this PR, but this just hides the views from the user until I can test it out in production.
=> Fix for the statements view

config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb
Closes https://github.com/brave-intl/publishers/issues/3240
=> Specify Permissions-Policy=interest-cohort=()

app/javascript/views/statements/Statements.tsx
This reverts the admin-only flag in https://github.com/brave-intl/publishers/pull/3222
=> Enable statements view for all users

app/services/payout/uphold_service.rb
Closes https://github.com/brave-intl/publishers/issues/3266
=> Cleanup of the balance checks prior to payout and email warnings.

app/controllers/payment/connection/bitflyer_connections_controller.rb, app/services/bitflyer/oauth_completer.rb
Bitflyer useres are getting 500s when they try to auth with us
due to the records not having access_tokens, which we haven't saved
yet.
=> Bitflyer 500

app/helpers/publishers_helper.rb, app/models/payout_report.rb, app/services/payout/uphold_service.rb, app/views/publishers/_home_balances.html.slim, config/locales/en.yml, config/locales/ja.yml, config/locales/jabap.yml, lib/eyeshade/contribution_balance.rb, lib/eyeshade/overall_balance.rb, lib/eyeshade/referral_balance.rb, test/features/payout_in_progress_test.rb, test/helpers/publishers_helper_test.rb
=> Remove remaining 5 BAT messaging and code

app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/models/publisher.rb, app/views/publishers/home.html.slim, app/views/publishers/settings/index.html.slim
Remove the web home check on whether or not we should render the main wallet_services panel
Closes https://github.com/brave-intl/publishers/issues/3277
=> Enable bitflyer for all

app/controllers/payment/connection/bitflyer_connections_controller.rb, app/services/bitflyer/auth_completer.rb, config/secrets.yml, test/services/bitflyer/auth_completer_test.rb
I've refactored the Bitflyer new connection code and added a test. This is verified to work in staging.
=> Bitflyer 500 Refactor and Test

app/helpers/publishers_helper.rb, app/views/publishers/_home_balances.html.slim, config/locales/en.yml, config/locales/ja.yml, test/helpers/publishers_helper_test.rb
=> Update payout date wording

config/locales/ja.yml
Closes https://github.com/brave-intl/publishers/issues/3318
=> Temporary bandage to fix missing translations

app/jobs/promo/email_breakdowns_job.rb
Closes https://github.com/brave-intl/publishers/issues/3316
=> Fix crash when no country exists

public/robots.txt
Fix https://github.com/brave-intl/creators-private-issues/issues/14
1. Step one
2. Step two
3. Step three
=> Fix expired auth token endpoint in robots.txt

Gemfile, Gemfile.lock, app/javascript/locale/en.ts, app/jobs/promo/email_breakdowns_job.rb, app/models/concerns/user_feature_flags.rb, app/models/publisher.rb, app/views/admin/publishers/edit.html.slim, public/robots.txt, test/fixtures/gemini_connections.yml, test/jobs/payout/bitflyer_job_test.rb, test/jobs/payout/gemini_job_test.rb, test/jobs/payout/uphold_job_test.rb, test/models/concerns/user_feature_flags_test.rb
(1) Upgrade query regarding payable Publishers and fixes the missing `addresses` field
(2) Fix display name for BitflyerConnections for :en locale
(3) Referral emails can now be month-to-date
=> Release 2021-07-28

config/environments/development.rb, config/initializers/rack-attack.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/17
=> Limit attempts against a single user when trying to sign-in via totp

Gemfile, config/initializers/add_column_types_to_null_db.rb
Got an error in prod -- `cannot load such file -- nulldb`
Make sure the gem is installed in prod and that we only load the monkey patch after all gems have been loaded.
=> Nulldb asset compile prod

Gemfile, config/initializers/add_column_types_to_null_db.rb
=> Release 08-02-2021 #2 (#3352)

Dockerfile
Messing with the PATH previously causes bundle to fail. Only override for bundle installing.
=> Only update PATH for bundle install

lib/tasks/database_updates/update_activestorage_service_names.rake
Update ActiveStorage::Blob service_name after renaming from amazon to split buckets.
=> Add service_name update task

Dockerfile, Gemfile, Gemfile.lock, README.md, test/helpers/image_conversion_helper_test.rb
Don't need it anymore, use `fastimage` in the tests to get the dimensions.
=> Completely remove imagemagick

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb
=> Release 08-16-2021

app/views/site_channels/verification_dns_record.html.slim, config/locales/en.yml, config/locales/ja.yml
Closes https://github.com/brave-intl/publishers/issues/3194
=> Update community email locations

app/models/channel.rb, db/migrate/20210823203807_add_derived_brave_publisher_id_to_channels.rb, db/schema.rb, lib/tasks/database_updates/backfill_derived_brave_publisher_id.rake, test/controllers/publishers/omniauth_callbacks_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/18
=> Set derived_brave_publisher_id in the channels table

app/controllers/concerns/search.rb
Closes https://github.com/brave-intl/publishers/issues/3382
=> Use Aurora supported index query for our email lookup.

app/javascript/views/walletServices/braveConnection/GeminiConnection.tsx
once we do support alternative currency payout for Gemini.
Closes https://github.com/brave-intl/publishers/issues/3370
=> Don't show the default currency panel for Gemini. Feel free to revert

app/models/publisher.rb
Closes https://github.com/brave-intl/publishers/issues/3404
This seems to have been accidentally added in https://github.com/brave-intl/publishers/pull/1825
=> Removes duplicate attr_encrypted field.

public/creators-landing/src/sections/main-section/signComponent/index.js
Fixes uncentered text on `Log in` button for creators.brav.com.
Context: https://twitter.com/BraveSampson/status/1442709494316810240
1. Step one
2. Step two
3. Step three
=> tweaks styling for login button on creators page

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
Closes https://github.com/brave-intl/publishers/issues/3403
=> Fix overall balance to not have negative values.

app/jobs/promo/email_breakdowns_job.rb
our daily emails.
Closes https://github.com/brave-intl/publishers/issues/3398
=> Fix EmailBreakdownsJob to properly count the number of confirmations in

app/views/admin/publishers/_channel.html.slim
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>
This PR Fixes #2719 
Enter a brief summary of the Pull Request - Features, motivations, and closes #2719
There was a typo in the text according to Issue 2719, fixed the message in the file according to issue description
=> Fixed Typo in Message - Fixes #2719

app/jobs/sync/connection/uphold_connection_sync_job.rb, app/models/publisher.rb, test/models/gemini_connection_test.rb
Closes https://github.com/brave-intl/publishers/issues/3419
=> Fixes arguments for Uphold and Gemini sync jobs.

app/models/uphold_connection.rb
=> Release 10-04-2021

app/controllers/publishers/wallets_controller.rb
currencies.
Closes https://github.com/brave-intl/publishers/issues/3422
=> Not all users will have a an uphold connection for checking possible

app/controllers/publishers/wallets_controller.rb, app/jobs/sync/connection/gemini_connection_sync_job.rb, app/models/uphold_connection.rb, app/services/uphold/refresher.rb, test/jobs/sync/connection/gemini_connection_sync_job_test.rb
=> Release 10-05-2021

app/services/uphold/models/authorization.rb, app/services/uphold/refresher.rb, public/creators-landing/yarn.lock
=> Better Uphold Refresh Error Handling

app/controllers/concerns/logout.rb, app/controllers/totp_registrations_controller.rb, app/controllers/u2f_registrations_controller.rb, app/models/publisher.rb, db/migrate/20211028205253_add_session_salt_to_publisher.rb, db/schema.rb, test/controllers/totp_registrations_controller_test.rb, test/controllers/u2f_registrations_controller_test.rb
Adds session_salt to authenticatable_salt.
Resolves https://github.com/brave-intl/publishers/issues/2179
1. Login
2. Enable 2fa/Change 2fa/Remove 2fa (if-enabled)
3. Other users should be logged out automatically
=> Adds session_token to authenticatable_salt.

app/controllers/concerns/logout.rb, app/controllers/totp_registrations_controller.rb, app/controllers/u2f_registrations_controller.rb, app/jobs/promo/email_breakdowns_job.rb, app/models/publisher.rb, db/migrate/20211028205253_add_session_salt_to_publisher.rb, db/schema.rb, test/controllers/totp_registrations_controller_test.rb, test/controllers/u2f_registrations_controller_test.rb
=> Release 11-02-2021

app/views/publishers/home.html.slim
=> Remove form to add unattached promo code (#3462)

app/models/uphold_connection.rb, test/models/uphold_connection_test.rb
=> Release 11-02-2021 #4

Gemfile, Gemfile.lock
To get rid of deploy error:
```
Step 23/26 : RUN RAILS_ENV=production SECRET_KEY_BASE="1" bundle exec rails assets:precompile DB_ADAPTER=nulldb DATABASE_URL='nulldb://nohost'
---> Running in c28d1cb107be
rails aborted!
LoadError: cannot load such file -- rexml/document
```
=> Add rexml for ruby 3

app/controllers/publishers_controller.rb, app/models/uphold_connection.rb, app/services/bitflyer/wallet_connection_syncer.rb, app/services/gemini/wallet_connection_syncer.rb, app/services/uphold/refresher.rb, app/services/uphold/wallet_connection_syncer.rb, app/services/util/wallet/connection_syncer.rb, app/views/publishers/_home_balances.html.slim, config/initializers/login_activities.rb, config/locales/en.yml, config/locales/ja.yml, test/services/util/wallet/connection_syncer_test.rb
=> Release 11-9-2021 #2

app/javascript/locale/en.ts, app/services/util/wallet/connection_syncer.rb, config/locales/en.yml, test/services/util/wallet/connection_syncer_test.rb
=> Release 11-10-2021

app/controllers/payment/connection/currencies_controller.rb, app/jobs/create_gemini_recipient_ids_job.rb, app/jobs/create_uphold_cards_job.rb, app/jobs/sync/bitflyer/update_missing_deposit_job.rb, app/mailers/publisher_mailer.rb, app/models/channel.rb, test/models/channel_test.rb
A number of bugfixes due to errors logged in New Relic, including backgrounding the Bitflyer deposit ID creation.
=> Newrelic bug cleanup

app/controllers/publishers_controller.rb, app/views/publishers/ensure_email.html.slim, config/initializers/login_activities.rb, config/locales/en.yml, config/locales/ja.yml, config/routes.rb, test/controllers/publishers_controller_test.rb
=> Release 11-16-20210 #2

app/models/site_banner.rb, config/secrets.yml, test/controllers/publishers/site_banners_controller_test.rb
=> Release 12-07-2021 #2

db/migrate/20211208230135_add_proper_index_to_site_banner_lookups.rb, db/schema.rb
=> Release 12-09-2021

app/models/publisher.rb
=> Release 10-10-2021

.github/workflows/build.yml, package.json, yarn.lock
1. Step one
2. Step two
3. Step three
=> Add bundler audit action

public/robots.txt
Fix https://github.com/brave-intl/publishers/issues/3509
1. Step one
2. Step two
3. Step three
=> Disallow all of publishers/ from crawling

app/jobs/promo/email_breakdowns_job.rb
This is the data as the dashboard displays it, i.e., we mark a download fiinalized today, but the download_ts
is what we go off of when generating this report. This means the confirmation is backported 30+ days.
The next section will include the report where we group by the finalized_ts, but that's only included
_additionally_ in the nightly CSV since the dashboard still groups data by the download_ts. That is, we still need
a section in the nightly CSV that matches the data you see on the dashboard.
=> Nightly report updates

.github/workflows/build.yml, public/creators-landing/package.json, public/creators-landing/yarn.lock
Fix https://github.com/brave-intl/publishers/issues/3508
1. Step one
2. Step two
3. Step three
=> Fix yarn audit errors in creators-landing

.github/workflows/build.yml
- build
- functional and integration tests
- local vulnerabilities
- libraries vulnerabilities
- type checking
- code style
Reorder build steps semantically, so that the failing step failing will be the least important ones.
1. Merge
2. Verify that the build order changed accordingly
=> github workflow: reorder build steps semantically

app/jobs/promo/email_breakdowns_job.rb, config/sidekiq.yml
This will give our referrers an idea of how much is owed. Countries taken from [here](https://support.brave.com/hc/en-us/articles/360025284131-What-do-the-referral-metrics-on-my-dashboard-mean-).
=> Update nightly CSV with region

app/javascript/analytics.js
Remove legacy cookies.  This should be ok though it's hard to tell as I don't think cookies have been enabled locally
Check console cookies.
=> task: Remove them cookies and maybe disable them?

.github/workflows/lint.yml, .github/workflows/test.yml, .standard.yml, app/controllers/concerns/logout.rb, app/controllers/concerns/two_factor_auth.rb, app/controllers/publishers/two_factor_authentications_removals_controller.rb, app/controllers/publishers_controller.rb, app/controllers/totp_authentications_controller.rb, app/controllers/totp_registrations_controller.rb, app/controllers/two_factor_authentications_controller.rb, app/controllers/u2f_authentications_controller.rb, app/controllers/u2f_registrations_controller.rb, app/services/pending_actions.rb, config/initializers/rack-attack.rb, test/controllers/totp_registrations_controller_test.rb, test/controllers/u2f_registrations_controller_test.rb, test/features/two_factor_registrations_test.rb, test/services/pending_actions_test.rb
Adds a generic step-up functionality.
This is helpful to implement several features which may require
step-up before an action is performed.
The idea behind is saving the action in a session and then
executing it after a successful step-up happened.
=> *: implement generic step-up

app/views/publishers/home.html.slim
Remove static content
We just maintain the URL and the header.  Moving along.
1. Step one
2. Step two
3. Step three
=> task: Remove static content

app/javascript/views/walletServices/braveConnection/VerifyButton.tsx, app/javascript/views/walletServices/braveConnection/upholdConnection/UpholdStatusMessage.tsx
1. Step one
2. Step two
3. Step three
=> fix: Do not render verification button when wallet is broken

app/models/concerns/user_feature_flags.rb, app/views/publishers/settings/index.html.slim, test/models/publisher_test.rb
Added basic feature flag for use in locales overhaul.
=> task: Add feature flags for location

Gemfile, Gemfile.lock
Path of least resistance for supporting locales/location differentiation
=> task: Add countries gem

.github/workflows/audit.yml, .github/workflows/test.yml
Run `test` on all pushes.  Run `audit` on push to staging.
=> task: Actions Updates

.github/workflows/semgrep.yml
Include semgrep app in `creators`
=> New workspace: semgrep

config/initializers/webauthn.rb, test/webauthn_config_test.rb
This is meant to be updating the supported algorithms policy to check that the new algorithms can be used for verification. This closes https://github.com/brave/security/issues/802
1. Use webauthn with an authenticator that uses one of the new algorithms
=> chore: update Webauthn config to align supported algorithms with policy

config/initializers/webauthn.rb, test/webauthn_config_test.rb
Should fix failing linting job in staging.
=> task: Fix lint

app/models/uphold_connection.rb, lib/oauth2/structs.rb, package.json, test/models/uphold_connection_test.rb, test/test_helpers/mock_oauth2_responses.rb, yarn.lock
- Security Patch
- Minor patch for updating refresh token logic
I sniff tested the updates in staging and didn't see anything off.
=> Patch Release 4/11/22

package.json, yarn.lock
This should get the general builds going again.  I'll see if I can do a more nuanced update this time.
=> task: Revert back to master values to try again

.github/workflows/lint.yml, app/jobs/oauth2_batch_refresh_job.rb, app/jobs/oauth2_refresh_job.rb, app/mailers/publisher_mailer.rb, app/models/oauth2/authorization_code_base.rb, app/views/publisher_mailer/wallet_refresh_failure.html.slim, config/locales/en.yml, sorbet/rails-rbi/mailers/publisher_mailer.rbi, sorbet/rails-rbi/models/bitflyer_connection.rbi, test/jobs/oauth2_batch_refresh_job_test.rb, test/jobs/oauth2_refresh_job_test.rb, test/mailers/previews/publisher_mailer_preview.rb
1. Core mailer logic for notifying users if a wallet connection has failed
2. Run container build before deploy
=> Release 4/25/22 - Wallet Refresh Failure Mailer, CI Updates

app/controllers/oauth2_controller.rb, app/models/bitflyer_connection.rb, app/models/gemini_connection.rb, app/models/oauth2/authorization_code_base.rb, app/models/uphold_connection.rb, config/secrets.yml, lib/oauth2/authorization_code_client.rb, lib/oauth2/config.rb, test/lib/oauth2/authorization_code_client_test.rb, test/lib/oauth2/config_test.rb
Implemements a strictly typed interface for Oauth2::AuthenticationCodeClient to:
1. Enforce a standard configuration abstraction for any authentication code oauth2 provider
2. Creates Seperate configuration container that can be independently inspected for debugging purposes.
3. Pulls non-secret values out of ENV and puts them in a testable format
4. Documents/implements the core requirements for all authentication code flows.
=> improvmement: Consolidate Oauth2 config

app/controllers/oauth2_controller.rb, app/models/bitflyer_connection.rb, app/models/gemini_connection.rb, app/models/oauth2/authorization_code_base.rb, app/models/uphold_connection.rb, config/secrets.yml, lib/oauth2/authorization_code_client.rb, lib/oauth2/config.rb, test/jobs/oauth2_refresh_job_test.rb, test/lib/oauth2/authorization_code_client_test.rb, test/lib/oauth2/config_test.rb, test/models/gemini_connection_test.rb
1. Consolidated Oauth2 config values and client API
2. Fix for unknown error handling.
=> Release 4/26/22 - Oauth2 Config and Minor Fixes

.github/workflows/audit.yml, app/views/publisher_mailer/wallet_refresh_failure.html.slim, config/locales/en.yml, test/mailers/previews/publisher_mailer_preview.rb
Updates en locale to requested content.
=> task: Update copy

.github/workflows/audit.yml, app/views/publisher_mailer/wallet_refresh_failure.html.slim, config/locales/en.yml, lib/oauth2/config.rb, test/bundler_audit_test.rb, test/lib/oauth2/config_test.rb, test/mailers/previews/publisher_mailer_preview.rb
1. Fixes incorrect url configuration for gemini refresh
2. Temporarily suspends rails audits to unblock prod deploy.
=> Release 4/28/22 - Gemini Refresh Fix [Expedite]

README.md, docs/TESTING.md
Updated the README.md and TESTING.md files.
=> task: update readme with build instructions

app/jobs/sync/bitflyer/update_missing_deposits_job.rb, app/models/channel.rb, test/models/channel_test.rb
Hard to debug in staging without being able to quickly see things.
=> improvement: Add scopes for debugging and sanity

config/initializers/login_activities.rb
Pretty sure this is breaking staging and it's not necessary.  The same thing is done in... a lot of places.
=> fix: Remove this, redundant, shouldn't be here, causing a fail

app/models/oauth2/authorization_code_base.rb
Not sure why the tests passed previously, but the exact functionality it was supposed to implement did not actually work.  I may just be tired and missed something obvious.  I'll try and come back and fix the sorbet stuff, but sorbet doesn't support abstract attributes which is annoying.
=> fix: Work around sorbet expectations

app/services/wallet/refresh_failure_notification_service.rb
=> improvement: Add exhaustiveness checks to notficiation service

app/javascript/locale/ja.ts, app/javascript/views/walletServices/braveConnection/BitflyerConnection.tsx, app/javascript/views/walletServices/braveConnection/GeminiConnection.tsx
=> improvement: Add connection error messaging for bitflyer

app/models/bitflyer_connection.rb, test/models/bitflyer_connection_test.rb, test/test_helpers/mock_oauth2_responses.rb
Resolves brave-intl/creators-private-issues#62
=> task: Handle bitflyer 403

app/javascript/locale/en.ts
=> fix: update duplicate gemini account language

app/jobs/sync/bitflyer/update_missing_deposits_job.rb, app/models/channel.rb, config/application.rb, test/controllers/channel_transfer_controller_test.rb, test/controllers/site_channels_controller_test.rb, test/jobs/channels/transfer_channels_job_test.rb, test/services/channels/contest_channel_test.rb
I tested the updated job in staging but there is no data that meets the necessary criteria so it doesn't tell me much.  It has been running (and failing) in prod so but I'm confident the underlying update machinery works so we might as well get this out there.
=> Prod Release 2: Deposit ID Fixes, Deployment Alert Notifications, Job enqueing fixes. 6/7/22

app/controllers/api/base_controller.rb, app/services/slack_messenger.rb, config/application.rb, config/secrets.yml
=> Update slack messenger and add github commit url to initialization message

app/controllers/api/base_controller.rb, app/services/slack_messenger.rb, config/application.rb, config/secrets.yml
1. Add some configurability to SlackMessenger
2. Post full github url for newly initialized environments.
3. Include request ip for unauthorized API request alerts.
=> Production Release: Notification Enhancements

config/initializers/rack-attack.rb
Rate limit update
Resolves #3727
=> security: Add rate limit to PATCH /publishers

config/initializers/rack-attack.rb
=> rack-attack: fix busted rate-limiter

app/jobs/channels/approve_channel_transfer_job.rb, app/jobs/sync/bitflyer/update_missing_deposits_job.rb, app/models/bitflyer_connection.rb, app/models/channel.rb, test/models/channel_test.rb
Remove callbacks and slow down bitflyer request rate limit for fun and profit.
=> Production Release: More bitflyer tweaks/debugging. (#3734)

app/models/channel.rb
https://one.newrelic.com/nr1-core/errors/overview/MjYwNDMwOXxBUE18QVBQTElDQVRJT058NTkyOTgwNzA3?account=2604309&duration=1800000&state=fdf70af1-23f9-ac60-ef95-c74b7830b101
=> task: Newrelic warning on this one

app/jobs/create_uphold_cards_job.rb
Newrelic alerting on this.  Trying to call method on a service failure result.
=> fix: Check response type

app/models/channel.rb
New relic also, I thought I had patched this but maybe it was another method.
=> fix: Guard clause

app/controllers/publishers_controller.rb, app/models/publisher.rb, test/models/publisher_test.rb
1. Moves the core confirmation logic into the publisher model, adds scaffold of specs in the model.
2. Implements the method in the controller.
=> poc: Unit test scaffold

app/controllers/oauth2_controller.rb
=> fix: Don't pass publisher for a few reasons

app/controllers/publishers_controller.rb, app/jobs/bitflyer_refresh_job.rb, app/jobs/gemini_refresh_job.rb, app/jobs/oauth2_batch_refresh_job.rb, app/jobs/uphold_refresh_job.rb, app/models/bitflyer_connection.rb, app/models/uphold_connection.rb, config/sidekiq.yml, sorbet/rails-rbi/models/uphold_connection.rbi, test/controllers/publishers_controller_test.rb, test/jobs/bitflyer_refresh_job_test.rb, test/jobs/gemini_refresh_job_test.rb, test/jobs/uphold_refresh_job_test.rb
1. Adds refresher jobs, though only Gemini is currently scheduled
2. Fixes an arg error causing 500s for some users.
=> Production Release: Oauth2 Refreshers and Email Confirmation Bugfix

test/lib/uphold/cards_test.rb, test/services/uphold/find_or_create_card_service_test.rb
This is just the addition of a few specs related to a newrelic error that I'm seeing.  The error is weird because it shouldn't be possible to even see it, these specs highlight that.  Perplexing...
=> task: Enhance spec

app/models/uphold_connection.rb
This is to help resolve one of the more frequent newrelic errors that may actually be impacting legitimate users.  This bug shouldn't be possible so I need additional info to figure out what is going on.
=> task: Add publisher ID to error

Gemfile, Gemfile.lock
=> task: Patch

Gemfile, Gemfile.lock, app/models/uphold_connection.rb
FML on that one.  The sorbet and standardrb linters got over a fight because of that line and I made the wrong choice.
=> Production Release: P1 patch for failure to assign refresh token.

.github/workflows/deploy.yml
Github Actions Generalized Deployment Update to `master`
Exposes `reproducible` flag in Generalized Deployment
=> Update Github Actions Generalized Deployment YAML in master

.github/workflows/deploy.yml
Fix staging going to dev, now to prod
=> Prod Release: Update deploy.yml (#3801)

app/models/publisher.rb, test/models/publisher_test.rb
* task: We don't know the circumstances under which someone is blocked by uphold, let's let them deal with it
* task: Increment to threshold
=> Production Release: Task/relax restriction - 7.27.22

app/models/uphold_connection.rb, test/controllers/payment/connection/uphold_connections_controller_test.rb, test/models/uphold_connection_test.rb, test/test_helpers/mock_uphold_responses.rb
Enforce requirement for "deposits" capability in order to create an uphold account.
=> enhancement: Block if not capability

app/models/uphold_connection.rb, test/controllers/payment/connection/uphold_connections_controller_test.rb, test/models/uphold_connection_test.rb, test/test_helpers/mock_uphold_responses.rb
I'm able to verify this on the backend as well as in local dev, but the UI in staging appears to be broken. I suspect that the staging eyeshade server is no longer active/available or something.
=> Production Release: Check for Uphold Capabilities

app/services/base_api_client.rb, lib/uphold/cards.rb
Should Resolve primary cause of #3803
=> Production Release: fix: Ensure content type header is passed to create card call (#3811)

app/javascript/locale/en.ts
=> task: Update Gemini and Uphold copy

app/models/uphold_connection.rb
=> task: Change copy

app/javascript/locale/en.ts, app/models/uphold_connection.rb
=> Production Release: Minor Copy Changes

app/models/uphold_connection.rb, test/models/uphold_connection_test.rb
Ignore deleted users for connection check.
brave-intl/creators-private-issues#105
=> task: Bypass this for now

README.md, app/models/uphold_connection.rb, docs/PROMO.md, test/models/uphold_connection_test.rb
Closes brave-intl/creators-private-issues#105
=> Production Release: Ignore deletes for uniqueness check

app/javascript/locale/en.ts
=> task: Move away from wallet nomenclature

app/jobs/oauth2_batch_refresh_job.rb, app/jobs/uphold_refresh_job.rb, test/jobs/uphold_refresh_job_test.rb
This was the fastest way I could come up with to up the limit for uphold without messing with the other jobs.
=> improvement: Easily configure limit

app/services/base_api_client.rb
Promo/referrals are throwing 500s in production right now.  I sniff tested in staging and didn't see anything off.
=> Production Release: Possible Promo Timeout Fix

app/services/promo/registrations_stats_fetcher.rb
=> task: Disable proxy url for promos only

app/services/promo/client.rb
I honestly just need to rewrite this set of jobs.
=> fix: Evidently there is also a client for promos

app/services/promo/client.rb
There are a number of other timeout errors occurring related to promos, this should fix it for this set of cases.
=> Production Release: More Promos Fixes

app/jobs/sync/channel_promo_registrations_stats_job.rb, app/jobs/sync/promo_registration_stats_job.rb, app/models/promo_registration.rb, app/services/promo/registrations_stats_fetcher.rb, config/sidekiq.yml, test/jobs/sync/channel_promo_registrations_stats_job.rb, test/jobs/sync/promo_registrations_stats_job_test.rb
Sniff tested this in staging, basics looked solid, will need to check in prod on a test set to get a real sense of resolve.
=> Production Release: Promo stats job performance enhancements

app/jobs/sync/channel_promo_registrations_stats_job.rb, app/models/promo_registration.rb
Takes the number of records queued from 500k to 1k.  so... should be pretty performant.
=> task: Scope to only users in referral program

app/jobs/cache/browser_channels/responses_for_prefix.rb
Addresses conversation here: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1666284383413589
=> add wallet address fallback for uphold accounts

app/controllers/api/v3/public/channels_controller.rb, app/models/bitflyer_connection.rb, app/models/concerns/wallet_provider_properties.rb, config/routes.rb, test/controllers/api/v3/channels_controller_test.rb
Creator's portion of https://github.com/brave-intl/eyeshade-ops/issues/109#issue-1329032579.  The endpoint will change slightly as https://github.com/brave-intl/creators-private-issues/issues/115 is added in, but this should be enough to allow development on the Eyeshade portion.
=> add in api endpoint and test

app/javascript/locale/en.ts, app/javascript/views/walletServices/braveConnection/GeminiConnection.tsx, app/javascript/views/walletServices/braveConnection/NotConnected.tsx, app/javascript/views/walletServices/braveConnection/upholdConnection/UpholdStatusMessage.tsx, test/fixtures/publishers.yml
Added the warning for Non-KYC publishers, bugfix for the blocked countries message, and an update to the fixtures to make local testing easier.
=> Non-KYC warning

.semgrepignore
This removes false positives that would appear from semgrep when running on ruby test files which are quite common in this repository.
N/A
=> Add ruby test files to .semgrepignore

app/jobs/cache/browser_channels/responses_for_prefix.rb, test/jobs/cache/browser_channels/responses_for_prefix_test.rb
Resolves conversation at https://bravesoftware.slack.com/archives/C8GJLTQHW/p1666869515885059
=> fix: add selected wallet provider check to all wallet types

app/jobs/cache/browser_channels/responses_for_prefix.rb, test/jobs/cache/browser_channels/responses_for_prefix_test.rb
Addresses https://github.com/brave-intl/creators-private-issues/issues/125
=> remove account-level fallback for gemini recipient ids

app/services/payout/service.rb, test/services/payout/uphold_service_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/131
=> Include referrers in payout even if in a suspended country

app/models/publisher.rb, app/services/enqueue_publishers_for_payout_service.rb, app/services/payout/bitflyer_service.rb, app/services/payout/gemini_service.rb, app/services/payout/uphold_service.rb, db/migrate/20221123220112_add_whitelisting_to_potential_payments.rb, db/schema.rb
To better aid in detecting whether to let a creator through, we will include whitelisting status in the potential payments.
Closes https://github.com/brave-intl/creators-private-issues/issues/132
=> Add whitelisting to potential payouts

app/models/channel.rb
Addresses https://github.com/brave-intl/creators-private-issues/issues/137
=> add additional channel types to admin channel search

app/jobs/create_gemini_recipient_ids_job.rb, app/jobs/create_uphold_channel_card_job.rb, lib/tasks/database_updates/backfill_gemini_channel_recipient_ids.rake
Addresses https://github.com/brave-intl/creators-private-issues/issues/159
=> Allow retries for card creation jobs

lib/tasks/update_publisher_statuses.rake
We at times need to de-whitelist some creators.
=> Add de-whitelisting task

lib/tasks/update_publisher_statuses.rake
Enhancement to dewhitelist via new record and keep history.
=> Dewhitelist via new record

app/views/publishers/_home_balances.html.slim, config/locales/en.yml
=> Adding new referral sunset language

app/services/base_api_client.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/116
Attempted [here](https://github.com/brave-intl/publishers/pull/3838) as well, will make sure other services will work this time.
=> Remove communicating through proxy to internal services

app/controllers/publishers/site_banners_controller.rb, app/javascript/packs/banner_editor.jsx, app/javascript/packs/style.jsx, app/models/site_banner.rb, test/controllers/publishers/site_banners_controller_test.rb, test/models/site_banner_test.rb
=> remove default tipping from UI

Gemfile, Gemfile.lock, app/controllers/publishers/omniauth_callbacks_controller.rb, config/initializers/devise.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1594
=> update twitter omniauth gem

app/jobs/cache/browser_channels/responses_for_prefix.rb
resolves https://github.com/brave-intl/creators-private-issues/issues/1600
=> remove reference to donation amounts

lib/tasks/database_updates/migrate_old_encrypted_fields_to_rails_7.rake
Use `in_batches` to go through UpholdConnections 10000 at a time, then bulk insert 1000 at a time.
=> Don't load all UpholdConnections at conce

Dockerfile.dev, Gemfile, Gemfile.lock, app/models/channel.rb, app/models/crypto_address.rb, app/models/crypto_address_for_channel.rb, app/models/publisher.rb, config/initializers/add_column_types_to_null_db.rb, db/migrate/20230320211516_add_public_name_and_public_identifier_to_channel.rb, db/migrate/20230320212718_create_crypto_addresses.rb, db/migrate/20230320213156_create_crypto_address_for_channels.rb, db/schema.rb, test/fixtures/crypto_address_for_channels.yml, test/fixtures/crypto_addresses.yml, test/models/channel_test.rb, test/models/crypto_address_for_channel_test.rb, test/models/crypto_address_test.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/140
=> Add in new p2p data models and adjust channel model

app/models/uphold_connection.rb, test/models/uphold_connection_test.rb
* Green Uphold Status even if refresh token issues
=> Prod Release: 04-05-2023

package.json, yarn.lock
=> request override

package.json, yarn.lock
Update node-sass to 8.0.0
Update 8.0.0
1. Verify if `node-sass` works properly
=> Update node-sass to 8.0.0 

app/jobs/cache/browser_channels/responses_for_prefix.rb, app/models/crypto_address_for_channel.rb, protos/channel_responses.proto, protos/channel_responses.rb, test/fixtures/channels.yml, test/jobs/cache/browser_channels/responses_for_prefix_test.rb
resolves https://github.com/brave-intl/creators-private-issues/issues/141
=> add crypto addresses to pCDN

app/controllers/publishers/wallets_controller.rb, app/javascript/locale/en.ts, app/javascript/locale/ja.ts, app/javascript/views/walletServices/braveConnection/GeminiConnection.tsx, app/javascript/views/walletServices/braveConnection/UpholdConnection.tsx, app/javascript/views/walletServices/braveConnection/upholdConnection/UpholdStatusMessage.tsx, test/features/payout_in_progress_test.rb, test/fixtures/bitflyer_connections.yml, test/fixtures/channels.yml, test/fixtures/publishers.yml, test/fixtures/site_channel_details.yml, test/jobs/bitflyer_refresh_job_test.rb, test/models/channel_test.rb, test/test_helper.rb
Also Uphold & Bitflyer E2E tests
Followup for https://github.com/brave-intl/creators-private-issues/issues/1635
Waiting on Japanese translation approval
=> Bitflyer translation for failed wallet

Gemfile, Gemfile.lock, app/services/log_exception.rb, config/locales/en.yml
Closes https://github.com/brave-intl/creators-private-issues/issues/446
Closes https://github.com/brave-intl/creators-private-issues/issues/170
=> Title change

app/views/layouts/application.html.slim, test/features/sign_up_test.rb
We had an issue registering keys in staging, this resolves that.
An extension of https://github.com/brave-intl/publishers/pull/3533
=> We don't use U2F anymore, but webauthn

app/javascript/packs/banner_editor.jsx, app/javascript/packs/banner_preview.jsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1653
=> add hard-coded default donations, fix banner editor bug

public/.well-known/gpc.json
Resolves https://github.com/brave-intl/creators-private-issues/issues/339
https://creators.brave.com/.well-known/gpc.json will now return a static json file
This is part of Brave Global Privacy Control initiative 
https://brave.com/web-standards-at-brave/4-global-privacy-control/
=> Adds gpc.json file to public directory

app/models/totp_registration.rb
Updates the app name users will see when using a 2FA application like Google Authenticator
=> Update issuer name for 2FA

app/mailers/publisher_mailer.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1655
Adds missing variable for Verification Success email subject heading
=> Adds publication_title variable to email template

test/features/log_in_test.rb, test/features/sign_up_test.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1661
Fixes two tests.
One from a copy change to the home-page and another that has been failing intermittently the last few weeks.
=> Fix failing signup/login tests

config/locales/en.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1659
Updates copy for contested channel email
=> Updates email subject and intro for Contested Channel Email

app/views/publishers/_promo_panel.html.slim
Resolves https://github.com/brave-intl/creators-private-issues/issues/138
Removes referral promo alert
=> Removes outdated promo alert

Dockerfile, Dockerfile.dev
Closes https://github.com/brave-intl/creators-private-issues/issues/1663
=> Pin rust until our image resizer is updated

.semgrepignore
.semgrepignore: add config test environment file
add config test environment file
https://github.com/brave-intl/publishers/pull/4109#discussion_r1268633782
Don't
=> .semgrepignore: add config test environment file

Gemfile.lock, app/models/stats_redshift/redshift.rb
=> Staging debug

Gemfile, Gemfile.lock
Closes https://github.com/brave-intl/creators-private-issues/issues/1671
=> Switch to fork which fixed closed? bug

app/views/publishers/registrations/log_in.html.slim
Closes https://github.com/brave-intl/creators-private-issues/issues/1686
=> Remove Legacy Youtube login

app/jobs/create_channel_banners_from_default_site_banners.rb, lib/tasks/database_updates/create_unique_site_banner_details_for_each_channel.rake
small cut/paste errors from adjusting the original job.
=> fix errors with banner job

Gemfile, Gemfile.lock, app/jobs/create_public_identifiers_job.rb, config/initializers/sidekiq.rb, lib/tasks/database_updates/backfill_channel_public_identifiers.rake
Security review: https://github.com/brave/reviews/issues/1406
=> update task to run no more than 2 jobs at once

amplify.yml
1. Step one
2. Step two
3. Step three
=> Update PUBLISHERS_HOST in amplify.yml

renovate.json
renovate.json: add org-level config
CI
N/A CI
N/A CI
=> renovate.json: add org-level config

.github/workflows/audit.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/security.yml, .github/workflows/test.yml
Pin deps to block tag squatting
=> ci: pin deps

app/assets/stylesheets/pages/home.scss, app/controllers/publishers/wallets_controller.rb, app/javascript/views/walletServices/BraveConnection.tsx, app/javascript/views/walletServices/braveConnection/NotConnected.tsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1601
=> add in tooltip and region link

app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
resolves https://github.com/brave-intl/creators-private-issues/issues/1711
=> update prices every 5 minutes

.github/workflows/deploy.yml
Related to https://github.com/brave-intl/bsg-infra/issues/426
Related PR https://github.com/brave-intl/general-docker-build-pipeline/pull/40
1. Step one
2. Step two
3. Step three
=> Update deploy.yml to use IAM Role

public/creators-landing/src/locale/en.js
Text updates that:
* Changes "tip" language to "contribute" language
* Rewords a couple things to bring the copy up to date 
Context: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1699941679044079
=> update "tip" language to "contribute" language and update content

app/services/payout/bitflyer_service.rb, test/services/payout/bitflyer_service_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1715
=> Don't send channels with blank Bitflyer deposit IDs

config/environments/production.rb, config/environments/staging.rb
Security Headers Policy: https://github.com/brave/devops/wiki/Security-Headers
Referrer-Policy: referer header will be omitted cross-origin
Strict-Transport-Security: altered age, added preload, should override the HSTS header provided by config.force_ssl
Cross-Origin-Opener-Policy: isolates process, prevents cross-origin cross-window access e.g. via window.opener
Currently, I don't believe there are resources which are loaded from other domains. Connections to external sites are via redirection and do not rely on inter-window communication. Still, worth testing that things work as expected.
=> Implement Security Headers Policy

app/jobs/channels/update_site_banner_lookup_job.rb, app/models/site_banner.rb, lib/tasks/database_updates/null_out_site_banners_with_no_attachment.rake, test/controllers/publishers/site_banners_controller_test.rb, test/models/site_banner_lookup_test.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1718
=> Send empty string to pCDN if using default banners

app/assets/stylesheets/pages/crypto-wallets.scss, app/javascript/locale/en.ts, app/javascript/packs/CryptoWalletServices.jsx, app/javascript/views/cryptoWalletServices/CryptoPrivacyModal.jsx, app/javascript/views/cryptoWalletServices/CryptoWalletServices.jsx, test/features/site_channel_verification_test.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1678
https://github.com/brave-intl/publishers/assets/4231556/c00ac8c9-eb65-46ab-9835-57a512094016
=> add privacy modal when address is in use

app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
=> fix vertical alignment on channel page dropdown

app/javascript/packs/SettingsPage.tsx, app/models/publisher.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1662
=> Admins have longer login

app/models/gemini_connection.rb, app/services/gemini/get_validation_service.rb, test/models/gemini_connection_test.rb, test/services/payout/gemini_get_validation_service_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1675
=> Add validate endpoint service class

app/models/publisher.rb, app/models/publisher_status_update.rb, test/controllers/api/v1/publishers_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1726
=> Ensure suspensions always add a previously deleted record

app/models/gemini_connection.rb, test/fixtures/gemini_connections.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1706
=> override allowed_countries list for gemini

app/controllers/public_channel_controller.rb, app/helpers/publishers_helper.rb, app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx, app/javascript/views/publicChannelPage/PublicChannelPageStyle.js, app/views/layouts/public.html.slim, config/locales/en.yml
resolves https://github.com/brave-intl/creators-private-issues/issues/1722
resolves https://github.com/brave-intl/creators-private-issues/issues/1731
resolves https://github.com/brave-intl/creators-private-issues/issues/1734
=> update styling and title on public page

app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx, app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
resolves https://github.com/brave-intl/creators-private-issues/issues/1742
=> Update dropdown styles

app/controllers/public_channel_controller.rb, app/helpers/publishers_helper.rb, app/views/layouts/public.html.slim, config/locales/en.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1741
Also added language detection back into the public layout file.
=> update meta tags

app/controllers/public_channel_controller.rb, app/views/publishers/_channel.html.slim
Removes the p2p feature flag and opens the feature for all users.
=> remove feature flag screens

app/views/publisher_mailer/channel_contested.slim, test/mailers/publisher_mailer_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1758
=> Fix contested channel email bug

app/javascript/locale/en.ts, app/javascript/locale/ja.ts, app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx, app/javascript/views/publicChannelPage/PublicChannelPageStyle.js, app/javascript/views/publicChannelPage/TryBraveModal.jsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1752
Resolves https://github.com/brave-intl/creators-private-issues/issues/1749
Resolves https://github.com/brave-intl/creators-private-issues/issues/1751
https://github.com/brave-intl/publishers/assets/4231556/68b30866-1861-4027-9c66-62c4fa94b046
=> fix try brave modal bug and clear error messages on chain change

lib/error_handler.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1761
=> Don't throw an exception/500 on invalid CSRF token, redirect instead

app/jobs/channels/approve_channel_transfer_job.rb, test/jobs/channels/approve_channel_transfer_job_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1762
=> Fix error throwing in Channel Transfer Job

app/javascript/locale/ja.ts, app/javascript/views/cryptoWalletServices/CryptoWalletServices.jsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1749
https://github.com/brave-intl/publishers/assets/4231556/1128e3f1-c063-4e50-a741-06f9cfa1a935
=> JP translations and add try brave modal to publishers dashboard

config/sidekiq.yml
Working toward resolving https://github.com/brave-intl/creators-private-issues/issues/1764
=> Run every 2 hours to debug sidekiq killing it

app/validators/html_validator.rb, test/models/publisher_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1697
=> Add error to pub on html char

app/jobs/enqueue_site_channel_verifications.rb, app/jobs/verify_site_channel.rb, test/jobs/enqueue_site_channel_verifications_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1765
=> Call without named args as sidekiq doesn't support

app/jobs/create_uphold_channel_card_job.rb, app/services/uphold/models/card.rb, test/jobs/create_uphold_channel_card_job_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1768
=> Fix Faraday 401 Unauthorized for UpholdCardCreation

app/models/gemini_connection.rb, app/services/gemini/get_validation_service.rb
In service of https://github.com/brave-intl/creators-private-issues/issues/1769
=> Add additional logging

app/services/enqueue_publishers_for_payout_service.rb
Working towards https://github.com/brave-intl/creators-private-issues/issues/1764
=> An experiment in smaller batch sizes for payout report processing

app/controllers/publishers/registrations_controller.rb, test/controllers/publishers/registrations_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1770
=> Fix expired_authentication_token tests

app/jobs/channels/approve_channel_transfer_job.rb, test/jobs/channels/approve_channel_transfer_job_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1771
=> Log when a typcial ApproveChannel error occurs, don't raise

lib/error_handler.rb, test/controllers/publishers_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1773
=> Add test for Stepup

.audit-ci.json, Dockerfile, Dockerfile.dev, docker-compose.yml, scripts/entrypoint-nextjs.sh
Closes https://github.com/brave-intl/creators-private-issues/issues/1774
=> Enable NextJS deploy using main Dockerfile

Dockerfile, Dockerfile.dev
1. Step one
2. Step two
3. Step three
=> Add copyLeoIcons.js script to build

package.json, yarn.lock
resolves https://github.com/brave-intl/publishers/security/dependabot/182
=> remove hoek

config/routes.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1780
=> Eliminate old route

app/controllers/application_controller.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1781
=> No more need for rails-based http auth, k8s can handle it

app/controllers/api/v3/public/ofac_controller.rb, app/services/parse_ofac_list_service.rb, config/routes.rb, config/secrets.yml, test/controllers/api/v3/public/ofac_controller_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1784
=> Add an OFAC api for banned addresses

.github/workflows/security.yml
N/A
fix a CI security pass to include user name, when triggered.
N/A, ci concern
=> security.yml: add gh_to_slack_user_map: GH_TO_SLACK_USER_MAP

Gemfile.lock
This reverts commit e929c2e344cba9c8bf214f18a79974f108a61728.
1. Step one
2. Step two
3. Step three
=> Revert "build(deps-dev): bump yard from 0.9.35 to 0.9.36 (#4377)"

nextjs/src/lib/api.ts
Closes https://github.com/brave-intl/creators-private-issues/issues/1787
=> StatusText is no longer supported in http2, use status instead

nextjs/src/app/[locale]/publishers/security/page.tsx
Closes https://github.com/brave-intl/creators-private-issues/issues/1788
=> Properly scope u2f_registrations key

app/controllers/api/nextv1/publishers_controller.rb, config/routes.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1788
=> Route interfereing with API

nextjs/package-lock.json, nextjs/package.json, nextjs/scripts/create-local-server.js
Closes https://github.com/brave-intl/creators-private-issues/issues/1790
=> Add http auth when available, fix local dev server flakiness

nextjs/scripts/create-local-server.js
Closes https://github.com/brave-intl/creators-private-issues/issues/1790
=> Don't basic auth for health check

app/controllers/application_controller.rb, nextjs/scripts/create-local-server.js, nextjs/src/app/[locale]/publishers/layout.tsx
resolves https://github.com/brave-intl/creators-private-issues/issues/1800
=> fix new UI logo and JP locale redirect issue

config/initializers/omniauth.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1803
=> override full host for omniauth

.audit-ci.json, config/routes.rb, config/webpack/webpack.config.js, nextjs/src/app/[locale]/publishers/settings/page.tsx, package.json, yarn.lock
Resolves https://github.com/brave-intl/creators-private-issues/issues/1805
=> A user could not delete himself from the new UI

config/initializers/omniauth.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1808
For testing, keep the URL the default
=> Only set the FULL_HOST in non-test envs

app/controllers/api/base_controller.rb, config/initializers/active_analytics.rb, package.json, yarn.lock
Closes https://github.com/brave-intl/creators-private-issues/issues/1812
=> Check remote IP via the proxy in all IP check cases

config/webpack/webpack.config.js, package.json, yarn.lock
Resolves https://github.com/brave-intl/creators-private-issues/issues/1813
=> Remove unneeded module

config/initializers/devise.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1795
=> Limit twitter oauth scope

config/sidekiq.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1816
=> Correct CRON syntax error

config/locales/en.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1738
=> updated language for the add a channel info box

test/helpers/publishers_helper_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1821
=> Fix broken balance test

config/initializers/devise.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1822
Reverts brave-intl/publishers#4421
This broke our X integration, we need at least these 2
=> Revert "Limit twitter oauth scope"

app/jobs/banned_address_job.rb, app/models/crypto_address.rb, app/services/wallet/disconnect_invalid_p2p_address_service.rb, app/validators/banned_address_validator.rb, config/sidekiq.yml, test/models/crypto_address_test.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1824
=> Nightly job to delete banned addresses

nextjs/src/app/[locale]/publishers/settings/page.tsx, nextjs/src/app/[locale]/publishers/totp_registrations/new/page.jsx, nextjs/src/app/[locale]/publishers/u2f_registrations/new/page.tsx
bugfix for input issues found on prod: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1717523390063649
=> update input return values

Gemfile, Gemfile.lock
Closes https://github.com/brave-intl/creators-private-issues/issues/1833
=> Update to upstream minitest-rails

app/controllers/api/nextv1/oauth2_controller.rb, nextjs/package.json, nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/home/custodianServices/CustodianServiceWidget.jsx, nextjs/src/app/[locale]/publishers/home/page.tsx, nextjs/src/app/[locale]/publishers/layout.jsx, nextjs/src/lib/api.ts, nextjs/src/styles/ChannelCard.module.css, nextjs/src/styles/Layout.module.css
Included here:
- leo update
- getting rid of the reference to callback in the oauth2 api endpoint
- Some small styling fixes
- Fixing remove button on the channel card
- Ensuring only bitflyer option appears when location is Japan
- removing the theme slider for now
=> further wallet provider oauth fixes and additional styling fixes

protos/channel_responses.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1836
=> Fix unknown fields in channel_responses

app/jobs/cache/browser_channels/responses_for_prefix.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1838
=> Remove nil error for sending addresses through pCDN

nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/home/channels/CryptoWalletOption.jsx, nextjs/src/lib/api.ts, nextjs/src/messages/en.json, nextjs/src/styles/ChannelCard.module.css
Resolves https://github.com/brave-intl/creators-private-issues/issues/1840
=> fix channel card styles

nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/settings/page.tsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1846
=> Properly Close the Delete Dialog

nextjs/src/app/[locale]/publishers/home/custodianServices/CustodianServiceWidget.jsx, nextjs/src/messages/en.json, nextjs/src/messages/ja.json
Resolves: https://github.com/brave-intl/creators-private-issues/issues/1844
=> update jp translations

nextjs/src/app/[locale]/publishers/home/channels/AddChannelModal.tsx, nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/home/page.tsx, nextjs/src/app/[locale]/publishers/layout.jsx, nextjs/src/components/Card.tsx, nextjs/src/components/Container.tsx, nextjs/src/styles/Layout.module.css, nextjs/src/styles/globals.css
Resolves: https://github.com/brave-intl/creators-private-issues/issues/1841
=> add mobile styling

app/controllers/api/nextv1/home_controller.rb, app/controllers/publishers/site_banners_controller.rb, app/javascript/packs/style.jsx, nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/home/page.tsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1843
=> fix layout and styling issues with contribution banner

nextjs/package-lock.json
Looks like the package lock json was out of sync with what was in the package.json for the nextJS app. This corrects that.
=> Correcting package.lock

nextjs/src/app/[locale]/publishers/home/custodianServices/CustodianServiceWidget.jsx, nextjs/src/app/[locale]/publishers/home/page.tsx, nextjs/src/app/[locale]/publishers/layout.jsx, nextjs/src/app/[locale]/publishers/security/page.tsx, nextjs/src/app/[locale]/publishers/settings/page.tsx, nextjs/src/app/[locale]/publishers/totp_registrations/new/page.jsx, nextjs/src/app/[locale]/publishers/u2f_registrations/new/page.tsx, nextjs/src/styles/ChannelCard.module.css, nextjs/src/styles/Dashboard.module.css
- re-adds close button for add channel modal
- fixes spacing on the settings and security pages
- fix spacing on account details card
- adjust spacing and size for channel crypto dropdown crypto and trash can icons
- fix nav menu height
- change color of disconnect button
=> styling adjustments

nextjs/src/app/[locale]/publishers/home/channels/ChannelCard.tsx, nextjs/src/app/[locale]/publishers/layout.jsx, nextjs/src/app/[locale]/publishers/security/page.tsx, nextjs/src/components/Container.tsx, nextjs/src/messages/en.json, nextjs/src/messages/ja.json, nextjs/src/styles/Layout.module.css, nextjs/src/styles/globals.css, nextjs/src/styles/variables.css
Resolves https://github.com/brave-intl/creators-private-issues/issues/1851
Resolves https://github.com/brave-intl/creators-private-issues/issues/1849
Resolves https://github.com/brave-intl/creators-private-issues/issues/1852
=> Add footer and small text fixes

nextjs/src/app/[locale]/publishers/home/custodianServices/CustodianServiceWidget.jsx, nextjs/src/messages/en.json, nextjs/src/messages/ja.json
Resolves https://github.com/brave-intl/creators-private-issues/issues/1860
=> make wrong region message provider specific

config/environments/production.rb, config/environments/staging.rb
Fixes https://github.com/brave-intl/creators-private-issues/issues/1662
=> Don't expire the sessions in redis so soon

app/controllers/api/nextv1/contribution_page_controller.rb, nextjs/src/app/[locale]/publishers/contribution_page/page.jsx, public/creators-landing/package.json, public/creators-landing/yarn.lock
Addressing this issue here: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1727263166958319
=> fix reference error and add padded extension back in

public/creators-landing/yarn.lock
Addresses https://github.com/brave-intl/publishers/security/dependabot/251
=> updated cross-spawn

nextjs/src/styles/PublicChannelPage.module.css
Resolves https://github.com/brave-intl/creators-private-issues/issues/1878
=> remove background image

app/jobs/change_site_banner_title_from_default_to_publication_title_job.rb, app/models/site_banner.rb, lib/tasks/database_updates/set_default_site_banner_titles_to_channel_publication_title.rake
Resolves https://github.com/brave-intl/creators-private-issues/issues/1884
=> correct default name and create job to backfill publication title

nextjs/src/app/[locale]/c/[public_identifier]/CryptoPaymentWidget.jsx, nextjs/src/styles/PublicChannelPage.module.css
Resolves https://github.com/brave-intl/creators-private-issues/issues/1883
=> added crypto denomination to amount field

app/controllers/api/nextv1/public_channel_controller.rb, nextjs/src/app/[locale]/c/[public_identifier]/CryptoPaymentWidget.jsx, nextjs/src/app/[locale]/c/[public_identifier]/PublicChannelPage.jsx
Addresses bug discussed here: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1738215191484249
=> read rpc address from current url

config/sidekiq.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1894
=> update frequency of ofac chron jobs

public/creators-landing/yarn.lock
Resolves https://github.com/brave-intl/publishers/security/dependabot/269
=> resolved serialize-javascript to 6.0.2

app/jobs/cache/browser_channels/prefix_list.rb
Address issue discussed here: https://bravesoftware.slack.com/archives/C8GJLTQHW/p1739906575367139
=> sort dummy values

docs/NETWORKS.md, docs/PROMO.md, nextjs/src/styles/variables.css
Nala references 'inter variable', but the app can only recognize 'Inter' (even though 'inter' is a variable font).
I only corrected a few misspellings in the readmes, despite what the diff is showing.
=> replace nala references for inter variable with inter

.github/workflows/audit.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> fix: autopin dependencies

app/helpers/publishers_helper.rb
Resolves security discussion started here: https://bravesoftware.slack.com/archives/C6R461GF4/p1743342543345879
=> adjust name from email function

nextjs/next.config.js
Issue: https://github.com/brave/internal/issues/1263
=> add no-cache headers

app/controllers/admin/channels_controller.rb, app/controllers/api/nextv1/crypto_address_for_channels_controller.rb, app/services/wallet/disconnect_invalid_p2p_address_service.rb, app/views/admin/channels/index.html.slim, config/routes.rb, docker-compose.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1904
Includes changes needed to test on staging for https://github.com/brave-intl/creators-private-issues/issues/1903
=> Feat/admin OFAC button

.github/workflows/test.yml, app/controllers/api/nextv1/crypto_address_for_channels_controller.rb, docker-compose.yml, test/cassettes/rewards-parameters.yml, test/controllers/api/nextv1/crypto_address_for_channels_controller_test.rb, test/test_helper.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1903
=> Remove unnecessary logging

nextjs/src/app/[locale]/publishers/home/channels/ChannelCryptoEditor.jsx, nextjs/src/app/[locale]/publishers/home/channels/CryptoWalletOption.jsx
fixes a bug where the window will close when a crypto address is deleted. disallows typing in the select dropdown.
=> remove unnecessary call to close

app/controllers/admin/referral_totals_controller.rb, app/models/referral_totals.rb, app/views/admin/referral_totals/index.html.slim, app/views/admin/shared/_sidebar.html.slim, config/routes.rb, db/migrate/20250716225001_create_referral_totals.rb, db/schema.rb, lib/tasks/database_updates/migrate_eyeshade_referral_totals.rake, public/creators-landing/yarn.lock, yarn.lock
memoize some computed data from eyeshade so that the database can be conveniently archived.
=> add rake task and admin access for referral totals table

app/controllers/api/nextv1/home_controller.rb, nextjs/src/app/[locale]/publishers/home/page.jsx
resolves https://github.com/brave-intl/creators-private-issues/issues/1923
=> pass flash messages to the front end on dashboard

app/controllers/api/nextv1/public_channel_controller.rb, nextjs/src/app/[locale]/publishers/home/channels/ChannelCryptoEditor.jsx, nextjs/src/app/[locale]/publishers/home/channels/CryptoRemovalModal.jsx, nextjs/src/messages/en.json
Resolves https://github.com/brave-intl/creators-private-issues/issues/1925
Resolves https://github.com/brave-intl/creators-private-issues/issues/1928
=> add notice modal and fix public_name query bug

app/javascript/application.js, app/javascript/packs/admin.js, app/javascript/packs/admin_case.js, app/javascript/packs/application.js, config/importmap.rb, package.json, yarn.lock
Resolves https://github.com/brave-intl/creators-private-issues/issues/1930
=> remove @rails/ujs library
