brave-intl/publishers

- README.md
> Updated README after doing the setup on my local machine :)

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application/publishers.sass
- app/views/publishers/verification_dns_record.html.slim
Fix #28
Auditors @bradleyrichter @bsclifton 
Do these look ok? Did I add the gem in the correct way? :)
> copy to clipboard buttons

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/application/publishers.sass
- app/assets/stylesheets/shared/popover.scss
- app/helpers/application_helper.rb
- app/views/application/_popover.html.slim
- app/views/publishers/verification_dns_record.html.slim
- config/locales/en.yml
- vendor/assets/stylesheets/css-modal/_modal-animations.scss
- vendor/assets/stylesheets/css-modal/_modal-config.scss
- vendor/assets/stylesheets/css-modal/_modal-core.scss
- vendor/assets/stylesheets/css-modal/_modal-element.scss
- vendor/assets/stylesheets/css-modal/_modal-theme.scss
- vendor/assets/stylesheets/css-modal/modal.scss
Fix #27
Auditors @bradleyrichter @ayumi @bsclifton 
Alright. Thanks to @ayumi I got this working. How does it look to you all?
> Added DNS helper popover

- app/assets/stylesheets/application/publishers.sass
- app/views/publishers/verification_dns_record.html.slim
- config/locales/en.yml
Fix #41 
Auditors @bradleyrichter @bsclifton 
Here's what it looks like!
> Add contact brave support link to popover

- config/locales/en.yml
Fixes https://github.com/brave/publishers/issues/44
Auditor: @bradleyrichter
> Updated intro text

- app/views/publishers/new.html.slim
Fixes https://github.com/brave/publishers/issues/61
Looks like this is all that is required; I tested it out locally, looks good 😄
> Phone number is now required at time of sign up

- Gemfile
- Gemfile.lock
- app/jobs/enqueue_publisher_verifications.rb
- test/fixtures/publishers.yml
- test/jobs/enqueue_publisher_verifications_test.rb
> Pause auto checking domain verifications after 6 weeks

- app/services/publisher_verifier.rb
- config/newrelic.yml
> Reduce new relic tracking

- app/mailers/publisher_mailer.rb
- app/models/publisher.rb
- app/views/publisher_mailer/bitcoin_address_changed.html.slim
- config/locales/en.yml
- test/models/publisher_test.rb
Added email copy and branched off staging. Thanks @bigeasy!
Fix #88
Fix #59
> Send email notification when Bitcoin address changes

- app/controllers/api/publishers_controller.rb
- config/routes.rb
- db/migrate/20170720004738_add_created_via_api_to_publishers.rb
- db/schema.rb
- test/controllers/api/publishers_controller_test.rb
> Add Api::Publishers #create

- app/controllers/api/publishers_controller.rb
- config/routes.rb
- test/controllers/api/publishers_controller_test.rb
- test/fixtures/publishers.yml
> Introduce API endpoint to delete publishers

- config/locales/en.yml
> Adjust landing page copy to "BAT wallet"

- app/controllers/publishers_controller.rb
> Associate pending_email with session for created publishers

- app/assets/stylesheets/application/static.sass
- app/assets/stylesheets/variables/colors.scss
- app/views/static/index.html.slim
- config/locales/en.yml
Restructures the landing page content to place the buttons to the right of the input fields and text.
> Bring the landing page appearance in line with #50

- app/models/publisher.rb
> only Publisher#generate_verification_token if brave_publisher_id present

- app/views/publishers/create_done.html.slim
> Move class from form to button

- config/initializers/verify_config.rb
Currently just UPHOLD_AUTHORIZATION_ENDPOINT.
Fix #145
> Sanity check config vars

- app/views/publishers/verification_dns_record.html.slim
- config/locales/en.yml
Brave Bounty => Brave Payments
support+publishers@brave.com => support+publishers@basicattentiontoken.org
> Update wording and email address

- test/controllers/publishers_controller_test.rb
This PR just fixes the tests to align with the changes made to the dashboard in #152.
Further work is needed to smooth out the functionality and appearance of the dashboard.
> Fix tests to align with dashboard changes in 152

- app/helpers/publishers_helper.rb
- app/services/publisher_balance_getter.rb
- app/services/publisher_wallet_setter.rb
- app/views/publishers/home.html.slim
- lib/eyeshade/balance.rb
- test/services/publisher_balance_getter_test.rb
- test/unit/balance_test.rb
- Adds support for the new `/v2/publishers/#{publisher.brave_publisher_id}/balance` endpoint
- Adds a new Eyeshade::Balance class to handle the new response format
- Updates the dashboard to use the new formatted balance.
- Updates the wallet setter endpoint
Fixes #155
> Balance display BAT and USD

- app/services/publisher_wallet_setter.rb
- test/jobs/upload_uphold_access_parameters_job_test.rb
for bat mercury, the `PUT /.../wallet` operation is used to transmit access information.
> use /v2 endpoint for putting uphold parameters

- app/views/publishers/home.html.slim
The statement button is broken, so we'll disable this temporarily until #74 is resolved.
cc @alexwykoff @mrose17 @bsclifton
> REVERT ME: Disable Publishers Statement

- Gemfile.lock
see also https://github.com/sinatra/sinatra/pull/1171
cc @diracdeltas
> Upgrade rack-protection to 2.0.0

- app/controllers/application_controller.rb
Don't merge me unless you know what you're doing!
cc @evq @mrose17
> redirect all requests using TARGET_APP_DOMAIN

- app/helpers/publishers_helper.rb
- app/models/publisher.rb
- app/services/publisher_legacy_balance_getter.rb
- app/views/publishers/home.html.slim
- app/views/publishers/verification_done.html.slim
- config/locales/en.yml
> FIXME later: Add publisher legacy btc balance

- app/helpers/publishers_helper.rb
- app/services/publisher_legacy_balance_getter.rb
- config/secrets.yml
> Fix legacy balance getter (add legacy eyeshade config)

- app/services/publisher_legacy_balance_getter.rb
- config/secrets.yml
don't show anything in this case
cc @mrose17
> Legacy balance without api

- lib/error_handler.rb
> Add Publisher sentry context to ErrorHandler

- app/assets/stylesheets/shared/spinner.scss
- app/views/publishers/verification_background.html.slim
- config/locales/en.yml
- Slows the spinner
- Places it on the verifying page
- Rewords the verifying page
> Verify wording spinner

- app/assets/stylesheets/variables/fonts.scss
Use the font_url helper to fixes broken font asset location
> fonts use font_url helper

- app/views/publishers/home.html.slim
> Fix contact editing issues when phone number is not present

- app/controllers/publishers_controller.rb
> Redirect when verification completes

- app/assets/stylesheets/application/publishers.sass
- app/assets/stylesheets/application/static.sass
- app/views/publishers/home.html.slim
- app/views/static/index.html.slim
- config/locales/en.yml
> Add terms of service links to staging

- config/initializers/rack-attack.rb
Prevent ip addresses from the API_IP_WHITELIST from being throttled
> safelist api_ip_whitelist in Rack::Attack

- app/helpers/publishers_helper.rb
- app/views/publishers/home.html.slim
- config/secrets.yml
- docs/publishers-secrets.example.sh
Fixes #209 
I added the environment variable (UPHOLD_DASHBOARD_URL) on heroku staging, but this will need to be done on production.
> Adds configuration for UPHOLD_DASHBOARD_URL

- app/views/publishers/home.html.slim
- app/views/static/index.html.slim
Added analytics actions for landing page and dashboard
> updating analytics to include more landing and dashboard actions

- db/migrate/20171025114507_change_show_verification_status_null_for_publishers.rb
- db/schema.rb
> remove nulls for show_verification_status

- app/serializers/publisher_serializer.rb
Resolves #182 
```js
// GET /api/publishers/pfefferle.co
[
{
"id": "37fd49cf-cf5b-4fd8-83e9-c79cb772a0e7",
"email": "kevin@pfefferle.co",
"name": "Kevin Pfefferle",
"phone": "",
"phone_normalized": null,
"verified": true,
"verification_method": "dns_record",
"verification_token": "fd1048396dc60b30285e5b618a0e05c64a801aff8579b13ccfb34df6ed045595",
"show_verification_status": false,
"created_at": "2017-11-06T14:33:17.730-08:00",
"updated_at": "2017-11-06T14:54:39.182-08:00",
"last_sign_in_at": "2017-11-06T14:41:08.891-08:00"
}
]
```
Test Plan:
Tests
Security:
> Add show_verification_status and verification_method to publishers API endpoint

- app/services/publisher_wallet_setter.rb
- test/fixtures/publishers.yml
- test/services/publisher_wallet_getter_test.rb
- test/services/publisher_wallet_setter_test.rb
> Add tests for wallet setter/getter services

- app/controllers/publishers/omniauth_callbacks_controller.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
> Minor updates to PR #252

- app/services/publisher_host_inspector.rb
- test/services/publisher_host_inspector_test.rb
Resolves #204 
Test Plan:
Tests
Security:
> Update HTTPS verification to check WWW subdomain

- app/assets/javascripts/application.js
- app/assets/stylesheets/application/publishers.sass
- app/assets/stylesheets/shared/modal.sass
- app/views/publishers/home.html.slim
- vendor/assets/javascripts/classie.js
Addresses changes to the verification dialog requested by @jenn-rhim:
* Hides the blurred edges of the overlay using a scale effect
* Uses `setTimeout` to ensure that easing transitions are used to display the dialog
Resolves #262 
Test Plan:
Tests
Security:
> Improve display of verification dialog

- app/assets/stylesheets/application/publishers.sass
- app/assets/stylesheets/shared/modal.sass
- app/views/publishers/home.html.slim
Fixes #271
Test Plan:
Tests
Security:
> Use new `md` class prefix to avoid conflict with bootstrap modals

- app/models/publisher_statement.rb
- app/models/youtube_channel.rb
Resolves #279
@ayumi - please review
Test Plan:
Tests
Security:
> Add paper_trail to PublisherStatement and YoutubeChannel models

- config/locales/en.yml
> Shortened text on call to action button for email verification.

- Gemfile.lock
> Update rubocop, and dependent gems

- Procfile
This might fix #289, but I'm not sure how exactly to test it other than pushing to staging and looking at the logs
Test Plan:
Tests
Security:
> add heroku release step to migrate the database

- app/controllers/publishers_controller.rb
- config/locales/en.yml
Fixes #302
Test Plan:
Tests
Security:
> remove flash message after logout

- README.md
> README: Add note about installing chromium

- config/locales/en.yml
Resolves #480 
Test Plan:
Tests
Security:
> update install wordpress plugin link to use brave-payments-verification

- config/locales/en.yml
Resolves #495 
Test Plan:
Tests
Security:
> Update install wordpress plugin note to use brave-payments-verification

- app/assets/stylesheets/application/publishers.sass
- app/assets/stylesheets/shared/error-group.sass
- app/assets/stylesheets/shared/sub-panel.sass
- app/javascript/u2f/authenticationPage.js
- app/javascript/u2f/registrationPage.js
- app/javascript/u2f/shared.js
- app/models/publisher.rb
- app/services/publisher_unverified_calculator.rb
- app/views/application/_icon_circled_x.html
- app/views/publishers/create_auth_token.html.slim
- app/views/publishers/new_auth_token.html.slim
- app/views/totp_registrations/new.html.slim
- app/views/two_factor_authentications/_u2f.html.slim
- app/views/two_factor_authentications/index.html.slim
- app/views/u2f_registrations/new.html.slim
- config/locales/en.yml
- lib/tasks/publisher_inventory.rake
- test/services/publisher_unverified_calculator_test.rb
This consists of a merge commit bringing all commits in `staging` into the `staging2` branch.
`publisher_unverified_calculator.rb` and its test required significant refactoring to align with the new models. This work has been discussed with @nvonpentz. The gist is that instead of try to find duplication verified records of an unverified channel (tricky and probably not handling a common case) we instead simply put a max age on the channels being considered for win back.
> Merge `staging` into `staging2`

- lib/tasks/data_sanitizer.rake
> add data sanitizer task

- config/environments/staging.rb
this does go against #326 
it is to help testing in staging, with verbose logged emails
> staging log level to :debug

- lib/error_handler.rb
Fixes #553
Test Plan:
Tests
Security:
> Send email instead of brave_publisher_id to Sentry

- Gemfile
- Gemfile.lock
Fixes #555
Test Plan:
Tests
Security:
> Update nokogiri to 1.8.2

- config/secrets.yml
- lib/publishers/fetch.rb
Fix #516
auditors: @lgebhardt 
Test Plan:
Tests
Security:
> Reduce host inspector timeout to avoid timeouts

- app/assets/stylesheets/_bootstrap-custom.scss
- app/assets/stylesheets/_colors.scss
- app/assets/stylesheets/components/btn.scss
- app/assets/stylesheets/components/modal.scss
- app/assets/stylesheets/pages/totp_registrations.scss
- app/assets/stylesheets/pages/two_factor_registrations.scss
- app/assets/stylesheets/theme/columns.scss
- app/assets/stylesheets/theme/main-content.scss
- app/assets/stylesheets/theme/nav.scss
- app/assets/stylesheets/theme/panels.scss
- app/assets/stylesheets/theme/text.scss
- app/controllers/totp_registrations_controller.rb
- app/views/application/_nav.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/totp_registrations.html.slim
- app/views/layouts/two_factor_registrations.html.slim
- app/views/layouts/u2f_registrations.html.slim
- app/views/publishers/create_done.html.slim
- app/views/totp_registrations/new.html.slim
- app/views/two_factor_authentications/_totp.html.slim
- app/views/two_factor_authentications/_u2f.html.slim
- app/views/two_factor_registrations/index.html.slim
- app/views/two_factor_registrations/prompt.html.slim
- app/views/u2f_registrations/_u2f_registration.html.slim
- app/views/u2f_registrations/new.html.slim
- config/locales/en.yml
> Update 2FA Registrations to Bootstrap 4

- config/locales/en.yml
As per @jenn-rhim’s requests in https://github.com/brave-intl/publishers/issues/577
Closes #577
Here's the updated appearance:
Test Plan:
Tests
Security:
> Adjust text in channel taken modal

- app/controllers/publishers_controller.rb
- app/javascript/packs/application.js
- app/views/publishers/sign_up.html.slim
- config/locales/en.yml
- test/features/publishers_home_test.rb
Closes https://github.com/brave-intl/publishers/issues/508
**Before**
**After**
/cc @ayumi @jenn-rhim
> Prompt the user to create an account if they have a bad email on login

- app/mailers/announcement_mailer.rb
- app/views/announcement_mailer/multi_chan.html.slim
- config/locales/en.yml
- config/sidekiq.yml
- lib/tasks/mail/announce_multi_chan.rake
Fix #570
Test Plan:
Tests
Security:
> Email: add multi-chan announcement

- app/mailers/announcement_mailer.rb
- app/views/announcement_mailer/multi_chan.html.slim
- config/locales/en.yml
- config/sidekiq.yml
- lib/tasks/mail/announce_multi_chan.rake
> Release 2018-02-01 multi-chan announcement

- app/jobs/clean_abandoned_site_channels_job.rb
- app/models/site_channel_details.rb
- config/sidekiq.yml
- test/controllers/api/owners_controller_test.rb
- test/fixtures/channels.yml
- test/fixtures/publishers.yml
- test/fixtures/site_channel_details.yml
- test/jobs/clean_abandoned_site_channels_job_test.rb
- test/models/site_channel_test.rb
Fixes #476
Test Plan:
Tests
Security:
> Add CleanAbandonedSiteChannelsJob

- app/views/publishers/home.html.slim
- app/views/publishers/new_auth_token.html.slim
- app/views/site_channels/verification_dns_record.html.slim
- app/views/totp_registrations/new.html.slim
- app/views/two_factor_registrations/index.html.slim
- app/views/u2f_registrations/new.html.slim
- config/locales/en.yml
Fixes #612
Test Plan:
Tests
Security:
> Cleans up some translation string issues

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/publishers/omniauth_callbacks_controller.rb
- app/models/channel.rb
- app/models/twitch_channel_details.rb
- app/models/youtube_channel_details.rb
- app/services/publisher_channel_setter.rb
- app/views/publishers/choose_new_channel_type.html.slim
- config/initializers/devise.rb
- config/initializers/inflections.rb
- config/secrets.yml
- db/migrate/20180212233004_create_twitch_channel_details.rb
- db/schema.rb
- test/controllers/api/owners_controller_test.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
- test/fixtures/channels.yml
- test/fixtures/publishers.yml
- test/fixtures/twitch_channel_details.yml
This lands Twitch support behind a param. To run through the UI follow the instructions added to `README.md` then visit:
`/publishers/choose_new_channel_type?twitch=1`
And choose the Twitch option to move forward. This is a work-in-progress UI (not final UI, no translations), but it should be safe to land in staging.
> Twitch Support

- test/tasks/launch_promo_test.rb
Fix #641
auditors: @nvonpentz 
Test Plan:
Tests
Security:
> Test: Fix flappy launch_promo_test

- app/assets/stylesheets/mailer.scss
- app/helpers/promos_helper.rb
- app/views/promo_mailer/new_channel_registered_2018q1.html.slim
- app/views/promo_mailer/promo_activated_2018q1_verified.html.slim
- app/views/promo_registrations/_activated_verified.html.slim
- app/views/promo_registrations/_active.html.slim
- app/views/publishers/home.html.slim
- db/migrate/20180222234205_add_multi_column_index_to_promo_registration.rb
- db/schema.rb
- test/controllers/promo_registrations_controller_test.rb
- test/mailers/promo_mailer_test.rb
Resolves #631 (add DB constraint for referral code, promo id)
Resolves #645 (use https for underlying links in promo emails)
Resolves #642 (supply download links to promo assets in promo emails) cc @jenn-rhim 
Test Plan:
Tests
Security:
> Referral promo fixes

- app/views/layouts/publishers.html.slim
Fixes #656
/cc @ayumi @nvonpentz 
Test Plan:
Tests
Security:
> Ensure Bootstrap4 styles are applied to create action

- app/models/channel.rb
Resolves #672 
* Add case for Channel#channel_id for TwitchChannelDetails
Test Plan:
Tests
Security:
> Add missing piece for twitch referral promo support

- app/javascript/publishers/home.js
- app/views/application/_nav.html.slim
Update the username in the top nav upon updating user via the edit contact form at `/publishers/home`.
Tests
Security:
> Update username in topnav

- Gemfile.lock
Fix #689
Test Plan:
Tests
Security:
> Update gems: rack, rack-protection

- app/views/publishers/_choose_channel_type.html.slim
Make Twitch available to all users on the dashboard.
> Drop the opt-in query param for Twitch

- test/controllers/publishers/omniauth_callbacks_controller_test.rb
Fix #693
Test Plan:
Tests
Security:
> Test: Fix omniauth_callbacks_controller

- app/assets/stylesheets/legacy/application/publishers.sass
- app/helpers/promos_helper.rb
- app/helpers/publishers_helper.rb
- app/services/publisher_wallet_getter.rb
- app/views/promo_mailer/new_channel_registered_2018q1.html.slim
- app/views/promo_mailer/promo_activated_2018q1_verified.html.slim
- app/views/promo_registrations/_activated_verified.html.slim
- app/views/promo_registrations/_active.html.slim
- app/views/publishers/_choose_channel_type.html.slim
- app/views/publishers/home.html.slim
- config/locales/en.yml
- config/secrets.yml
- lib/eyeshade/wallet.rb
- test/controllers/promo_registrations_controller_test.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
- test/helpers/publishers_helper_test.rb
- test/mailers/promo_mailer_test.rb
- test/models/publisher_test.rb
- test/services/publisher_wallet_getter_test.rb
- test/unit/wallet_test.rb
Show pending BAT balances on a per channel basis.
> Release 2018-03-02

- app/javascript/publishers/home.js
Fix #664
Test Plan:
Tests
Security:
> Add change email error message

- app/assets/stylesheets/_fonts.scss
Resolves #707 
Test Plan:
I was unable to reproduce this locally.  When this is merged to staging I'll poke around and confirm it is fixed.
Tests
Security:
> Fix muli font path

- app/javascript/publishers/home.js
- app/javascript/userMenu.js
Fixes #648
Test Plan:
Tests
Security:
> Close user menu when page is clicked

- app/jobs/sync_publisher_statement_job.rb
Resolves #747 
Test Plan:
Tests
Security:
> Correct sentry-raven call in SyncPublisherStatementJob

- app/assets/stylesheets/legacy/application/publishers.sass
- app/assets/stylesheets/pages/site-channels.scss
- app/assets/stylesheets/theme/panels.scss
- app/controllers/publishers_controller.rb
- app/javascript/publishers/home.js
- app/jobs/sync_publisher_statement_job.rb
- app/models/channel.rb
- app/views/layouts/publishers.html.slim
- app/views/publishers/create_auth_token.html.slim
- app/views/publishers/emailed_auth_token.html.slim
- app/views/publishers/home.html.slim
- app/views/site_channels/verification_wordpress.html.slim
- config/locales/en.yml
- config/routes.rb
- test/controllers/publishers_controller_test.rb
- test/controllers/site_channels_controller_test.rb
- test/features/log_in_test.rb
- test/features/sign_up_test.rb
> Release 2018-04-02

- app/jobs/enqueue_site_channel_verifications.rb
- config/secrets.yml
Resolves #752 
Open to other name suggestions!
Test Plan:
Tests
Security:
> Add max_site_age envar

- app/services/publisher_notifier.rb
- config/secrets.yml
> Release 2018-04-10 (2)

- config/secrets.yml
> Send notifications in test environment

- config/secrets.yml
> Release 2018-04-10 (3)

- config/locales/en.yml
> Minor translation update for promo panel

- app/assets/stylesheets/legacy/application/publishers.sass
- app/helpers/promos_helper.rb
- app/helpers/publishers_helper.rb
- app/views/publishers/home.html.slim
- config/locales/en.yml
- test/helpers/promos_helper_test.rb
> Release 2018-04-11

- app/controllers/publishers_controller.rb
- app/views/publishers/emailed_auth_token.html.slim
Resolves #755 
Test Plan:
Tests
Security:
> Rate limit attempts to resend emails 

- Gemfile
- README.md
- app/controllers/publishers_controller.rb
- app/views/publishers/emailed_auth_token.html.slim
- config/environments/development.rb
- config/initializers/rack-attack.rb
- config/locales/en.yml
- docs/publishers-secrets.example.sh
Fixes issue where sometimes the reCAPTCHA is not shown and user instead sees 🎷
Supports rate limiting and reCAPTCHA in staging and development environments
Test Plan:
Tests
Security:
> Release 2018-04-25

- config/newrelic.yml
A part of https://github.com/brave-intl/publishers/issues/820
Test Plan:
Tests
Security:
> Include newrelic for staging environment

- config/newrelic.yml
> Fixed a misspelling in the newrelic initializer

- config/newrelic.yml
> Enable monitoring mode

- config/newrelic.yml
> Disable possibly breaking settings

- app/jobs/clean_abandoned_site_channels_job.rb
- app/services/promo_channel_owner_updater.rb
- app/services/promo_registrar.rb
- app/services/promo_registration_getter.rb
- app/services/publisher_promo_stats_fetcher.rb
Resolves #828 
Test Plan:
Tests
Security:
> Remove redundant sentry logs

- README.md
- config/secrets.yml
Resolves #836 
Test Plan:
Tests
Security:
> Remove FIXIE_URL

- app/controllers/api/channels_controller.rb
- app/helpers/channels_helper.rb
- config/routes.rb
- test/controllers/api/channels_controller_test.rb
> Feature: GET API for channel's verification status

- app/controllers/api/channels_controller.rb
> Modified response API to match Eyeshade

- .github/PULL_REQUEST_TEMPLATE.md
Resolves #873 
cc @alexwykoff 
Test Plan:
Tests
Security:
> Update pull request template require piwik/matomo integration

- app/services/publisher_statement_syncer.rb
- test/services/publisher_statement_syncer_test.rb
> Turn off statement email notifications

- app/jobs/sync_publisher_statement_job.rb
- app/services/publisher_statement_syncer.rb
- config/secrets.yml
- test/services/publisher_statement_syncer_test.rb
> Release 2018-05-21

- .github/PULL_REQUEST_TEMPLATE.md
- Gemfile
- Gemfile.lock
- config/brakeman.ignore
Resolves #897 
Use `brakeman -I` to ignore new vulnerabilities.
* Update config/brakeman.ignore
* Update .github/PULL_REQUEST_TEMPLATE.mde
Test Plan:
Tests
Security:
> Add brakeman to project

- app/controllers/api/base_controller.rb
Test Plan:
Tests
Security:
fixes brave-intl/internal#48
> Remove fastly ip. Closes #900

- Gemfile
- Gemfile.lock
- app/controllers/publishers_controller.rb
- config/initializers/session_store.rb
- db/migrate/20180521195417_add_sessions_table.rb
- db/schema.rb
Replaces the cookie based session store with an ActiveRecord based session store.
Fixes #893
Test Plan:
Tests
Security:
> ActiveRecord session store

- config/locales/en.yml
> Updated payout date to June 8, 2018. Closes #923

- app/helpers/publishers_helper.rb
Fixes #927
/cc @yachtcaptain23 
Test Plan:
Tests
Security:
> Remove unused, duplicate helper function

- config/locales/en.yml
> Fix settlement date. Closes #937

- db/migrate/20180509181712_add_kind_to_publishers.rb
- db/migrate/20180509181712_add_role_to_publishers.rb
- db/schema.rb
and possibly migrate later.
Fixes #839.
Test Plan:
Tests
Security:
> Migration to track the role of Users. Currently make use of Publishers

- Gemfile
- Gemfile.lock
> Update sinatra to 2.0.2. Closes #943

- lib/tasks/sendgrid/refresh.rake
- test/cassettes/test_can_add_multiple_contacts_to_a_list.yml
- test/cassettes/test_upserts_all_email_verified_publishers_to_SendGrid_with_paginated_requests.yml
- test/tasks/send_grid_refresh_test.rb
- test/unit/send_grid_helper_test.rb
Reworks some tests that use vcr to be less sensitive to new fixtures.
Test Plan:
Tests
Security:
> Rework vcr tests

- app/views/promo_registrations/_activate.html.slim
- app/views/publishers/_choose_channel_type.html.slim
- app/views/publishers/home.html.slim
- app/views/publishers/new_auth_token.html.slim
- app/views/site_channels/verification_dns_record.html.slim
- app/views/site_channels/verification_github.html.slim
- app/views/site_channels/verification_public_file.html.slim
- app/views/site_channels/verification_support_queue.html.slim
- app/views/site_channels/verification_wordpress.html.slim
- app/views/static/index.html.slim
- app/views/totp_registrations/new.html.slim
- app/views/u2f_registrations/new.html.slim
Fixes #862
Test Plan:
Tests
Security:
> Add more analytics to our interactions

- app/controllers/application_controller.rb
- app/models/ability.rb
- base.yml
- config/secrets.yml
- test/controllers/admin/publishers_controller_test.rb
- test/fixtures/publishers.yml
- test/fixtures/totp_registrations.yml
Resolves #961 
- [] Tagged reviewers.
Test Plan:
Tests
Security:
> Enforce 2fa and IP whitelisting for admins

- app/controllers/admin/publishers_controller.rb
- app/views/admin/publishers/index.html.slim
- test/controllers/admin/publishers_controller_test.rb
> Search functionality for name and email

- app/models/publisher.rb
- app/models/publisher_notes.rb
- db/migrate/20180613170836_create_publisher_notes.rb
- db/schema.rb
Refs #975 (Admin dashboard integration still needed)
Refs #959 
Test Plan:
Tests
Security:
> Add PublisherNotes table & model

- app/services/log_exception.rb
Closes #909
Test Plan:
Tests
Security:
> Feature: Logging service into NewRelic and Sentry

- app/controllers/api/public/channels_controller.rb
- test/controllers/api/public/channels_controller_test.rb
> Change timestamp result to string. Fixes #979

- app/assets/stylesheets/admin/style.scss
- app/controllers/admin_controller.rb
- app/controllers/publishers_controller.rb
- app/helpers/admins_helper.rb
- app/helpers/publishers_helper.rb
- app/javascript/packs/admin.js
- app/javascript/publishers/statements.js
- app/jobs/sync_publisher_statement_job.rb
- app/models/publisher_statement.rb
- app/services/publisher_statement_generator.rb
- app/services/publisher_statement_syncer.rb
- app/views/admin/publishers/show.html.slim
- app/views/admin/shared/_header.html.slim
- app/views/layouts/admin.html.slim
- app/views/publishers/statements.html.slim
- config/routes.rb
- db/migrate/20180613004804_add_created_by_admin_to_publisher_statements.rb
- db/schema.rb
- test/controllers/admin/publishers_controller_test.rb
- test/jobs/sync_publisher_statement_job_test.rb
- test/models/publisher_statement_test.rb
- test/services/publisher_statement_syncer_test.rb
Resolves #959 
Test Plan:
Tests
Security:
> [WIP] Add #show per publisher on admin dashboard

- app/controllers/api/base_controller.rb
- app/models/ability.rb
Resolves #986 
Test Plan:
Tests
Security:
> Only allow blank whitelists in development

- app/assets/stylesheets/admin/style.scss
- app/controllers/admin_controller.rb
- app/controllers/publishers_controller.rb
- app/models/publisher.rb
- app/models/publisher_note.rb
- app/views/admin/publishers/show.html.slim
- config/routes.rb
- db/migrate/20180614215946_add_created_by_to_publisher_notes.rb
- db/schema.rb
- test/models/publisher_note_test.rb
Resolves #975 
Test Plan:
Tests
Security:
> Allow admins to create notes for a publisher

- app/models/json_builders/identity_json_builder.rb
- test/controllers/api/public/channels_controller_test.rb
> Apply exclusions to subdomains. Closes #995

- config/locales/en.yml
Closes #1020
Test Plan:
Tests
Security:
> Updated wording on publisher mailing

- app/controllers/application_controller.rb
Prevent caching of all responses via the `Cache-Control` header. By including `no-store`, browsers should make fresh requests even when navigating through the history (i.e. via the back button).
NOTE: This should be confirmed on staging on all supported browsers to verify in our production environment.
Fixes #769
Test Plan:
Tests
Security:
> Prevent caching

- app/javascript/publishers/home.js
- app/views/publishers/home.html.slim
- test/features/publishers_home_test.rb
Reverts brave-intl/publishers#1049
> Revert "Prevent default currency modal from appearing"

- app/views/faqs/_faqs.slim
Fixes https://github.com/brave-intl/publishers/issues/1056
Test Plan:
Tests
Security:
> Support redcarpet markdowns

- Gemfile
- Gemfile.lock
Resolves #1060 
Test Plan:
Tests
Security:
> Bump nokogiri gem to latest version

- config/initializers/rack-attack.rb
Resolves #1062 
Test Plan:
Tests
Security:
> Update rate limited path with new version number

- config/initializers/rack-attack.rb
> Release 2018-07-16

- app/controllers/api/stats_controller.rb
- config/routes.rb
- test/controllers/api/stats_controller_test.rb
Closes #1065
Test Plan:
Tests
Security:
> Verified and non-verified publishers created_at per day

- app/javascript/userMenu.js
Resolves #1054 
Test Plan:
Tests
Security:
> Allow firefox users to access user menu

- Gemfile
- Gemfile.lock
- app/controllers/api/stats_controller.rb
- app/jobs/sync_channel_stats_job.rb
- app/services/channel_stats_services/twitch_channel_stats_service.rb
- app/services/channel_stats_services/youtube_channel_stats_service.rb
- base.yml
- config/initializers/yt.rb
- config/routes.rb
- config/secrets.yml
- config/sidekiq.yml
- db/migrate/20180719173113_add_stats_to_channel_details.rb
- db/schema.rb
- test/controllers/api/stats_controller_test.rb
- test/fixtures/twitch_channel_details.yml
- test/fixtures/youtube_channel_details.yml
- test/services/channel_stats_services/twitch_channel_stats_service_test.rb
We will need to register a youtube data api key.
Test Plan:
Tests
Security:
> Collect stats on youtube and twitch channels & expose via the stats API

- app/controllers/api/stats_controller.rb
- app/models/publisher.rb
- config/routes.rb
- test/controllers/api/stats_controller_test.rb
> Stats for no-script users

- README.md
- app/services/publisher_balance_getter.rb
- app/services/publisher_wallet_getter.rb
- db/schema.rb
- docker-compose.yml
- test/controllers/publishers_controller_test.rb
- test/features/publishers_home_test.rb
- test/helpers/publishers_helper_test.rb
- test/jobs/create_uphold_cards_job_test.rb
- test/models/publisher_test.rb
- test/services/publisher_balance_getter_test.rb
- test/services/publisher_wallet_getter_test.rb
Resolves #1095 
Test Plan:
Tests
Security:
> Use new eyeshade balance endpoint for wallet information 

- Gemfile
- Gemfile.lock
> Force upgrade rubyzip to 1.2.2. Closes #1120

- .travis.yml
> Fix travis time zone settings. Closes #1138

- app/services/publisher_wallet_getter.rb
- test/services/publisher_wallet_getter_test.rb
Resolves #1130 
Test Plan:
Tests
Security:
> Set overall balance by summing over all accounts (channels and owner)

- app/services/publisher_balance_fee_calculator.rb
- config/secrets.yml
- test/jobs/generate_payout_report_job_test.rb
Resolves #1137 
Test Plan:
Tests
Security:
> Return the balance minus fee in PublisherFeeCalculator

- app/services/publisher_balance_getter.rb
- test/controllers/admin/payout_reports_controller_test.rb
- test/features/publishers_home_test.rb
- test/jobs/create_uphold_cards_job_test.rb
- test/jobs/generate_payout_report_job_test.rb
- test/models/publisher_test.rb
- test/services/publisher_balance_getter_test.rb
- test/services/publisher_wallet_getter_test.rb
> Update PublisherBalanceGetter request url

- app/views/admin/publishers/show.html.slim
Resolves #1150 
Test Plan:
Tests
Security:
> Accurately display balance and converted balance on admin page

- app/jobs/generate_payout_report_job.rb
Resolves #1144 
Test Plan:
Tests
Security:
> Log progress every 500 publishers in GeneratePayoutReportJob

- Gemfile
- Gemfile.lock
- app/controllers/admin/dashboard_controller.rb
- app/javascript/admin/dashboard/index.js
- app/javascript/packs/admin.js
- app/views/admin/dashboard/index.html.slim
- config/initializers/piwik.rb
- config/secrets.yml
- package.json
- yarn.lock
This reverts commit ad0793537fa0f6c71a715395474badad7dfe9e13.
Test Plan:
Tests
Security:
> Revert "Revert "Feature/piwik api""

- app/controllers/admin/dashboard_controller.rb
- app/javascript/admin/dashboard/index.js
- app/views/admin/dashboard/index.html.slim
> Admin dashboard data

- app/controllers/admin/dashboard_controller.rb
- app/javascript/admin/dashboard/index.js
- app/services/publisher_wallet_getter.rb
- app/views/admin/dashboard/index.html.slim
- lib/eyeshade/balance.rb
- lib/eyeshade/wallet.rb
- test/controllers/publishers_controller_test.rb
- test/helpers/publishers_helper_test.rb
> Release 2018-09-27

- app/controllers/admin/payout_reports_controller.rb
- app/services/publisher_wallet_getter.rb
- lib/eyeshade/balance.rb
- lib/eyeshade/wallet.rb
- test/controllers/publishers_controller_test.rb
- test/helpers/publishers_helper_test.rb
> Release 2018-09-28

- Aptfile
> Correct Aptfile package names

- Aptfile
> Correct Aptfile package names again

- bin/wkhtmltopdf-with-xvfb.sh
> Remove the script that would have executed wkhtmltopdf

- app/javascript/packs/banner_editor.jsx
As per [this stack answer](https://stackoverflow.com/a/23123261)
> set image header before source

- test/controllers/publishers/site_banners_controller_test.rb
> Reset env variable before & after each test

- test/controllers/publishers/site_banners_controller_test.rb
> Release 2018-10-18 2

- app/controllers/publishers/site_banners_controller.rb
- config/storage.yml
- test/controllers/publishers/site_banners_controller_test.rb
> Release 2018-10-18 3

- app/controllers/publishers/site_banners_controller.rb
- app/models/site_banner.rb
- test/models/site_banner_test.rb
> Sanitize HTML tags

- app/models/channel.rb
> Fix misspelling for Rails.logger

- app/javascript/packs/banner_editor.jsx
Quick fix for a loading spinner bug, need to set loading to `false` first.
> Loading Spinner hotfix

- app/helpers/promos_helper.rb
- test/helpers/promos_helper_test.rb
> Default to 0 when aggregate promo stats are nil

- app/helpers/promos_helper.rb
- test/helpers/promos_helper_test.rb
> Release 2018-10-26 (2)

- app/views/publishers/home.html.slim
> Remove verified channel deletion from UI

- app/views/publishers/home.html.slim
> Release 2018-10-29

- config/locales/en.yml
> Fix channel transfer email typo

- lib/tasks/publisher_statements.rake
Closes #1275
Test Plan:
Tests
Security:
> Remove unused rake task

- app/controllers/publishers_controller.rb
- app/jobs/sync_publisher_promo_stats_job.rb
- test/jobs/sync_publisher_promo_stats_job_test.rb
> Pass publisher.id not publisher to SyncPublisherPromoStatsJob

- Gemfile.lock
> Update rack to 2.0.6. Closes #1318

- app/javascript/packs/banner_editor.jsx
- app/javascript/packs/style.jsx
- app/models/site_banner.rb
- test/models/site_banner_test.rb
Reverts brave-intl/publishers#1332
> Revert "Editable Tip Amounts"

- app/controllers/admin/stats/contributions_controller.rb
- app/controllers/admin/stats/referrals_controller.rb
- app/jobs/cache/eyeshade_stats_job.rb
- app/services/eyeshade/referral_totals.rb
- app/views/admin/shared/_sidebar.html.slim
- app/views/admin/stats/_top_eyeshade_wallets.html.slim
- app/views/admin/stats/contributions/index.html.slim
- app/views/admin/stats/referrals/index.html.slim
- config/routes.rb
> Show referral stats. Closes #1326

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/middlewares/http_header_middleware.rb
> Add HTTP security headers

- app/controllers/admin/unattached_promo_registrations_controller.rb
> Use PromoRegistration#unattached_only not #unattached

- app/controllers/admin/unattached_promo_registrations_controller.rb
> Release 2018-11-19 (hotfix)

- app/services/publisher_wallet_getter.rb
- app/views/admin/publishers/show.html.slim
> Display publisher Uphold authorization status from the Eyeshade wallet to admins

- app/controllers/admin/channels_controller.rb
- app/helpers/publishers_helper.rb
- app/models/channel.rb
- app/views/admin/channels/index.html.slim
- app/views/admin/publishers/show.html.slim
- app/views/admin/shared/_sidebar.html.slim
- config/routes.rb
- test/controllers/admin/channels_controller_test.rb
- test/models/channel_test.rb
> Create channels controller with search

- app/views/admin/publishers/show.html.slim
Closes #1386
Test Plan:
Tests
Security:
> Use updated referral logic from PromoHelper

- config/newrelic.yml
This is done per https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/sidekiq-instrumentation
Closes #1391
Test Plan:
Tests
Security:
> We want to understand the performance of our worker dynos in production.

- app/views/admin/publishers/show.html.slim
- config/newrelic.yml
> Release 2018-11-30

- app/controllers/api/v1/public/channels_controller.rb
- app/controllers/api/v1/public/publishers_controller.rb
- app/models/channel.rb
- app/models/publisher.rb
- app/views/admin/dashboard/index.html.slim
- config/routes.rb
- test/controllers/api/public/channels_controller_test.rb
- test/controllers/api/public/publishers_controller_test.rb
> Public API for verified channels and publisher counts. Closes #1413

- .gitignore
- Gemfile
- Gemfile.lock
- test/test_helper.rb
When you run `rails test` there will be a coverage report in `coverage/index.html`
We're currently at 76.19%
> Add test coverage reports

- .gitignore
- Gemfile
- Gemfile.lock
- test/test_helper.rb
* Add test coverage reports
* Add better errors
* Move better errors to dev mode
Test Plan:
Tests
Security:
> Release 2018-12-06 2

- Procfile
- app/jobs/cache_browser_channels_json_job.rb
- app/jobs/sync/channel_promo_registrations_stats_job.rb
- config/heavy_sidekiq.yml
- config/sidekiq.yml
> Use a separate sidekiq config for a dedicated process. Closes #1420

- app/views/admin/unattached_promo_registrations/index.html.slim
> Dates for Referral Promo UI should be in UTC. Closes #1425

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/admin/main.scss
> Include font-awesome for use in admin. Closes #1455

- app/services/publisher_transactions_getter.rb
- app/views/publishers/statement.html.slim
- test/services/publisher_transactions_getter_test.rb
Resolves #1466 
Test Plan:
Tests
Security:
> Change transaction[type] to transaction[transaction_type]

- .travis.yml
- app/assets/stylesheets/admin/_will_paginate.css
- app/assets/stylesheets/admin/main.scss
- app/assets/stylesheets/admin/style.scss
- app/controllers/admin/channels_controller.rb
- app/controllers/admin/publishers_controller.rb
- app/helpers/admin_helper.rb
- app/javascript/packs/admin.js
- app/models/channel.rb
- app/models/publisher.rb
- app/views/admin/channels/_default.html.slim
- app/views/admin/channels/_twitch.html.slim
- app/views/admin/channels/_website.html.slim
- app/views/admin/channels/_youtube.html.slim
- app/views/admin/channels/index.html.slim
- app/views/admin/shared/_sidebar.html.slim
- test/fixtures/twitch_channel_details.yml
- test/fixtures/youtube_channel_details.yml
- test/models/channel_test.rb
> Menu to split channels

- .travis.yml
- app/assets/stylesheets/admin/_will_paginate.css
- app/assets/stylesheets/admin/main.scss
- app/assets/stylesheets/admin/style.scss
- app/controllers/admin/channels_controller.rb
- app/controllers/admin/publishers_controller.rb
- app/controllers/publishers/site_banners_controller.rb
- app/helpers/admin_helper.rb
- app/javascript/packs/admin.js
- app/javascript/packs/banner_editor.jsx
- app/javascript/packs/banner_preview.jsx
- app/javascript/packs/style.jsx
- app/javascript/publishers/home.js
- app/models/channel.rb
- app/models/publisher.rb
- app/views/admin/channels/_default.html.slim
- app/views/admin/channels/_twitch.html.slim
- app/views/admin/channels/_website.html.slim
- app/views/admin/channels/_youtube.html.slim
- app/views/admin/channels/index.html.slim
- app/views/admin/shared/_sidebar.html.slim
- test/fixtures/twitch_channel_details.yml
- test/fixtures/youtube_channel_details.yml
- test/models/channel_test.rb
> Release 2018-12-20

- app/controllers/publishers/omniauth_callbacks_controller.rb
- app/models/channel.rb
- config/initializers/devise.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
> Disable the hidden twitter channel registration. Closes #1480

- package.json
- yarn.lock
> Bump webpack-dev-server to get yarn audit to pass

- app/javascript/packs/banner_editor.jsx
- app/models/site_banner.rb
We discovered the tipping server can't handle this. For the existing users we'll downgrade them to the next highest option
> Remove 500 BAT from Tipping option

- app/controllers/admin/payout_reports_controller.rb
- app/controllers/admin/publishers_controller.rb
- app/controllers/concerns/search.rb
- app/jobs/enqueue_publishers_for_payout_job.rb
- app/jobs/enqueue_publishers_for_payout_notification_job.rb
- app/jobs/include_publisher_in_payout_report_job.rb
- app/mailers/publisher_mailer.rb
- app/models/publisher.rb
- app/services/payout_report_publisher_includer.rb
- app/views/admin/payout_reports/index.html.slim
- app/views/admin/publishers/show.html.slim
- app/views/publisher_mailer/uphold_member_restricted.html.slim
- config/locales/en.yml
- config/routes.rb
- config/sidekiq.yml
- db/migrate/20190116001651_add_uphold_id_to_publisher.rb
- db/schema.rb
- lib/eyeshade/wallet.rb
- test/controllers/admin/payout_reports_controller_test.rb
- test/jobs/enqueue_publishers_for_payout_notification_job_test.rb
- test/services/payout_report_publisher_includer_test.rb
> Release 2019-01-16

- app/mailers/application_mailer.rb
As noted here: https://github.com/brave-intl/publishers/pull/1536#issuecomment-456906505
> chore: remove old code

- app/mailers/application_mailer.rb
Reverts brave-intl/publishers#1550
> Revert "chore: remove old code"

- app/controllers/api/v1/public/base_controller.rb
> Loosen cache on the public api. Closes #1568

- app/assets/stylesheets/pages/home.scss
- app/helpers/publishers_helper.rb
- app/javascript/publishers/home.js
- app/models/publisher.rb
- app/services/payout_report_publisher_includer.rb
- app/services/publisher_wallet_getter.rb
- app/views/admin/publishers/show.html.slim
- app/views/publishers/home.html.slim
- config/locales/en.yml
- lib/eyeshade/wallet.rb
- test/controllers/publishers_controller_test.rb
- test/helpers/publishers_helper_test.rb
- test/models/publisher_test.rb
- test/services/publisher_wallet_getter_test.rb
> Ask users to go to uphold.com to fully verify. Closes #1513

- app/models/json_builders/payout_report_json_builder.rb
> Fix payout report from being stopped if a channel was deleted

- app/views/static/index.html.slim
- app/views/two_factor_authentications/index.html.slim
- config/locales/en.yml
Closes #1560
Test Plan:
Tests
Security:
> Discovery links for channel transfer.

- app/models/promo_registration.rb
> Don't destroy the publisher if the promo registration is deleted

- README.md
- lib/docker/eyeshade_helper.rb
- lib/tasks/docker.rake
Resolves #1491 
Balances can now be added with
```
rake docker:add_contribution_balance_to_account['youtube#channel:UCOo92t8m-tWKgmw276q7mxw', 200] # Adds 200 BAT to youtube#channel:UCOo92t8m-tWKgmw276q7mxw
```
and
```
rake docker:add_referral_balance_to_account['publishers#uuid:967a9919-34f4-4ce6-af36-e3f592a6eab7', 400] # Adds 400 BAT to publishers#uuid:967a9919-34f4-4ce6-af36-e3f592a6eab7
```
Test Plan:
Tests
Security:
> Add instructions on how to add balances to accounts using docker

- app/views/admin/publishers/show.html.slim
Closes #1593
Test Plan:
Tests
Security:
> Show address and is_a_member? in admin

- app/services/publisher_balance_getter.rb
- test/controllers/admin/payout_reports_controller_test.rb
- test/controllers/publishers_controller_test.rb
- test/features/publishers_home_test.rb
- test/jobs/create_uphold_cards_job_test.rb
- test/models/publisher_test.rb
- test/services/payout_report_publisher_includer_test.rb
- test/services/publisher_balance_getter_test.rb
- test/services/publisher_wallet_getter_test.rb
Closes #1563
Test Plan:
Tests
Security:
> Include pending=true for account balances

- app/views/admin/publishers/index.html.slim
- app/views/admin/publishers/show.html.slim
> Fix display of users if they only have a pending email

- app/views/admin/publishers/show.html.slim
Resolves https://sentry.io/organizations/brave-software/issues/903231920/?project=221970&query=is%3Aunresolved&statsPeriod=14d&utc=true
Test Plan:
Tests
Security:
> Do not try to display report status for potential payments that don't exist

- app/controllers/admin/stats/top_balances_controller.rb
- app/services/eyeshade/top_balances.rb
- app/views/admin/stats/top_balances/index.html.slim
Closes #1625
Test Plan:
Tests
Security:
> Show top balances for top 1000

- app/views/publishers/home.html.slim
Error during rebasing caused this issue 😅
> Update payments path

- app/views/publishers/home.html.slim
- lib/docker/eyeshade_helper.rb
> Release 2019-02-28

- app/models/json_builders/channels_json_builder.rb
Fix to resolve this [Sentry Error](https://sentry.io/organizations/brave-software/issues/750563805/?project=225116&query=is%3Aunresolved+json&statsPeriod=14d&utc=false)
> Fix nil details error

- config/heavy_sidekiq.yml
- config/sidekiq.yml
[promo stats was removed here](https://github.com/brave-intl/publishers/pull/1637) but we didn't remove the scheduler config
> Remove dead config from scheduler

- app/controllers/admin/stats/top_balances_controller.rb
- app/views/admin/dashboard/index.html.slim
Couple of sentry issues that were found in staging, might as well address them as well
> Fix TypeError

- app/controllers/admin/publishers_controller.rb
Fix #1669 
Test Plan:
Tests
Security:
> Look for potential payments with no channel id when displaying payout report status for referrals

- db/migrate/20190222204716_remove_ip_tracking_from_publishers.rb
> Add type to allow reverse of 20190222204716

- app/models/publisher.rb
- app/views/internal_mailer/channel_verification_approval_required.html.slim
- db/migrate/20190222204716_remove_ip_tracking_from_publishers.rb
- db/schema.rb
- lib/tasks/data_sanitizer.rake
This reverts commit b363fac9b0d17aacaed2c3ac75ec2891b9cd1a74.
Test Plan:
Tests
Security:
> Revert "Remove IP Address from Publishers Table (#1639)"

- .travis.yml
- Gemfile
- Gemfile.lock
> Try caching yarn results

- app/assets/stylesheets/pages/home.scss
- app/javascript/publishers/home.js
- app/views/publishers/home.html.slim
- config/locales/en.yml
Resolves issue #1564 
The message will go away when the channel is older than 2 days 😄
> Add some information about verification time

- app/javascript/packs/referral_charts.jsx
> Don't use scientific notation. Add auto-skip on x-axis

- .travis.yml
> We might not need to precompile assets for travis builds

- app/controllers/publishers/site_banners_controller.rb
- app/javascript/packs/bannerEditor/FailureDialog.jsx
- app/javascript/packs/banner_editor.jsx
- config/locales/en.yml
Resolves #1610
I also ran Prettier on the banner_editor so the diff looks rough. 😅
> SiteBanner inform user's when upload failed

- app/javascript/packs/referral_charts.jsx
> Fix multiple charts getting overlaid

- .babelrc
> Fix babelrc to include plugin-proposal-class-properties

- Gemfile
- Gemfile.lock
> Upgrade devise to 4.6.1

- app/views/admin/publishers/show.html.slim
> Fix variable scope error on admin. Closes #1715

- app/services/promo/registrations_geo_stats_fetcher.rb
- app/services/publisher_balance_getter.rb
- app/services/publisher_transactions_getter.rb
> Ensure 503's don't crash the entire application

- app/controllers/admin/publishers/publisher_status_updates_controller.rb
- app/views/admin/publishers/index.html.slim
- app/views/admin/publishers/publisher_status_updates/index.html.slim
- app/views/admin/shared/_sidebar.html.slim
Closes #1645
Test Plan:
Tests
Security:
> Show the last note. Make the link to suspended publishers obvious

- config/locales/en.yml
> Adjust wording to not overpromise 48 hour response time. Closes #1737

- package.json
- yarn.lock
> Resolve js-yaml security warning during yarn audit.

- app/assets/stylesheets/static/static.scss
- app/views/static/index.html.slim
Fixes: https://github.com/brave-intl/publishers/issues/1748
Simplifying down styles to make the page responsively resize to be of better use on mobile
Video of responsiveness: https://d.pr/v/eiXouT
> responsive css styling

- test/models/partner_test.rb
Forgot to update the "In progress" status for the mocked Invoices
> Fix broken partner tests

- app/controllers/publishers_controller.rb
Closes #1627
Test Plan:
Tests
Security:
> Don't double auth the user.

- lib/eyeshade/wallet.rb
Was missing a require statement for the contribution balance
https://sentry.io/organizations/brave-software/issues/952700626/?project=221970&query=is%3Aunresolved&statsPeriod=14d&utc=false
> Add missing contribution_balance file

- app/controllers/admin/payout_reports_controller.rb
- app/helpers/publishers_helper.rb
- app/jobs/set_payout_in_progress_job.rb
- app/views/admin/payout_reports/index.html.slim
- app/views/publishers/home.html.slim
- config/locales/en.yml
- config/routes.rb
- config/sidekiq.yml
- test/controllers/admin/payout_reports_controller_test.rb
- test/helpers/publishers_helper_test.rb
- test/jobs/set_payout_in_progress_job_test.rb
Resolves #1594 
Test Plan:
Tests
Security:
> Add note on dashboard for when payout is in progress

- app/assets/stylesheets/static/static.scss
- app/views/layouts/application.html.slim
> Fix navbar for home page

- .github/PULL_REQUEST_TEMPLATE.md
* Cleaner more minimal pull request template.
* Simplicity encourages more usage and more descriptive prs.
* `How to Test` section encourages more thorough testing by removing guesswork.
1. Create a PR 
2. Look at the PR
> Update Pull Request Template 🏷 

- app/services/publisher_statement_getter.rb
1. Step one
2. Step two
3. Step three
> Fix loading of statements. Closes #1788

- app/controllers/admin/stats/top_balances_controller.rb
- app/services/eyeshade/top_balances.rb
- app/views/admin/stats/top_balances/_channels.html.slim
- app/views/admin/stats/top_balances/_owners.html.slim
- app/views/admin/stats/top_balances/_uphold_accounts.html.slim
- app/views/admin/stats/top_balances/index.html.slim
> Make top balances more usable

- config/locales/en.yml
- Include link to community tipping guidelines 
- More transparency for disgruntled publishers 
Might be best to hold off on merging until https://bravesoftware.slack.com/archives/C0EL8S7QX/p1554829340124900 is resolved, 
Perhaps an official statement would provide more clarity. 
1. From the admin dashboard `suspend` a publisher account
2. Log in as `suspended` publisher
> Update Suspended Disclaimer 🏷 

- app/controllers/publishers/omniauth_callbacks_controller.rb
- app/models/channel.rb
- config/initializers/devise.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
This reverts commit 6bf57c2e15bb69c702515a07ba3325e4528c2eaa.
1. Step one
2. Step two
3. Step three
> Revert "Disable the hidden twitter channel registration."

- app/services/promo/registrations_stats_fetcher.rb
- test/unit/send_grid_helper_test.rb
1. Step one
2. Step two
3. Step three
> Get rid of sendgrid test that fails on occasion

- config/initializers/rack-attack.rb
1. Step one
2. Step two
3. Step three
> Rate limit on IP for 2FA removal

- package.json
- yarn.lock
> Get rid of the frikin vulnerabiltiies

- app/services/payout_report_publisher_includer.rb
- db/migrate/20190411222856_add_channel_stats_to_potential_payment.rb
- db/schema.rb
- test/services/payout_report_publisher_includer_test.rb
> Add channel_stats to potential_payments

- app/services/payout_report_publisher_includer.rb
- config/locales/en.yml
- db/migrate/20190411222856_add_channel_stats_to_potential_payment.rb
- db/schema.rb
- package.json
- test/services/payout_report_publisher_includer_test.rb
- yarn.lock
1. Step one
2. Step two
3. Step three
> Release 2019-04-18

- Gemfile
- Gemfile.lock
1. Step one
2. Step two
3. Step three
> Upgrade to Nokogiri 1.10.3

- app/services/payout_report_publisher_includer.rb
- db/migrate/20190422195852_add_channel_type_to_potential_payments.rb
- db/schema.rb
- test/services/payout_report_publisher_includer_test.rb
1. Step one
2. Step two
3. Step three
> Save the channel type in the potential payment if it's a contribution payment

- app/controllers/admin/payout_reports_controller.rb
- app/services/payout_report_publisher_includer.rb
- app/views/admin/invoices/show.html.slim
- db/migrate/20190422195852_add_channel_type_to_potential_payments.rb
- db/schema.rb
- test/services/payout_report_publisher_includer_test.rb
1. Step one
2. Step two
3. Step three
> Release 2019-04-22

- app/controllers/admin/stats/top_balances_controller.rb
Closes #1849
1. Step one
2. Step two
3. Step three
> Only show verified channels for top balances

- app/models/json_builders/channels_json_builder.rb
weird complexity on how Rails handles polymorphic lookup.
1. Step one
2. Step two
3. Step three
> Big perf improvement. Still a massively ugly N+1 query due to

- app/views/admin/stats/top_youtube_channels/index.html.slim
1. Step one
2. Step two
3. Step three
> Fix sorting

- app/controllers/publishers_controller.rb
So we don't have downtime 
1. checkout branch
`git checkout c69a89f8d46efb671386a17f53c96134f8ba0534`
2. run the server create an account and link to uphold
3. connect uphold
4. checkout this branch
`git checkout migrate-live`
5. login, see that an uphold connection was created  🎉
> Add the ability to migrate live connections

- app/controllers/publishers_controller.rb
Fixes 500 when user was logged in during deployment
> Move uphold creation to home

- app/models/site_banner.rb
1. Step one
2. Step two
3. Step three
> Site Banner Fix 🏷 

- app/models/site_banner.rb
In response to https://bravesoftware.slack.com/archives/G2KN13Z8C/p1557962234053000
> Release 5/21

- app/views/publishers/_choose_channel_type.html.slim
- config/locales/en.yml
Opens up the feature which allows Publishers to create Twitter Channels
1. Set Twitter environment variables
2. Try to add a Twitter Channel
> Enable Twitter Channels 🏷 

- app/models/channel.rb
This is for our stats service :)
> Add twitter to the statistical totals

- app/models/channel.rb
new channels totals for stats service
> Create totals for new channels

- app/controllers/admin/publishers_controller.rb
- app/jobs/publisher_removal_job.rb
- app/models/channel.rb
- app/models/publisher.rb
- app/models/publisher_status_update.rb
- app/models/site_banner.rb
- app/views/admin/publishers/edit.html.slim
- app/views/publishers/_choose_channel_type.html.slim
- config/locales/en.yml
- test/jobs/publisher_removal_job_test.rb
- test/models/publisher_status_update_test.rb
- test/models/publisher_test.rb
1. Step one
2. Step two
3. Step three
> Release 2019-05-24

- app/jobs/cache_browser_channels_json_job.rb
- config/environments/production.rb
- config/environments/staging.rb
closes #1900
1. Deploy on staging
> Update Redis Config

- config/environments/production.rb
- config/environments/staging.rb
Increase write timeout for Redis
1. In production, of course.
> Increase write timeout for redis

- config/environments/production.rb
- config/environments/staging.rb
1. Step one
2. Step two
3. Step three
> Release 2019-05-29

- app/models/channel.rb
- app/services/site_channel_verifier.rb
* has emojis
1. Add channel to staging
2. Look at the slack channels
3. ???
4. Profit
> Notifciations for slack

- public/creators-landing/src/locale/en.js
- public/creators-landing/src/sections/main-section/index.js
- public/creators-landing/src/style/style.css
Fixes: https://github.com/brave-intl/publishers/issues/1903
> Login button

- app/javascript/views/admin/referrals/components/referralsChart/ReferralsChart.tsx
> Fix the referral charts :)

- app/jobs/delete_publisher_channel_job.rb
- app/jobs/publisher_removal_job.rb
- app/jobs/two_factor_authentication_removal_job.rb
- app/services/channels/approve_channel_transfer.rb
- app/services/channels/reject_channel_transfer.rb
- test/jobs/delete_publisher_channel_job_test.rb
Handles the exceptions
1. Register a channel for transfer
2. Mark it as verification_pending: true
3. Now try and transfer that
> Fix Channel Transfers

- app/jobs/two_factor_authentication_removal_job.rb
Removes a duplicate call to `PublisherWalletDisconnector` which was causing errors for some users
> 2FA Removal Patch 2 🏷 

- app/assets/stylesheets/admin/errors/whitelist.scss
- app/assets/stylesheets/admin/main.scss
- app/controllers/application_controller.rb
- app/views/admin/errors/_construction.svg.html
- app/views/admin/errors/whitelist.html.slim
- test/controllers/admin/publishers_controller_test.rb
* When the user is not on the whitelist the user gets an error screen
1. Update `app/models/ability.rb` to always `raise AdminNotOnIPWhitelistError`
2. See the error 🎉 
3. Revert the file
4. No more error
Closes #1720
> Fix 500 when user logs in without being on IP Whitelist

- app/models/potential_payment.rb
- app/models/site_channel_details.rb
- app/models/twitch_channel_details.rb
- app/models/twitter_channel_details.rb
- app/models/youtube_channel_details.rb
- lib/tasks/database_updates/remove_unused_versions.rake
> Don't papertrail things that shouldn't be paper trailed. Closes #1630

- app/controllers/admin/publishers/publisher_status_updates_controller.rb
- app/controllers/api/v1/publishers_controller.rb
- app/javascript/views/admin/components/userNavbar/components/TopNav/TopNavStyle.ts
- app/mailers/application_mailer.rb
- app/mailers/publisher_mailer.rb
- app/models/publisher.rb
- app/models/publisher_status_update.rb
- app/services/manual_payout_report_publisher_includer.rb
- app/services/payout_report_publisher_includer.rb
- app/views/admin/publishers/publisher_status_updates/index.html.slim
- app/views/publisher_mailer/email_user_on_hold.html.slim
- config/locales/en.yml
- config/secrets.yml
- test/mailers/previews/publisher_mailer_preview.rb
Creates a hold status for publishers
Set publisher to hold and trigger email to be sent
> Create hold status

- config/sidekiq.yml
1. Step one
2. Step two
3. Step three
> Disable zendesk from autorunning

- app/models/channel.rb
- app/models/publisher.rb
- app/services/publisher_statement_getter.rb
- test/models/publisher_test.rb
* Don't try to upload default currency if the address doesn't exist. Closes #1958
* Fix test for processing default currency for accounts without an address
1. Step one
2. Step two
3. Step three
> Release 2019-06-12

- .travis.yml
- app/mailers/publisher_mailer.rb
- app/views/publisher_mailer/update_to_tos.html.slim
- config/locales/en.yml
- lib/tasks/email_tos_update.rake
- test/mailers/previews/publisher_mailer_preview.rb
Creates a rake task to email out every single user to inform them about updated terms of service
`rake email:tos_update`
> Updated Terms of Service

- app/mailers/publisher_mailer.rb
- app/views/publisher_mailer/uphold_account_changed.html.slim
- config/locales/en.yml
- test/mailers/previews/publisher_mailer_preview.rb
- test/mailers/publisher_mailer_test.rb
While reviewing the text for emails that we send I found some that we no longer use.
> Remove unused mailers

- .travis.yml
- app/assets/stylesheets/pages/home.scss
- app/controllers/admin/publishers/publisher_status_updates_controller.rb
- app/helpers/admin/publishers_helper.rb
- app/javascript/views/admin/components/userNavbar/components/TopNav/TopNavStyle.ts
- app/jobs/delete_publisher_channel_job.rb
- app/jobs/include_publisher_in_payout_report_job.rb
- app/mailers/publisher_mailer.rb
- app/models/channel.rb
- app/models/promo_registration.rb
- app/models/publisher.rb
- app/models/publisher_status_update.rb
- app/services/promo/publisher_channels_registrar.rb
- app/views/admin/publishers/publisher_status_updates/index.html.slim
- app/views/publisher_mailer/update_to_tos.html.slim
- app/views/publisher_mailer/uphold_account_changed.html.slim
- app/views/publishers/home.html.slim
- config/locales/en.yml
- lib/tasks/email_tos_update.rake
- test/controllers/site_channels_controller_test.rb
- test/fixtures/publisher_status_updates.yml
- test/fixtures/publishers.yml
- test/mailers/previews/publisher_mailer_preview.rb
- test/mailers/publisher_mailer_test.rb
- test/tasks/launch_promo_test.rb
1. Step one
2. Step two
3. Step three
> Release 2019-06-19

- app/views/admin/publishers/show.html.slim
- lib/tasks/email_tos_update.rake
Fixes error during stopped email
Fixes 500 on pages that don't have an uphold connection
> Update TOS and publisher show view

- app/services/promo/publisher_channels_registrar.rb
Fixes error with registration reddit or github for a promo
> Fix Reddit and Github promo registration

- app/models/channel.rb
Instead of returning 0's returns the correct amount
```json
{"all_channels":6,"twitch":1,"youtube":3,"site":0,"twitter":0,"reddit":1,"github":1,"vimeo":0}
```
> Update stats for github and reddit

- app/mailers/batch_mailer.rb
- lib/tasks/email_tos_update.rake
#
Fixes the queue priority for the rake tasks
> Fix queue priority for all mailers

- app/mailers/batch_mailer.rb
- app/models/channel.rb
- lib/tasks/email_tos_update.rake
1. Step one
2. Step two
3. Step three
> Release 2019-06-22

- lib/tasks/email_tos_update.rake
1. Step one
2. Step two
3. Step three
> Fix ordering when sending emails

- app/mailers/batch_mailer.rb
- lib/tasks/email_tos_update.rake
1. Step one
2. Step two
3. Step three
> Release 2019-06-24

- app/jobs/publisher_removal_job.rb
1. Step one
2. Step two
3. Step three
> Reload the current state before the publisher gets deleted

- app/models/json_builders/channels_json_builder_v2.rb
1. Step one
2. Step two
3. Step three
> Fix the ordering of the excluded channels

- Gemfile
- Gemfile.lock
- app/services/base_api_client.rb
- app/services/promo/client.rb
- app/services/promo/models/owner_state.rb
* Creates a basic service client for interacting with the promo server
* Adds `OwnerState` as a first endpoint to introduce
1. Run `bundle exec rails console`
2. Here's some test code
```ruby
client = Promo::Client.new
client.owner_state.find(id: '1234')
client.owner_state.create(id: '1234', state: Promo::Models::OwnerState::State::SUSPEND)
client.owner_state.find(id: '1234')
client.owner_state.create(id: '1234', state: Promo::Models::OwnerState::State::NO_UGP)
client.owner_state.find(id: '1234')
client.owner_state.destroy(id: '1234', state: Promo::Models::OwnerState::State::SUSPEND)
client.owner_state.destroy(id: '1234', state: Promo::Models::OwnerState::State::SUSPEND)
```
> Create owner_states client for Promo

- app/views/publishers/_choose_channel_type.html.slim
- Removes Vimeo from flag
- Removes new label from twitter
> Remove vimeo from flag

- Gemfile
- Gemfile.lock
- app/mailers/batch_mailer.rb
- app/services/base_api_client.rb
- app/services/promo/client.rb
- app/services/promo/models/owner_state.rb
- app/views/publishers/_choose_channel_type.html.slim
- lib/tasks/email_tos_update.rake
🐛 Fix reloading the state in the delete job
✨ Remove flag hiding Vimeo support
> Release 2019-06-26

- app/models/json_builders/channels_json_builder_v2.rb
1. Step one
2. Step two
3. Step three
> Show the UI on home

- app/views/publishers/_choose_channel_type.html.slim
1. Step one
2. Step two
3. Step three
> Release 2019-06-29

- app/models/json_builders/channels_json_builder_v2.rb
1. Step one
2. Step two
3. Step three
> Only turn on home address for staging and dev

- app/services/promo/models/owner_state.rb
404 in prod because our environment variable ends with a slash so we're getting duplicate
> Fix beginning slash

- config/locales/en.yml
Updates link to a more general help center article, which gives us flexibility to update periodically. 
Closes #1802 
1. Suspend a publisher
2. Ensure link on suspension disclaimer takes them to help center article
> Update suspension info link

- app/jobs/publisher_removal_job.rb
- app/jobs/send_grid/delete_email_job.rb
- lib/send_grid/api_helper.rb
1. Step one
2. Step two
3. Step three
> Remove users from sendgrid

- app/jobs/delete_publisher_channel_job.rb
- app/services/channels/approve_channel_transfer.rb
Fixes tech debt found in channel transfer and when deleting a channel.
> Fix obscure channel transfer logic by not making circular calls

- app/models/json_builders/channels_json_builder_v2.rb
- test/fixtures/uphold_connections.yml
- test/models/json_builders/channels_json_builder_test_v2.rb
Closes https://github.com/brave-intl/publishers/issues/2035
> Gemini v2 api for a single channel

- app/javascript/packs/case.jsx
- app/views/admin/cases/show.html.slim
- app/views/publishers/cases/new.html.slim
- app/views/publishers/cases/show.html.slim
- app/views/publishers/cases/update.js.erb
- fixes the ability to upload files
> Fix direct upload ability

- app/services/payout_report_publisher_includer.rb
- db/migrate/20190710170355_add_status_to_potential_payment.rb
- db/schema.rb
- test/services/payout_report_publisher_includer_test.rb
Resolves #1977
1. Step one
2. Step two
3. Step three
> Nvonpentz fix/1977

- app/views/application/_choose_channel_type.html.slim
> Expose Github from feature flag

- public/creators-landing/src/style/style.css
1. Step one
2. Step two
3. Step three
> Fix viewport width. Closes #2052

- app/assets/stylesheets/admin/pages/unattached_promo_registrations.scss
- app/controllers/admin/unattached_promo_registrations_controller.rb
- app/views/admin/unattached_promo_registrations/index.html.slim
> * Fix sorting on unattached promos

- config/excluded_site_channels.yml
1. Step one
2. Step two
3. Step three
> Change exclusion list to contain uphold

- app/controllers/publishers/cases_controller.rb
We should definitely not show internal notes to users, this is my bad.
> Only show public notes to users

- app/jobs/sync/zendesk/ticket_comments_to_notes.rb
- app/jobs/sync/zendesk/tickets_to_notes.rb
- config/sidekiq.yml
1. Step one
2. Step two
3. Step three
> Fix sync config for zendesk and enable sync

- app/assets/stylesheets/_colors.scss
- app/assets/stylesheets/admin/style.scss
- app/views/admin/shared/_sidebar.html.slim
Could still use more work but I thought this was generally positive.
Closes: https://github.com/brave-intl/publishers/issues/2086
> Admin sidebar

- app/jobs/migrate_uphold_access_parameters_job.rb
1. Step one
2. Step two
3. Step three
> Use return for non-loops

- lib/tasks/database_updates/migrate_uphold_access_parameters.rake
> Release 2019-08-05 Part 2

- app/assets/stylesheets/admin/style.scss
- app/views/admin/channels/index.html.slim
- app/views/admin/partners/index.html.slim
- app/views/admin/partners/new.html.slim
- app/views/admin/payout_reports/index.html.slim
- app/views/admin/publishers/index.html.slim
- app/views/admin/shared/_sidebar.html.slim
- app/views/admin/stats/contributions/index.html.slim
- app/views/admin/stats/publisher_statistics/index.html.slim
- app/views/admin/stats/referrals/index.html.slim
- app/views/admin/stats/top_balances/index.html.slim
- app/views/admin/stats/top_youtube_channels/index.html.slim
- app/views/admin/unattached_promo_registrations/index.html.slim
General polish updates again. 
- consolidated page titles to h4 tags
- consolidated search and filter/sorting action items to one row
- updated default btn to feel more like a button
> Admin title polish

- app/javascript/packs/banner_editor.jsx
1. Step one
2. Step two
3. Step three
> Small UX fix for site banner

- app/assets/stylesheets/admin/style.scss
- app/javascript/packs/banner_editor.jsx
- app/views/admin/channels/index.html.slim
- app/views/admin/partners/index.html.slim
- app/views/admin/partners/new.html.slim
- app/views/admin/payout_reports/index.html.slim
- app/views/admin/publishers/index.html.slim
- app/views/admin/shared/_sidebar.html.slim
- app/views/admin/stats/contributions/index.html.slim
- app/views/admin/stats/publisher_statistics/index.html.slim
- app/views/admin/stats/referrals/index.html.slim
- app/views/admin/stats/top_balances/index.html.slim
- app/views/admin/stats/top_youtube_channels/index.html.slim
- app/views/admin/unattached_promo_registrations/index.html.slim
1. Step one
2. Step two
3. Step three
> Release 2019-08-07

- app/controllers/publishers_controller.rb
- app/views/layouts/static.html.slim
Reverts brave-intl/publishers#2104
> Revert "Devise shows t.devise.failure.timeout after a user signs in. Removing…"

- app/models/publisher.rb
- app/views/admin/channels/index.html.slim
- app/views/admin/partners/index.html.slim
- app/views/admin/publishers/index.html.slim
1. Step one
2. Step two
3. Step three
> Fix broken indentation that broke the form

- app/controllers/admin/publishers_controller.rb
- app/controllers/publishers/uphold_controller.rb
- app/models/publisher.rb
- app/services/manual_payout_report_publisher_includer.rb
- app/views/admin/channels/index.html.slim
- app/views/admin/partners/index.html.slim
- app/views/admin/payout_reports/index.html.slim
- app/views/admin/publishers/index.html.slim
- test/controllers/admin/publishers_controller_test.rb
- test/fixtures/publishers.yml
1. Step one
2. Step two
3. Step three
> Release 2019-08-12

- app/jobs/sync/zendesk/start_job.rb
> Add enqueue_as for Sync::Zendesk::StartJob. Closes #2145.

- app/controllers/publishers_controller.rb
- app/views/layouts/static.html.slim
Reverts brave-intl/publishers#2112
> Revert "Revert "Devise shows t.devise.failure.timeout after a user signs in. Removing…""

- config/initializers/rack-attack.rb
> Rate limit

- Gemfile.lock
1. Step one
2. Step two
3. Step three
> Force upgrade to nokogiri 1.10.4

- config/heavy_sidekiq.yml
Adding the CacheBrowserChannelsJsonJobV3
> Add V3 API to Sidekiq

- app/controllers/publishers/uphold_controller.rb
- app/controllers/publishers_controller.rb
- config/locales/en.yml
closes #2169
- Better messaging around uphold errors
- Fixing the login for invalid access parameters
> Fix login for invalid access parameters 

- app/helpers/application_helper.rb
- app/views/layouts/application.html.slim
- app/views/layouts/error.html.slim
- app/views/layouts/headless.html.slim
- app/views/layouts/no_js.html.slim
- app/views/layouts/static.html.slim
- config/secrets.yml
Closes #2165
1. Step one
2. Step two
3. Step three
> Choose the right piwik host to prevent blocking

- app/controllers/api/v3/public/channels_controller.rb
- app/jobs/cache_browser_channels_json_job_v3.rb
1. Step one
2. Step two
3. Step three
> Add caching for api/v3/public/channels/totals

- lib/tasks/database_updates/create_cards_for_old_parameter_channels.rake
1. Step one
2. Step two
3. Step three
> Backfill to include cards:write

- app/helpers/application_helper.rb
1. Step one
2. Step two
3. Step three
> Fix analytics url

- lib/tasks/database_updates/create_cards_for_old_parameter_channels.rake
1. Step one
2. Step two
3. Step three
> Fix print statement

- Gemfile
- Gemfile.lock
- app/controllers/api/v3/public/channels_controller.rb
- app/controllers/publishers_controller.rb
- app/helpers/application_helper.rb
- app/javascript/publishers/home.js
- app/jobs/cache_browser_channels_json_job_v3.rb
- app/models/channel.rb
- app/models/publisher.rb
- lib/tasks/database_updates/create_cards_for_old_parameter_channels.rake
1. Step one
2. Step two
3. Step three
> Release 2019-08-22

- app/mailers/batch_mailer.rb
- app/views/batch_mailer/update_to_rates.html.slim
- config/locales/en.yml
- lib/tasks/email_rate_change.rake
- test/mailers/previews/publisher_mailer_preview.rb
> Email users about rate changes

- app/mailers/batch_mailer.rb
- app/views/batch_mailer/update_to_rates.html.slim
- config/locales/en.yml
- lib/tasks/email_rate_change.rake
- test/mailers/previews/publisher_mailer_preview.rb
* Email users about rate changes
> Release 2019-08-30 (2)

- app/controllers/publishers/site_banners_controller.rb
- app/javascript/packs/banner_editor.jsx
- app/javascript/packs/style.jsx
- app/models/json_builders/channels_json_builder_v3.rb
- app/models/site_banner.rb
- test/controllers/publishers/site_banners_controller_test.rb
- if the keys are the same as the default we delete them
- removes the warning text, closes #2113
> Remove keys for default site banner values

- app/assets/stylesheets/theme/columns.scss
- app/assets/stylesheets/theme/form.scss
- app/controllers/publishers/site_banners_controller.rb
- app/controllers/publishers_controller.rb
- app/javascript/packs/banner_editor.jsx
- app/javascript/packs/style.jsx
- app/models/json_builders/channels_json_builder_v3.rb
- app/models/publisher.rb
- app/models/site_banner.rb
- app/views/publishers/settings/index.html.slim
- config/locales/en.yml
- config/locales/views/publishers/settings/en.yml
- db/migrate/20190829141054_add_login_duration_to_publishers.rb
- db/schema.rb
- test/controllers/publishers/site_banners_controller_test.rb
✨ 30 day login feature
🐎 V3 API payload size improvements
> Release 2019-09-06

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/tooltip.scss
- app/controllers/admin/payout_reports_controller.rb
- app/helpers/admin_helper.rb
- app/javascript/packs/PayoutReports.jsx
- app/models/payout_report.rb
- app/views/admin/payout_reports/edit.html.slim
- app/views/admin/payout_reports/index.html.slim
- app/views/admin/payout_reports/show.html.slim
- config/routes.rb
* Create show and edit for payout reports
> Release 2019-09-13

- config/routes.rb
1. Step one
2. Step two
3. Step three
> Warn if queue size is greater than 1000. Closes #1969

- app/models/json_builders/manual_payout_report_json_builder.rb
The current built JSON lacks the publisher field so this PR introduces that
> Fix Manual Report JSON Building

- app/views/admin/publishers/_uphold.html.slim
> Nil check for member at

- app/assets/stylesheets/pages/home.scss
- app/controllers/publishers_controller.rb
- app/helpers/payout_helper.rb
- app/views/publishers/_payout_status.html.slim
- app/views/publishers/home.html.slim
- config/locales/en.yml
Frequently users complain that: 
-they don't know how much money they're going to receive
- how that amount was determined
- why they did not get paid
- why payout takes so long
Hence I spent sometime creating a payout progress bar. This has great features such as
- Letting users know where they're at in the process
- How much they will earn
- If they need to re-verify, KYC or something else to receive funds
- Increases progress per day 🎉 
1. Generate final payout report
2. Increase through the days by looking at `payout_helper.rb`
> Make payout process more transparent

- lib/tasks/email/kyc_and_referral_update.rake
1. Step one
2. Step two
3. Step three
> Limit enqueue to only 4000

- tslint.json
- yarn.lock
1. Step one
2. Step two
3. Step three
> Remove yarn.lock and re-added yarn.lock

- tslint.json
- yarn.lock
Reverts brave-intl/publishers#2253
> Revert "Remove yarn.lock and re-added yarn.lock"

- package.json
- yarn.lock
Also need to revert https://github.com/brave-intl/publishers/pull/2252 and merge https://github.com/brave-intl/publishers/pull/2255
> Working compile with updated handlebars

- app/helpers/payout_helper.rb
- app/views/publishers/_payout_status.html.slim
- config/locales/en.yml
> Display generating when Payout Report is in progress

- app/views/publishers/home.html.slim
> Yank payout progress widget out

- app/controllers/application_controller.rb
- config/locales/ja.yml
- test/controllers/admin/organizations_controller_test.rb
- test/controllers/admin/publisher_notes_controller_test.rb
- test/controllers/channel_transfer_controller_test.rb
- test/controllers/channels_controller_test.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
- test/controllers/publishers/registrations_controller_test.rb
- test/controllers/publishers_controller_test.rb
- test/controllers/site_channels_controller_test.rb
- test/controllers/totp_authentications_controller_test.rb
- test/controllers/totp_registrations_controller_test.rb
- test/controllers/two_factor_authentications_controller_test.rb
- test/controllers/two_factor_registrations_controller_test.rb
- test/controllers/u2f_authentications_controller_test.rb
- test/controllers/u2f_registrations_controller_test.rb
- test/features/publishers_home_test.rb
- test/features/sign_up_test.rb
- test/features/site_channel_verification_test.rb
Related to https://github.com/brave-intl/publishers/issues/2186
> Japanese localization via param headers

- app/controllers/application_controller.rb
- app/views/publishers/home.html.slim
- config/locales/ja.yml
- test/controllers/admin/organizations_controller_test.rb
- test/controllers/admin/publisher_notes_controller_test.rb
- test/controllers/channel_transfer_controller_test.rb
- test/controllers/channels_controller_test.rb
- test/controllers/publishers/omniauth_callbacks_controller_test.rb
- test/controllers/publishers/registrations_controller_test.rb
- test/controllers/publishers_controller_test.rb
- test/controllers/site_channels_controller_test.rb
- test/controllers/totp_authentications_controller_test.rb
- test/controllers/totp_registrations_controller_test.rb
- test/controllers/two_factor_authentications_controller_test.rb
- test/controllers/two_factor_registrations_controller_test.rb
- test/controllers/u2f_authentications_controller_test.rb
- test/controllers/u2f_registrations_controller_test.rb
- test/features/publishers_home_test.rb
- test/features/sign_up_test.rb
- test/features/site_channel_verification_test.rb
* Japanese Localization
* Widget fix
> Release 2019-10-02

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
Tested locally to make sure nothing broke.
Closes #1575
> Disables newrelic browser tracking and update newrelic gem

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/channels_controller.rb
- app/controllers/errors_controller.rb
- app/helpers/channels_helper.rb
- app/helpers/publishers_helper.rb
- app/jobs/create_uphold_channel_card_job.rb
- app/views/layouts/full-width.html.slim
- app/views/publishers/_channel.html.slim
- app/views/site_channels/_verification_failed_modal.html.slim
- config/locales/views/publishers/security/ja.yml
- config/locales/views/publishers/settings/ja.yml
- config/locales/views/u2f_registrations/ja.yml
- test/controllers/channels_controller_test.rb
- test/helpers/channels_helper_test.rb
* Fix an issue where site channel that's not verified gets transferred
> Release 2019-10-04

- app/helpers/publishers_helper.rb
> Check balance for no_grants users

- app/controllers/application_controller.rb
- app/helpers/publishers_helper.rb
- app/jobs/sync/zendesk/ticket_comments_to_notes.rb
- app/models/publisher_note.rb
- app/services/publisher_statement_getter.rb
- app/views/admin/publishers/_note.html.slim
- db/migrate/20190903235845_add_sender_email_to_publisher_notes.rb
- db/schema.rb
:bug: Store from_address and to_address from Zendesk for admin app.
:bug: Fail gracefully when we don't have access to uphold transaction.
:bug: Fix redirect loop for suspended publishers.
> Release 2019-10-15

- app/controllers/application_controller.rb
> Fix locale check

- config/environments/development.rb
1. Step one
2. Step two
3. Step three
> Make logs not expand endlessly

- app/javascript/locale/en.ts
- app/javascript/views/statements/Statements.tsx
- app/javascript/views/statements/statements/StatementDetails.tsx
- app/models/views/user/statement_overview.rb
- app/models/views/user/statements.rb
- app/services/base_api_client.rb
- app/services/base_service.rb
- app/services/publisher_statement_getter.rb
- app/services/uphold/models/transaction.rb
- config/locales/en.yml
- test/models/views/statements_test.rb
- test/test_helper.rb
Closes #2329 
- Fixes problem where earning period wasn't accurate due to Eyeshade's created_at time being a month ahead
- Fixes pagination of transactions being missing
- Fixes uncertainty about total earned
One thing I'm thinking about adding is ensuring that there isn't different settlement amounts, like USD and BAT being changed in the middle of the month. This is an edge case i'm not quite sure we should handle yet. 
Message me for transactions and stuff :)
> Fix Statements

- app/helpers/promos_helper.rb
- app/javascript/packs/SettingsPage.tsx
- app/services/publisher_statement_getter.rb
- Fixes bad method call `start` -> `start_date`
- Fixes exception which is raised when a publisher does not have an Uphold Connection
> Bug Fix for statements

- Gemfile
- Gemfile.lock
Adds in translations for basic Rails helpers.
This will help with built-in ActiveRecord, Date, and Currency translations
> Add Rails-i18n

- config/initializers/rack-attack.rb
> Rate limit v3

- config/initializers/rack-attack.rb
> Release 2019-11-14

- db/migrate/20191125222810_add_created_at_index_to_promo_registrations.rb
- db/schema.rb
Used. by https://github.com/brave-intl/publishers/pull/2406/files
> Add index to promo registration order

- app/jobs/set_payout_in_progress_job.rb
- app/views/publishers/_payout_status.html.slim
- config/locales/en.yml
- test/features/log_in_test.rb
> Fix labels for payout in progress. Closes #2415

- app/jobs/set_payout_in_progress_job.rb
- app/services/eyeshade/referrals.rb
- app/views/publishers/_payout_status.html.slim
- config/locales/en.yml
- test/features/log_in_test.rb
🐛 Fix the counts for different groups.
> Release 2019-10-03

- package.json
- public/creators-landing/package.json
- public/creators-landing/yarn.lock
- yarn.lock
- Update packs to have correct versions
> Resolve JS Vulnerabilities

- app/models/views/user/statements.rb
- Reverse sort the statements
Closes #2442
> Reverse sort the Statements

- app/helpers/publishers_helper.rb
🐛 Use base url for paypal redirect
> Access base url from anywhere (#2470)

- app/services/promo/registration_stats_report_generator.rb
In the existing implementation empty events are inserted for each referral code, for each country, and on each date so that there are no missing dates on the report. 
For an average report, the array generated by `fill_in_events_with_no_activity`  would have the size 5,776 + 329,406. The events returned from service being size 5,776.
Afterwards we would run 3 `group_by` statements on the resulting 335,182 items. Causing massive memory leaks and slowdowns
The new implementation removes the insertion of blank events. Missing dates are checked when inserting into the CSV. This reduces complexity by only running `group_by` statements on the 5,776 events returned from the service rather than 335,182 events.
> Reduce complexity in referral reports

- Gemfile.lock
- app/assets/stylesheets/admin/pages/publisher.scss
- app/controllers/admin/publishers_controller.rb
- app/controllers/application_controller.rb
- app/helpers/payout_helper.rb
- app/helpers/publishers_helper.rb
- app/jobs/enqueue_publishers_for_payout_job.rb
- app/jobs/enqueue_publishers_for_payout_notification_job.rb
- app/jobs/include_publisher_in_payout_report_job.rb
- app/jobs/sync/channel_promo_registrations_stats_job.rb
- app/jobs/sync/promo_registration_stats_job.rb
- app/models/payout_message.rb
- app/models/payout_report.rb
- app/services/payout_report_publisher_includer.rb
- app/services/promo/registration_stats_report_generator.rb
- app/services/publisher_wallet_getter.rb
- app/services/uphold_request_access_parameters.rb
- app/views/admin/publishers/show.html.slim
- app/views/publishers/_payout_status.html.slim
- app/views/publishers/home.html.slim
- config/initializers/sidekiq.rb
- config/locales/en.yml
- db/migrate/20200114024815_create_payout_messages.rb
- db/schema.rb
- test/controllers/admin/payout_reports_controller_test.rb
- test/jobs/enqueue_publishers_for_payout_job_test.rb
- test/jobs/enqueue_publishers_for_payout_notification_job_test.rb
- test/services/payout_report_publisher_includer_test.rb
🐛 Fix redirect for Paypal accounts
🐛 Increase robustness and error handling for Payout Reports
🐛 Redux Complexity when generating referral reports. 
🐛 Improve reliability during syncing referral stats
> Release 2020-01-14

- app/views/site_channels/_site_channel_ads_learn_more_modal.html.slim
1. Step one
2. Step two
3. Step three
> Refine the Learn More copy for Publisher Ads consent

- app/assets/stylesheets/theme/form.scss
- app/controllers/api/v3_p1/public/channels_controller.rb
- app/jobs/cache_browser_channels_json_job_v3_p1.rb
- app/jobs/enqueue_publishers_for_payout_job.rb
- app/jobs/enqueue_publishers_for_payout_notification_job.rb
- app/jobs/enqueue_publishers_for_paypal_payout_job.rb
- app/jobs/include_publisher_in_payout_report_job.rb
- app/mailers/publisher_mailer.rb
- app/models/json_builders/channels_json_builder_v3_p1.rb
- app/models/payout_report.rb
- app/models/potential_payment.rb
- app/services/payout_report_publisher_includer.rb
- app/services/paypal/payout_report_publisher_includer.rb
- app/views/admin/payout_reports/index.html.slim
- app/views/publisher_mailer/paypal_missing_bank_account.html.slim
- app/views/publishers/_channel.html.slim
- config/heavy_sidekiq.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20200117010955_add_wallet_provider_to_potential_payments.rb
- db/schema.rb
- test/fixtures/channels.yml
- test/fixtures/site_channel_details.yml
- test/jobs/enqueue_publishers_for_payout_job_test.rb
- test/jobs/enqueue_publishers_for_payout_notification_job_test.rb
- test/services/payout_report_publisher_includer_test.rb
- test/services/paypal/payout_report_publisher_includer_test.rb
Refactor based on @nvonpentz's comments
> Report generation for paypal

- app/jobs/enqueue_publishers_for_payout_job.rb
- app/jobs/enqueue_publishers_for_payout_notification_job.rb
- app/jobs/enqueue_publishers_for_paypal_payout_job.rb
- app/jobs/include_publisher_in_payout_report_job.rb
- app/mailers/publisher_mailer.rb
- app/models/payout_report.rb
- app/models/potential_payment.rb
- app/models/promo_registration.rb
- app/services/payout_report_publisher_includer.rb
- app/services/paypal/payout_report_publisher_includer.rb
- app/services/promo/registrations_stats_fetcher.rb
- app/views/admin/payout_reports/index.html.slim
- app/views/publisher_mailer/paypal_missing_bank_account.html.slim
- config/locales/en.yml
- db/migrate/20200117010955_add_wallet_provider_to_potential_payments.rb
- db/schema.rb
- test/fixtures/channels.yml
- test/fixtures/site_channel_details.yml
- test/jobs/enqueue_publishers_for_payout_job_test.rb
- test/jobs/enqueue_publishers_for_payout_notification_job_test.rb
- test/services/payout_report_publisher_includer_test.rb
- test/services/paypal/payout_report_publisher_includer_test.rb
- test/services/promo/registration_stats_report_generator_test.rb
- test/services/promo/registrations_stats_fetcher_test.rb
✨  Report generation for paypal (#2494)
⚡️ Performance syncing promo stats
> Release 2020-01-27

- app/models/promo_registration.rb
> Tighten query for empty jsonb array on stats column

- app/helpers/payout_helper.rb
🐛 Fix error while rendering the payout helper.
Already approved by previous PR
> Release 2019-02-01

- app/controllers/admin/publishers_controller.rb
- app/controllers/concerns/search.rb
For far too long has search been slow when searching for emails. This is an improvement to search email if the user is searching for an email, by referral_codes if the user is searching for a referral code, or fallback to a generic search if they aren't
> Make search a little better

- app/controllers/api/base_controller.rb
Reverts brave-intl/publishers#2548
> Revert "Remote ip test by stringifying"

- app/controllers/api/base_controller.rb
Reverts brave-intl/publishers#2542
> Revert "Allow fetching from behind heroku forwarding"

- app/controllers/api/base_controller.rb
> Release 2020-02-18

- config/locales/ja.yml
1. Step one
2. Step two
3. Step three
> modified typo in translation

- app/controllers/api/base_controller.rb
- app/controllers/publishers/uphold_controller.rb
- app/javascript/packs/SettingsPage.tsx
- app/models/uphold_connection.rb
- app/services/payout_report_publisher_includer.rb
- app/views/publisher_mailer/uphold_kyc_incomplete.html.slim
- app/views/publisher_mailer/wallet_not_connected.html.slim
- app/views/publishers/settings/index.html.slim
- config/locales/en.yml
- config/locales/views/publishers/settings/en.yml
- config/routes.rb
- db/migrate/20200210213507_add_send_emails_to_uphold_connection.rb
- db/schema.rb
- test/fixtures/uphold_connections.yml
✨ Email snoozing
🌏 Localization fixes
> Release 2020-02-21

- app/javascript/locale/en.ts
- app/javascript/locale/ja.ts
- app/javascript/packs/banner_editor.jsx
- app/models/site_banner.rb
- test/fixtures/site_banners.yml
- test/models/site_banner_test.rb
> Use 1,10,100 as default tip amounts

- app/javascript/locale/en.ts
- app/javascript/locale/ja.ts
- app/javascript/packs/banner_editor.jsx
- app/javascript/views/payments/components/InvoiceShow.tsx
- app/javascript/views/payments/components/editIconInput/EditIconInputStyle.ts
- app/models/site_banner.rb
- app/services/publisher_statement_getter.rb
- package.json
- public/service-worker.js
- test/fixtures/site_banners.yml
- test/models/site_banner_test.rb
- yarn.lock
🐛 Tipping amounts
🐛 Statement fixes
> Release 2020-03-13

- app/javascript/locale/en.ts
- app/javascript/locale/ja.ts
- app/javascript/packs/banner_editor.jsx
- app/models/site_banner.rb
- test/fixtures/site_banners.yml
- test/models/site_banner_test.rb
Reverts brave-intl/publishers#2561
> Revert "Use 1,10,100 as default tip amounts"

- app/javascript/locale/en.ts
- app/javascript/locale/ja.ts
- app/javascript/packs/banner_editor.jsx
- app/models/site_banner.rb
- test/fixtures/site_banners.yml
- test/models/site_banner_test.rb
This reverts commit d50da671b7b4e0898be6d67820bedddb432a5d84.
> Revert "Revert "Use 1,10,100 as default tip amounts (#2561)" (#2582)"

- public/creators-landing/src/style/style.css
Fixes https://github.com/brave/brave-com-resources/issues/97
Changes width of `.bottom-swoop` from `100vw` to `100%`.
> Fix unintended horizontal overflow

- app/services/browser_user_sign_up_service.rb
- app/services/promo/client.rb
- app/services/promo/models/peer_to_peer_registration.rb
- test/services/promo/peer_to_peer_registration_test.rb
Tied to https://github.com/brave-intl/vault-promo-services/pull/160/files
> Use a separate route for peer-to-peer

- public/creators-landing/src/locale/en.js
- public/creators-landing/src/locale/ja.js
- public/creators-landing/src/sections/signoff/index.js
Updates count of verified content creators to 500,000 as per https://github.com/brave/brave-com-resources/issues/96
Changes text to:
> Join over 500,000 content creators and publishers earning more from Brave Rewards
_**NOTE**_: not modified in Japanese.
> Update count of content creator accounts to 500,000
