brave-intl/publishers

app/controllers/publishers_controller.rb, app/views/publishers/new.html.slim, config/locales/en.yml, db/migrate/20170413222129_add_show_verification_status_to_publishers.rb, db/migrate/20170418220835_change_show_verification_status_default_value_for_publishers.rb, db/schema.rb
Add checkbox to setup process allowing publishers to opt-in to making their verification status public
Fixes https://github.com/brave/publishers/issues/68
Auditors: @ayumi
=> Allow publishers to make their verification status public (opt-in)

app/assets/stylesheets/partials/footer.sass, app/views/application/_footer.html.slim, app/views/layouts/application.html.slim, config/locales/en.yml
This adds a footer with a contact link across the bottom of the content area:
I took a guess at the desired text and styling. Of course, I'm open to suggestions.
The email address that's displayed comes from the `:support_email` secret, as specified in #14.
[Resolves #14]
=> Introduce footer with contact link

app/helpers/publishers_helper.rb, app/views/publisher_mailer/uphold_account_changed.html.slim, app/views/publisher_mailer/welcome.html.slim, test/helpers/publishers_helper_test.rb, test/mailers/previews/notification_mailer_preview.rb, test/mailers/previews/publisher_mailer_preview.rb, test/mailers/publisher_mailer_test.rb
Updates the uphold_account_changed and welcome emails to use HTML links to the `brave_publisher_id` .
Adds email previews for all emails in the system to aid in testing. These are not necessary, but they are helpful for quickly viewing the emails. As part of the rails testing framework they will not be available in production. 
I made an assumption that the link should use `http` and not `https` in order to match the probable behavior of the email clients' rendering of found links (for known top level domains).
There are a few emails that appear to not be used any more. I don't see an issue filed to remove them, though it should be considered.
Fixes #46
=> Email brave_publisher_id as link

config/locales/en.yml
Adds a locale string for `phone_normalized` so the validation error field matches the display name for the field.
```
Phone normalized: is an invalid number
```
I encountered this field name mismatch on the `/publishers/new` endpoint. I hope this is a desirable change.
=> Add locale string for `phone_normalized`

app/services/publisher_wallet_setter.rb, config/secrets.yml, docs/publishers-secrets.example.sh, test/jobs/upload_uphold_access_parameters_job_test.rb
These changes are based on changes requested by @mrose17.
A `server` member has been added inside the `parameters` that come from Uphold.
The `UPHOLD_PROVIDER` env var is no longer needed, since we’re always going to just send `uphold` for this value.
=> Refactor JSON sent to wallet endpoint

app/controllers/publishers_controller.rb, app/models/publisher.rb, app/services/publisher_domain_normalizer.rb, app/services/publisher_login_link_emailer.rb, config/locales/en.yml, test/services/publisher_domain_normalizer_test.rb
When the publisher domain is being normalized any provided protocol is
stripped and replaced with `http` before being sent to
`ledger /v2/publisher/identity`.
Handles the case where a domain is malformed, such as including spaces,
before sending it to be normalized. This prevents sending domains to the
ledger which are not valid domains. It also adds a further degree of
consistency between the online and offline modes.
Adds testing for the above and basic mock testing for online mode.
Fixes #53
=> Handles protocols when registering a new publisher

app/helpers/publishers_helper.rb, app/models/publisher.rb
Publishers were being directed to the `/publishers/verification_done` endpoint. After this fix they are directed to the `/publishers/home` endpoint.
=> Fix flow for returning publishers who've completed Uphold verification

app/views/publishers/verification_dns_record.html.slim
The prior approach used a hidden form triggered by a `click` event on an
independent button. This did not work with JS disabled.
This approach converts the independent button to be a submit button for
a standard (non-hidden) form that will submit regardless.
The display of the interstitial should still happen with JS enabled.
Further exploration of an XHR-based alternative that uses polling is 
recommended.
[Resolves #43]
=> Allow DNS verify form to work with JS disabled

app/services/publisher_wallet_setter.rb, test/jobs/upload_uphold_access_parameters_job_test.rb
As per @mrose17’s [comments](https://github.com/brave/publishers/issues/74#issuecomment-326138778), wallet updates can now be made via `PUT /v1/publishers/{publisher}`. 
The `/wallet` suffix has been deprecated.
=> Use general publisher update endpoint for wallet updates

app/assets/stylesheets/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/services/publisher_statement_generator.rb, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/publishers_controller_test.rb, test/services/publisher_statement_generator_test.rb
As described in #74, publishers can now request reports be generated from their dashboard.
A `select` control is provided to choose a period, and a `Generate` link is used to invoke an Ajax call to a new `generate_statement` endpoint. This endpoint invokes the new `PublisherStatementGenerator` service, which requests a report URL from eyeshade.
The report URL that’s returned will be polled periodically to see if it exists (i.e. 200 is returned). Polling is done every 3s with a 2s backoff period. Four attempts are made. All settings can be tweaked easily.
If the report has been generated, a link will be presented to view it.
If the report is not generated during the polling period, the user is told that a link will be emailed when the report is ready.
---
Notes:
_Differences from #74_: …
=> Allow publishers to request statements from dashboard

Gemfile, Gemfile.lock, app/assets/stylesheets/application/publishers.sass, app/assets/stylesheets/application/static.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/mailers/publisher_mailer.rb, app/models/publisher.rb, app/services/publisher_token_authenticator.rb, app/views/application/_nav.html.slim, app/views/layouts/static.html.slim, app/views/publisher_mailer/confirm_email_change.html.slim, app/views/publisher_mailer/notify_email_change.html.slim, app/views/publisher_mailer/verify_email.html.slim, app/views/publishers/create_done.html.slim, app/views/publishers/email_verified.html.slim, app/views/publishers/home.html.slim, app/views/static/index.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20170907123156_add_pending_email_to_publishers.rb, db/schema.rb, test/bundler_audit_test.rb, test/controllers/publishers_controller_test.rb, test/services/publisher_statement_generator_test.rb
This PR addresses three different issues:
* @lgebhardt has tweaked the signup flow to require just an email, as specified in #50. This involves a new layout of the home page and a new form for updating unverified publishers (i.e. adding a name, domain, etc.). Note that some visual elements still need tweaking on the home page.
* As per #110, whenever a user updates their email from the dashboard, they are required to verify it. Emails are sent to the old and new addresses. The dashboard handles pending email addresses via a special notice.
* CVE-2017-5029 has recently been issued against the Nokogiri gem. This vulnerability has been addressed in 1.7.2.
* CVE-2017-9050 for Nokogiri 1.7.2 requires an upgrade to >= 1.8.1, but this will involve some dependency conflict resolution. For now, …
=> Require verification of emails

app/assets/stylesheets/application/publishers.sass, app/views/publishers/home.html.slim, config/locales/en.yml
The dashboard requires JavaScript for much of its functionality.
[Fixes #111]
=> Add a noscript warning to the dashboard

app/services/publisher_host_inspector.rb
The defaults provide a more sensible behavior when the ENV variables are missing.
=> Add default values for PublisherHostInspector offline mode

app/controllers/publishers_controller.rb, app/services/publisher_host_inspector.rb, app/services/publisher_verifier.rb, lib/publishers/fetch.rb, test/services/publisher_host_inspector_test.rb
Fix #127
Separates the HTTP fetch logic form the PublisherHostInspector to its
own module to share with the PublisherVerifier.
=> Verify offline using .well-known public files

app/assets/javascripts/dynamic_ellipsis.js, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/models/publisher.rb, app/services/publisher_verifier.rb, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/publishers_controller_test.rb, test/models/publisher_test.rb
The Uphold status is now displayed on a publisher's dashboard. If appropriate, the publisher is given the opportunity to connect with Uphold. Furthermore, if the Uphold data is still being processed in the background, the user is shown a processing message which dynamically changes the number of dots in a trailing ellipsis. This gives the impression of progress without taking over the UI like the current spinner we've been using. Obviously, this can all be tweaked if we decide to show progress in another way.
[Resolves #112]
=> Introduce dynamic Uphold status display and connection options to the Dashboard

docs/publishers-secrets.example.sh
According to @mrose17, the `transactions` param is not needed.
Note: this change only affects the _documentation_. The `transactions` param should also be removed from env vars.
=> Remove `transactions` from UPHOLD_SCOPE

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/publishers_controller.rb, app/jobs/enqueue_publisher_verifications.rb, app/jobs/verify_publisher.rb, app/models/publisher.rb, app/services/base_api_client.rb, app/services/base_service.rb, app/services/publisher_balance_getter.rb, app/services/publisher_dns_record_generator.rb, app/services/publisher_host_inspector.rb, app/services/publisher_login_link_emailer.rb, app/services/publisher_notifier.rb, app/services/publisher_token_authenticator.rb, app/services/publisher_token_generator.rb, app/services/publisher_verification_file_generator.rb, app/services/uphold_request_access_parameters.rb, config/initializers/init_notifier.rb, lib/error_handler.rb, lib/error_handler_delegator.rb
@evq has been staging the new BAT website and expressed the desire for more comprehensive exception logging, especially API errors.
Currently only unhandled exceptions are sent to our reporting service Sentry; and we handle most exceptions to ensure a good UX (e.g. prevent API 500s from reaching the user instead saying "API Error").
Rather than doing `Raven.capture_exception` everywhere we handle exceptions, I've instead added some metaprogramming to `BaseService` and `ApplicationJob`. I know this is a controversial Ruby style, but weighing the complexity downsides vs quality of life improvements for our ops team I think this is the most pragmatic way.
(Also upgrades Sentry to 2.6.3.)
Auditors: @dgeb @lgebhardt @bsclifton
=> Revert d667863 and instead use a shared error handler

app/assets/stylesheets/application/static.sass, app/assets/stylesheets/variables/fonts.scss
Fixes loading the new local fonts (missing commas). Reverts the landing page to using the default font.
Reduces the amount of empty space above and below the logo.
=> Landing page cleanup

app/assets/stylesheets/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/publishers_controller_test.rb
The helpers used to determine the publisher's status have been refactored to DRY up the logic and ensure that the descriptions match those given in #137 
The publisher's status is now updated both statically and dynamically (when the uphold status is polled). The `publishers/uphold_status` route has been replaced with `publishers/status`. This more general route now includes both the publishers general status and description, as well as the uphold status and description.
=> Ensure publisher's status is set correctly on the dashboard

app/assets/stylesheets/application/publishers.sass, app/views/publishers/verification_github.html.slim, app/views/publishers/verification_public_file.html.slim, config/locales/en.yml
Updates the github instructions per #142
Reworks layout of public file and github verification pages for better flow.
=> Update github verification instructions, rework file upload page

Gemfile, Gemfile.lock, config/i18n-tasks.yml
Will allow management of localizations
Uses the default setup, which may need some customization for a best fit
Documentation can be found at https://glebm.github.io/i18n-tasks/
Along with a host of useful features, it can be used to find unused and missing keys:
```bash
i18n-tasks health
```
Might be useful to integrate with travis to ensure we don't launch with missing strings. This is TBD.
=> Adds i8n-tasks development gem

app/views/publishers/home.html.slim
Because the element was commented out, the event listeners could not be
added.
=> Disable all scripts related to statement_period

app/assets/stylesheets/application/publishers.sass, app/views/publishers/create_done.html.slim
* Show flying email sent logo in the background pinned to the upper right corner (works well in this location as browser resizes)
* Highlight email address in orange
* Simplify email resend logic
Note: the content width will be addressed in a separate PR from @lgebhardt
=> Clean up publishers/create_done page

Gemfile, Gemfile.lock, app/assets/stylesheets/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/jobs/sync_publisher_statement_job.rb, app/mailers/publisher_mailer.rb, app/models/publisher.rb, app/models/publisher_statement.rb, app/services/publisher_statement_generator.rb, app/services/publisher_statement_getter.rb, app/services/publisher_statement_syncer.rb, app/views/publisher_mailer/statement_ready.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20171004075024_create_publisher_statements.rb, db/schema.rb, test/controllers/publishers_controller_test.rb, test/fixtures/publisher_statements.yml, test/models/publisher_statement_test.rb, test/services/publisher_statement_generator_test.rb, test/services/publisher_statement_getter_test.rb
Allows publishers connected to uphold to download statements from eyeshade.
The flow is as follows:
1. A publisher requests a statement for a given period from the dashboard.
2. A request is made to eyeshade's `/v1/publishers/#{publisher.brave_publisher_id}/statement` endpoint. A `reportURL` is returned.
3. The `reportURL` endpoint is polled until eyeshade returns the report as CSV data.
4. The report is saved to the `PublisherStatement` record's `contents`, an encrypted `text` field.
5. An email is sent out to notify the publisher that the statement is ready to view.
6. The dashboard continues to poll a `statement_ready` endpoint, which checks for the presence of `contents`. While polling, `Generating...` is shown with varying ellipsis.
a. When polling succeeds, a `View statement` link …
=> Add statement generation

app/assets/javascripts/dynamic_ellipsis.js, app/assets/stylesheets/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/jobs/sync_publisher_statement_job.rb, app/models/publisher.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/controllers/publishers_controller_test.rb
The dashboard now shows a listing of generated statements. The statements are shown in chronological order, newest at the top. For example:
When Generate is clicked, a new row is added to the top, and `Generating...` is displayed in the "Download" column. 
Once the report is available, the `Generating` link becomes a `Download` link like the others.
If the report doesn't become available within a couple minutes of polling, polling stops and `Delayed` is displayed. The user must either refresh the page or wait for an email (or both) to know when the report is ready.
Only one report can be generated at a time. After the report has been generated, the Generate link reappears.
Fixes #208
=> List generated statements on dashboard

app/models/publisher_statement.rb, lib/tasks/publisher_statements.rake, test/models/publisher_statement_test.rb
After this has been merged, we'll need to configure the heroku scheduler to run it periodically (hourly?).
Closes #206
=> Introduce rake task for clearing expired publisher statements

app/views/publishers/home.html.slim
Unless Uphold has been connected, this error will prevent some of
the dashboard’s dynamic functionality.
Fixes #231
Test Plan:
Tests
Security:
=> Fix dashboard JS error when default currency is not present.

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
Resolves #222 
Test Plan:
Tests
Security:
=> Don't show converted currency if none is set (or if set to BAT)

app/models/publisher.rb, test/fixtures/publishers.yml, test/models/publisher_test.rb, test/services/youtube_channel_getter_test.rb
Adds tests for the `YoutubeChannelGetter` service.
Also fixes a validation bug for the `Publisher` model, which should only be validating the uniqueness of `brave_publisher_id` if it is present.
Test Plan:
Tests
Security:
=> Improve tests related to 233

app/controllers/publishers_controller.rb, test/controllers/publishers_controller_test.rb
Resolves #241
Test Plan:
Tests
Security:
=> Ensure that contact info validation errors are shown

app/services/publisher_statement_generator.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/fixtures/publishers.yml, test/services/publisher_statement_generator_test.rb
This endpoint is used by the PublisherStatementGenerator service to
generate statements. It must be used for content creators (i.e. not
site publishers).
Closes #247
Test Plan:
Tests
Security:
=> Support owners/statement endpoint

app/controllers/publishers/omniauth_callbacks_controller.rb, app/models/publisher.rb, app/models/youtube_channel.rb, app/services/publisher_youtube_channel_syncer.rb, config/locales/en.yml, db/migrate/20171108212006_add_index_to_youtube_channels.rb, db/schema.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb, test/fixtures/publishers.yml, test/fixtures/youtube_channels.yml, test/models/publisher_test.rb, test/services/publisher_channel_setter_test.rb
Adds tests for the OAuth callback controller to handle login, signup, and attempted registration of a claimed channel.
Adds validations on channels and publisher models. Fixes missing index on the text ind for yt channels.
Refines logic around when to send the channels to eyeshade. Still need to determine the best way to test this.
Fixes #246, Fixes #244
A migration is needed after deployment. This may have issue with existing data. If so it's probably easiest to truncate the database.
Test Plan:
Tests
Security:
=> Refine and test the OAuth callback controller

app/controllers/publishers/omniauth_callbacks_controller.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb
Automatically creates a new publisher if the user signs up using oauth, but hasn't created a publisher account using existing flow.
Resolves #235 @ayumi 
Test Plan:
Tests
Security:
=> create publisher when user login from scratch using oauth

app/assets/stylesheets/application/publishers.sass
Makes the channel images circular to match google's normal display.
Test Plan:
Tests
Security:
=> Make channel images circular

app/serializers/publisher_serializer.rb, app/services/publisher_channel_setter.rb, app/services/publisher_token_requester.rb, test/controllers/api/publishers_controller_test.rb, test/fixtures/publishers.yml
Fixes #277 by translating nils to false for `show_verification_status`. 
Test Plan:
Tests
Security:
=> Handle nil case for show_verification_status

config/secrets.yml
Removed quotes from the display name portion of the address. These
are not needed (looked at outdated examples), and if the format is
followed on Heroku it causes a crash on app load.
fixes #275
Note: this change only affects the dev and test environments. Removing the quotes in the staging environment var was enough to fix #275. Still, we should not have a bad example in the app.
Test Plan:
Tests
Security:
=> Change format of from_email

app/assets/stylesheets/application/publishers.sass, app/controllers/publishers/omniauth_callbacks_controller.rb, app/controllers/publishers_controller.rb, app/models/youtube_channel.rb, app/services/publisher_youtube_channel_syncer.rb, app/views/publishers/email_verified.html.slim, config/locales/en.yml, test/controllers/publishers/omniauth_callbacks_controller_test.rb
When a user attempts to claim a channel that's already been claimed, present a useful dialog to let them know who claimed the channel and when.
This dialog can be dismissed either by clicking OK or pressing `Esc`.
Please review: @ayumi @jenn-rhim
Resolves #264
Test Plan:
Tests
Security:
=> Display modal when channel has already been claimed

app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/models/publisher.rb, config/locales/en.yml, test/models/publisher_test.rb
Adds validation to model to ensure a valid pending email is present
if email is not present
Cleanup controller flow
Protects name_from_email in case it's given an invalid email
Fixes #281
Test Plan:
Tests
Security:
=> Handle case when email is missing on a create (Get Started) call

Procfile
will use the RAILS_ENV set in the config
Test Plan:
Tests
Security:
=> remove the env setting for db:migrate

app/controllers/publishers_controller.rb, config/locales/en.yml
This will give different error messages for each error case we test for during signup. Also adds additional logging.
I removed the `sign_out` calls since a signed in user should never be able to get to this method. I don't think it was causing issues, but it's possible.
Not sure this will close #293, but it will hopefully help with debugging. 
Test Plan:
Tests
Security:
=> Clarify the error messages and flow for signup

app/assets/stylesheets/application/static.sass
Resolves #311 by leaving the button border transparently in place rather than removing it on `:hover`
cc: @jenn-rhim 
Test Plan:
Tests
Security:
=> Make log in button border transparent on hover instead of removing

Procfile.dev, README.md
Added an additional Procfile, Procfile.dev without the release phase that was causing the app to exit immediately after start.  You now can start the app with `foreman start -f Procfile.dev`.  This change is reflected in README.md.
Open to other solutions as this is only a slight improvement to the workaround described in #315.
Resolves #315
Test Plan:
Tests
Security:
=> Fix `foreman start` when developing

app/assets/stylesheets/application/static.sass, app/assets/stylesheets/shared/forms.sass, app/assets/stylesheets/variables/breakpoints.scss, app/views/layouts/static.html.slim, app/views/static/index.html.slim
Closes #199. The goal is to improve the mobile responsiveness of the landing page. This PR does not attempt to improve the responsiveness of the site as a whole, only the landing page.
Test Plan:
- Run the branch with your browsers's responsive layout emulation.
Tests
Security:
=> Improve the landing page on mobile.

app/controllers/publishers/omniauth_callbacks_controller.rb, app/models/publisher.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb, test/jobs/enqueue_publisher_verifications_test.rb, test/models/publisher_test.rb
Handles the special case described in #305.
In the special case where a publisher already has a channel claimed, and tries to claim the same channel again using the same email address, they will be taken to the dashboard for their existing account. The new publisher record is removed as it is unneeded.
Adds protection from `destroy` for verified publishers. This is used to assure that the step of destroying the new unneeded publisher is safe.
Fixes #305
Test Plan:
Tests
Security:
=> Support passing a publisher through to the original account when trying to reclaim a channel

app/controllers/api/base_controller.rb, app/services/publisher_verifier.rb, app/services/slack_messenger.rb, config/environments/staging.rb, config/secrets.yml, docs/publishers-secrets.example.sh
Fix #310 
after discussing options with @lgebhardt this seems like the cleanest way (remove #debug log statements and change staging to INFO level).
Test Plan:
Tests
Security:
=> Logging: staging logs to INFO level, add LOG_API_REQUESTS

app/controllers/publishers_controller.rb, app/services/publisher_login_link_emailer.rb
Use `deliver_later` instead of `deliver_later!`. Messages sent with `deliver_later!` do not trigger the 
ActionMailer::LogSubscriber `deliver` method (which handles the logging). And carry this [warning](http://api.rubyonrails.org/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later-21):
"Enqueues the email to be delivered through Active Job. When the job runs it will send the email using deliver_now!. That means that the message will be sent bypassing checking perform_deliveries and raise_delivery_errors, so use with caution."
This will give us consistency in the logging of emails, and combined with #326 will produce short log entries.
Fixes #327
Test Plan:
Tests
Security:
=> use deliver_later instead of deliver_later!

app/views/publishers/contact_info.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml
* Add validation that forces phone numbers to only include numbers, dashes, parentheses, periods, and plus (+).  There is no restrictions on the order or length of characters in accordance with the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle).
* Add title field within html tag to give user more information as to why they can't submit the form if their phone number is invalid
* Add the title message to en.yml for internationalization
Previously, phone numbers were being normalized and saved under a property `phone_normalized`.  If a publisher added an invalid number, only the `phone` property was updated, and `phone_normalized` was untouched.  Only valid numbers will update `phone_normalized`.  So this change does not affect the database, only nudges …
=> Add client side validations for publishers phone numbers

app/controllers/publishers_controller.rb
Resolves #333
I discovered this when testing the production site where I must have triggered and failed recaptcha.  However, it should be noted that I was never prompted to fill out a captcha in the first place.
Test Plan:
Tests
Security:
=> Correct the translation to be flashed when recaptcha verification fails

.gitignore, Gemfile, Gemfile.lock, README.md, config/environments/development.rb, config/puma.rb, lib/tasks/ssl.rake, lib/tasks/ssl/rootCA.cnf, lib/tasks/ssl/server.csr.cnf, lib/tasks/ssl/v3.ext
As we add support for U2F-based 2FA and adopt other cutting-edge web features, we need to be working on an HTTPS domain. This is because some APIs (like U2F) are only available to an SSL host.
Please create an entry in your `/etc/hosts` file for `localhost.ssl` pointing at `127.0.0.1`. The following command should be sufficient:
```
echo "echo '127.0.0.1 localhost.ssl' >> /etc/hosts" | sudo -s
```
I've preferred `localhost.ssl` as a domain over `localhost`. There are two motivations for this:
* Chrome and other browsers have some special `localhost`-only behaviors intended to make development simpler, however the rules are vague and poorly documented. It seems simpler to use a non-standard TLD and avoid any confusion.
* Second we may want to use HSTS at some point. HSTS sets an SSL-only …
=> Run the development server as SSL.

app/assets/stylesheets/application/static.sass
Closes https://github.com/brave-intl/publishers/issues/199. @jenn-rhim and I agree we should open another issue for any further responsiveness work with more detail.
Tweaks font sizes and margins around the logo for the landing page on mobile. This is based on iteration with @jenn-rhim over Slack.
**Desktop**
**iPad**
**iPhone 7**
Tests
Security:
=> Tweak font sizes on mobile

app/services/publisher_login_link_emailer.rb, test/controllers/publishers_controller_test.rb
Fixes #336
/cc @ayumi @nvonpentz 
Test Plan:
Tests
Security:
=> Normalize domain prior to login

app/views/publishers/verification_dns_record.html.slim, config/locales/en.yml
* Remove 'Name' form with @ symbol that may confuse users
* Replace with instructions on adding to root domain, clarify this is often represented by @
* Downcase the 'P' in 'Copy and Paste'
* Add translation for 'Copy to Clipboard' and downcase the 'C'
Resolves #135.
Test Plan:
Tests
Security:
=> Clarify @ symbol for DNS site verifcation

app/controllers/publishers_controller.rb, app/controllers/static_controller.rb, app/views/publishers/new_auth_token.html.slim, app/views/static/index.html.slim, config/locales/en.yml
A hidden field captures the value of the param 'captcha' when the form is loaded, and passes it through to the controller when it is submitted.  When the controller checks to see if a captcha should be loaded, it will now also check if `params[captcha]` is true, and load the captcha if so.
**How To Use**
To test this on development, add the rack-attack and recaptcha gems to development.
1. Go to any form that is protected by captchas (homepage, login)
2. Tack on `?captcha=true` to the URL and reload
3. Submit the form
The captcha will open.
Resolves #339.
Test Plan:
Tests
Security:
=> Allow developers to force a Captcha using query string param

app/assets/stylesheets/application/publishers.sass, app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim
This work addresses the dashboard statement generation issues mentioned in #329 as follows:
* Statement date is no longer shown as a column. Since statements generated > 24 hours ago will be purged, the date is rather meaningless.
* As statements are generated for a period, the corresponding option is eliminated from the select element. Once all options have been exhausted, the statement generation controls are hidden. Thus, only one statement per period can be generated. 
Here's how the dashboard looks with a few statements generated:
And here's how it looks with all the options exhausted:
I believe @jenn-rhim will want to further refine this approach, but this is at least a start.
Test Plan:
Tests
Security:
=> Simplify and improve statement generation

app/controllers/publishers_controller.rb, app/mailers/publisher_mailer.rb, test/controllers/publishers_controller_test.rb, test/mailers/publisher_mailer_test.rb
When a publisher changes their contact email, three emails are now sent.
1. Notification email to original email address
2. Confirmation email to pending email address, with a link to activate the change
3. Copy of confirmation email to Brave internal **(new)**
* Create new `confirm_email_change_internal` email in the publisher mailer
* Add unit tests for existing `confirm_email_change` email in publisher_mailer_tests.rb
* Add test for the entire email change flow in publisher_controller_tests.rb
Resolves #116
Test Plan:
There wasn't a test that covered the entire email update flow.  I added this test, and in one of the checks, verify that the internal email is sent.
I also added a unit test for the existing `confirm_email_change` email in publisher_mailer.rb.
More …
=> Notify admins when publisher emails change

app/controllers/publishers_controller.rb, app/jobs/set_publisher_domain_job.rb, app/models/publisher.rb, app/services/publisher_domain_setter.rb, config/locales/en.yml, test/controllers/publishers_controller_test.rb, test/models/publisher_test.rb, test/services/publisher_domain_setter_test.rb
This fixes a couple edge cases that were not handled well in #342:
* When domain normalization/inspection fails, it is now possible to reattempt submitting the domain (or an updated domain) in the contact info form.
* When a domain that matches an already verified domain has been entered, the error is now displayed properly to the user when JS is enabled.
Fixes #346 
/cc @ayumi 
Test Plan:
Tests
Security:
=> Refactor validations related to brave_publisher_id

config/locales/en.yml
Resolves #356 
Test Plan:
Tests
Security:
=> Add locale label for brave_publisher_id_unnormalized

app/views/publishers/verification_wordpress.html.slim, config/locales/en.yml
Resolves #358 
cc: @jenn-rhim for feedback on wording and placement
Test Plan:
Tests
Security:
=> Add escape hatch link for misidentified WordPress sites

app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/controllers/publishers_controller_test.rb
Resolves #223 
When the status check polling for the Uphold wallet connection keeps failing (whether Publishers, Eyeshade, or Uphold is having trouble completing wallet verification), this introduces a timeout message that displays after 30 seconds letting the Publisher know that we're having some trouble:
This gets the Publisher out of the visually "stuck" state while the background job keeps attempting to verify the Uphold wallet. Should the Publisher reload the page or logout/login, then they will again see the polling message unless/until it again times out.
The worst case scenario of Uphold verification not working at all ultimately will be handled by @nvonpentz's work on #366 which would then result in this page returning to the original "connect to Uphold" prompt after the stalled …
=> Add timeout message for Uphold status polling

app/assets/stylesheets/application/publishers.sass, app/assets/stylesheets/partials/nav.sass, app/views/layouts/application.html.slim, app/views/layouts/publishers.html.slim, app/views/publishers/new_auth_token.html.slim
Refs #349
* Change the viewport scaling to be `1`
* Add padding so the background gradient is visible after the container box on a small screen
* Remove minimum widths from several elements
* Tweak styles at small and extra-small breakpoints to be more reasonable
TODO:
**Mobile at 375px (iPhone7)**
before:
after:
**Mobile at 768px (tablet)**
before:
after:
**At all sizes larger than this, there is no visual change**
=> Tweak styles for the login page on mobile

Gemfile, Gemfile.lock, test/features/publishers_home_test.rb, test/fixtures/publishers.yml, test/test_helper.rb
This PR introduces full-stack feature testing, including JavaScript code. It is roughly related to #348.
Technical summary:
* Introduce minitest-rails-capybara for a feature test harness.
* Make all feature tests (which inherit from `Capybara::Rails::TestCase`) always run the full browser environment.
* Introduce Capybara for driving selenium and browser tests.
* Add chromedriver-selenium which permits us to use headless chrome.
* Write two simple proof-of-concept tests, including one which requires authentication.
* By default have webmock permit network connects (which Capybara uses), however disable them for tests using the `ActionDispatch::IntegrationTest` base class (most of ours, the integration tests).
w/ @kpfefferle.
=> Introduce capybara and headless chrome based tests

.travis.yml
`bundle install` can take 112 seconds, and seems like it isn't cached. Since Bundler already ensures the proper dependencies are loaded for an app lets use the cache and speed up the builds.
[travis docs for this option](https://docs.travis-ci.com/user/caching/#Bundler)
=> Add bundler cache to travis

app/views/publishers/home.html.slim
=> Properly link edit contact form labels to their respective fields

.travis.yml, app/assets/javascripts/u2f_authentications.js, app/assets/javascripts/u2f_registrations.js, app/assets/javascripts/u2f_shared.js, config/environments/test.rb
Recent staging builds have failed https://dashboard.heroku.com/apps/bat-publishers-staging/activity/builds/a9f62851-f233-4542-8ed0-4a9da485a8e1 The error causing this is a syntax error raised when the Uglify gem attempts to parse modern JavaScript code (in this case `let`).
In this PR, we have two goals:
* Fix the bug for now by not using modern JavaScript (`let`)
* Ensure that CI will fail in the future for other developers.
We can further pursue plans for being able to use modern JS via https://github.com/brave-intl/publishers/issues/348
/cc @kpfefferle 
TODO:
=> Have CI precompile assets

app/jobs/sync_publisher_statement_job.rb, test/jobs/sync_publisher_statement_job_test.rb, test/services/publisher_statement_getter_test.rb, test/services/publisher_statement_syncer_test.rb
As per @mrose17's instructions in #368, if the `SyncPublisherStatementJob` fails, it will continue to retry itself for 3 minutes, gradually backing off its wait time from 3 seconds to 10 seconds.
Also adds more complete tests for this job and its associated services.
Fixes #368 
/cc @ayumi 
Test Plan:
Tests
Security:
=> Back off statement sync retries and stop entirely after 3 minutes

app/controllers/publishers_controller.rb, app/services/publisher_domain_setter.rb, test/controllers/publishers_controller_test.rb, test/jobs/sync_publisher_statement_job_test.rb, test/services/publisher_domain_setter_test.rb
When a site does not support https, the option to re-check for https is provided to the publisher as part of the trusted file verification step. The method to perform this check was calling a previously removed method on the Publisher model. 
This PR fixes this method and adds tests to prevent regressions.
This is an urgent fix that should be applied to production ASAP.
Fixes #397 
/cc @ayumi @nvonpentz 
Test Plan:
Tests
Security:
=> Fixes problem checking for https after initial failure

app/jobs/sync_publisher_statement_job.rb
We are getting the following transient test failure on our TOTP/2FA branch:
```
Error:
SyncPublisherStatementTest#test_will_stop_retrying_to_sync_statement_after_3_minutes:
NameError: uninitialized constant SyncPublisherStatementJob::Raven
```
I believe this is happening because SyncPublisherStatementJob is sending an error to Sentry here without first requiring `sentry-raven`:
https://github.com/brave-intl/publishers/blob/e35db38558273fb34d9147fdad53bd59396b031d/app/jobs/sync_publisher_statement_job.rb#L8
This PR simply adds the necessary `require "sentry-raven"` line to SyncPublisherStatementJob in line with other Jobs that send errors to Sentry.
cc: @dgeb
=> Require sentry-raven in SyncPublisherStatementJob

app/controllers/publishers/omniauth_callbacks_controller.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb
Authenticated publishers should be redirected to the email verified
page, while unauthenticated publishers should be redirected to the
landing page.
Fixes #399 
/cc @nvonpentz @ayumi 
Test Plan:
Tests
Security:
=> Ensure that omniauth failures are properly redirected

app/assets/stylesheets/application/publishers.sass, app/views/publishers/email_verified.html.slim, config/locales/en.yml
Resolves #409.
#409 specified that we add the explanation in both choose verification page, as well as the google oauth consent screen.  This covers only the verification screen, as it is not possible to add a message to the consent screen as we previously thought.
* Add new translation for the note
* Add the note to email_verified.html.slim
* Add the styles to publishers.sass
Test Plan:
Tests
Security:
=> Explain why we need Google access on choose verification type page

app/mailers/publisher_mailer.rb, test/mailers/publisher_mailer_test.rb
When we attempt to send a verification email with a blank recipient, we now will raise an error, and log the exception on sentry.  The publisher information, and publication type is also logged.
This should help us pin down why we are attempting to send blank verification emails in the first place.
Refs #404 
* Raise if "To" address is blank in PublisherMailer#verify_email, send to sentry
* Add corresponding test to PublisherMailerTest
Test Plan:
Tests
Security:
=> Add sentry log when sending verification email to blank address

app/assets/javascripts/modal_shared.js, app/assets/stylesheets/application/publishers.sass, app/assets/stylesheets/application/two_factor_registrations.sass, app/assets/stylesheets/shared/modal.sass, app/assets/stylesheets/shared/text.sass, app/assets/stylesheets/variables/colors.scss, app/views/application/_icon_x.html, app/views/layouts/application.html.slim, app/views/two_factor_registrations/index.html.slim, app/views/u2f_registrations/_u2f_registration.html.slim, config/locales/en.yml, test/features/two_factor_registrations_test.rb, test/test_helper.rb
Per mocks in https://github.com/brave-intl/publishers/issues/414 and https://github.com/brave-intl/publishers/issues/394 prompt the user to confirm their action when removing a 2FA registration. This flow is triggered by clicking "Disable" when a TOTP registration exists or "Remove" for any one U2F device. In each case the copy the users sees may vary, however they are always provided a list of what 2FA methods will exist after confirmation.
A technical summary:
* I've added an abstraction which allows developers to create contents for possible modals in tags `<script id="my-modal-content" type="text/html">`. To open these modals add the attribute`data-js-confirm-with-modal` on any link to specify what `id` to look for. For example to open the example script tag above: `<a …
=> Add modal confirmation for 2FA changes

app/views/two_factor_registrations/index.html.slim, app/views/u2f_registrations/_u2f_registration.html.slim, config/locales/en.yml
This is a followup to https://github.com/brave-intl/publishers/pull/424. I mistakingly left out the translation strings work in that PR.
=> Add translation string for 2FA confirm

README.md, app/services/publisher_channel_setter.rb, config/secrets.yml, docs/publishers-secrets.example.sh
Between these additions and the setup instructions I added to the bat-ledger README, everything should be covered.
In config/secrets.yml, we may want to change  the default for `api_eyeshade_offline` under `development:` from `true`, to instead use `<%= ENV["API_EYESHADE_OFFLINE"] %>`, so we end up toggling the secrets script instead of the config file.  In this case I would replace instruction (4).
Resolves #416.
Test Plan:
Tests
Security:
=> Add setup instructions for local eyeshade

app/assets/stylesheets/partials/nav.sass, app/views/application/_nav.html.slim
Resolves #433 by turning the user info (avatar, name, email) contained in the 2FA settings dropdown menu into a link to the home Dashboard page.
Tests
Security:
=> Link user info in 2FA menu to dashboard

app/assets/javascripts/u2f_authentications.js, app/assets/javascripts/u2f_registrations.js, app/views/two_factor_authentications/_u2f.html.slim, app/views/u2f_registrations/new.html.slim, config/locales/en.yml, vendor/assets/javascripts/u2f-api.js
This error will throw for Brave, it shouldn't appear for any other known browser. Currently the timeout is three seconds, which seems generous enough for a browser like Chrome or Opera to open the iframe to the U2F extension.
Fixes #389
Examples of the error:
**Failing to register a U2F device in Brave**
**Failing to authenticate with a U2F device in Brave**
Tests
Security:
=> Add a new "incomplete implemenation" error for U2F

Gemfile, Gemfile.lock, app/controllers/api/publishers_controller.rb, app/mailers/publisher_mailer.rb, app/services/get_whois_emails_for_domain.rb, app/services/publisher_notifier_unverified.rb, app/views/publisher_mailer/unverified_domain_reached_threshold.html.slim, app/views/publisher_mailer/verified_no_wallet.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/api/publishers_controller_test.rb, test/controllers/publishers_controller_test.rb, test/mailers/publisher_mailer_test.rb
A `POST` to `/api/publishers/notify_unverified` with the params:
````
publisher_type: "domain",
params: {
domain: "<domain>"
}
````
Will scrape the WHOIS information for `<domain>` and send a notification email to each distinct valid email address found.  Currently, `publisher_type` can only be `"domain"` until we determine a solution for #372.  I chose this format for the params above because it matches those in the existing `PublisherNotifier` service class for verified publisher notifications.
I chose not to use the existing `PublisherNotifier` service class for this endpoint because that endpoint required an existing publisher record.  We would have to create a publisher record for each valid email address found for the unverified publisher, or refactor the `PublisherNotifier` class …
=> Add endpoint to notify unverified pubs they have money waiting

app/helpers/publishers_helper.rb, app/views/two_factor_registrations/index.html.slim, test/features/two_factor_registrations_test.rb
Fix #442
This enables 2FA, and enables TOTP but hides U2F. U2F is accessible if the user visits `/publishers/two_factor_registrations?u2f=1` or has any U2F devices setup.
Test Plan:
Tests
Security:
=> Turn on 2FA and hide U2F

app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/controllers/publishers_controller_test.rb
As outlined in #224, there are two cases we have to deal with:
> 1. If the Uphold code has not been exchanged for access parameters within the 5 minute window
> 2. If the access parameters have been acquired but not successfully sent to eyeshade
This PR proposes changes in the UI so it is more obvious to the user how/when to reset the connection for (1) and (2)
Last week we encountered an instance of (1).
(1) can be reproduced by commenting out `ExchangeUpholdCodeForAccessTokenJob#perform`, signing up a new publisher, and clicking "Create Uphold Wallet".  When returned to the publisher dashboard, the user was stuck on this (old) screen:
However, they still had the option to "Create Uphold Wallet".  If they were to click this button, it would reset the Uphold connection without problems - …
=> Allow users to connect with uphold when the state has stalled

app/views/publishers/home.html.slim, test/controllers/publishers_controller_test.rb
Resolves #449 
Refs #439, #448 
Test Plan:
Tests
Security:
=> Use data-test instead of obscure css selector

.travis.yml
Adds a before_install section to fix selenium chrome errors seen when testing on travis.
From https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode
Fixes #459
Test Plan:
Tests
Security:
=> Add before_install google-chrome-stable config to travis.yml

Gemfile, Gemfile.lock
Works around issue https://github.com/seattlerb/minitest/issues/730 by setting minitest to 5.10.3 in the Gemfile.lock. I don't like to edit Gemfile.lock, but this seems to be running correctly (and it's only for testing).
closes #455
Test Plan:
Tests
Security:
=> Regress minitest to 5.10.3

.travis.yml
try to fix tests chromedriver crashes
the release to master #470 isn't stoked on travis https://travis-ci.org/brave-intl/publishers/jobs/327791908
this is me attempting to fix it (see https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356004275)
auditors: @lgebhardt @nvonpentz
=> travis: add sudo: required

app/views/publishers/expired_auth_token.html.slim
* Remove hidden field that looks up the brave_publisher_id, which is no longer required to send login links
Resolves #471
Test Plan:
This fix displays the page, and the link triggers a new login link email, which also works.
Tests
Security:
=> Correctly display 'Send me new login link' page

app/assets/stylesheets/application/publishers.sass, app/assets/stylesheets/shared/error-group.sass, app/assets/stylesheets/shared/sub-panel.sass, app/javascript/u2f/authenticationPage.js, app/javascript/u2f/registrationPage.js, app/javascript/u2f/shared.js, app/views/application/_icon_circled_x.html, app/views/publishers/create_auth_token.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/totp_registrations/new.html.slim, app/views/two_factor_authentications/_u2f.html.slim, app/views/two_factor_authentications/index.html.slim, app/views/u2f_registrations/new.html.slim, config/locales/en.yml
This PR closes https://github.com/brave-intl/publishers/issues/393 and closes https://github.com/brave-intl/publishers/issues/394. It introduces a new error style in the header of sub panels.
**Login page**
**Login confirmation**
**Pending authentication via U2F**
**Errored authentication via U2F**
**Warning on TOTP  re-registration**
**Error on U2F registration**
**Error on U2F registration, mobile**. The other pages also adapt in this way: Less padding and no icon.
**GIF to illustrate flow, responsiveness**
TODO:
=> Introduce new styles for errors in the header of U2F

app/models/publisher.rb
Closes #415.
Eyeshade may return an action of `authorize` or `re-authorize`. Both of these actions suggest that the user should be prompted to reconnect to their uphold account.
* The reconnect button in at: https://github.com/brave-intl/publishers/blob/0c497ac13ae10d0aab727980c0296e5d6ae215dd/app/views/publishers/home.html.slim#L295
* It is only shown if `show_uphold_connect?(publisher)` is true. That logic is here: https://github.com/brave-intl/publishers/blob/0c497ac13ae10d0aab727980c0296e5d6ae215dd/app/helpers/publishers_helper.rb#L23. If Eyeshade provides and action of `authorize` we expect `publisher.uphold_status` to be `:unconnected`. Currently it is `:verified`, thus the reconnect button is not shown.
* `publisher.uphold_status` is based on several other properties at …
=> Prompt to reconnect if eyeshade action = authorize

app/assets/stylesheets/application/publishers.sass, app/controllers/channels_controller.rb, app/controllers/publishers_controller.rb, app/serializers/channel_serializer.rb, app/services/publisher_channel_setter.rb, app/views/publishers/email_verified.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, db/migrate/20180116200817_add_visible_to_publishers.rb, db/schema.rb, test/controllers/api/channels_controller_test.rb, test/controllers/channels_controller_test.rb, test/controllers/publishers_controller_test.rb, test/controllers/site_channels_controller_test.rb, test/fixtures/channels.yml, test/fixtures/publishers.yml, test/jobs/upload_uphold_access_parameters_job_test.rb
This flag controls whether channels can be listed as Brave Verified Publishers. Instead of setting this flag on individual channels, it should now be set once per publisher.
A checkbox has been added to both the complete registration step and the dashboard.
Closes #403
/cc @ayumi @jenn-rhim 
The updated "complete registration" panel:
The updated dashboard (note the new "Verified" label on the channel - this is just a first attempt):
Test Plan:
Tests
Security:
=> [Multichannel] Move `visible` flag from channels to publishers

app/controllers/publishers_controller.rb, app/models/publisher.rb, db/migrate/20180118022455_add_agreed_to_tos_to_publishers.rb, db/schema.rb, test/controllers/publishers_controller_test.rb, test/fixtures/publishers.yml, test/models/publisher_test.rb
The `agreed_to_tos` timestamp marks the first time that a publisher has completed signup and thus explicitly agreed to the site’s TOS.
Publisher verification, and thus access to the dashboard, will be blocked on the presence of `agreed_to_tos`. Thus, all returning publishers will be presented with the complete signup page.
Closes #379 
attn: @ayumi 
Test Plan:
Tests
Security:
=> Add timestamp for when publishers agree to the TOS

app/assets/stylesheets/application/site_channels.sass, app/views/site_channels/_nav.html.slim, config/locales/en.yml
Reworks the navbar in accordance with @jenn-rhim’s requests in #383:
* Show `Add Channel` on the left in place of `Brave Payments`. This is now text and not a link.
* Removes the login panel on the right in place of a `Cancel` button that returns you to the dashboard.
Does not attempt to rework the progress train settings because more clarification is needed. There are unspecified states in #383 during the verification process.
Test Plan:
Tests
Security:
=> Custom navbar for adding site channels

Gemfile, Gemfile.lock
Getting “no implicit conversion of nil into String” messages from puma. Looks like this is an issue introduced in 3.11 per https://github.com/puma/puma/issues/1483, https://github.com/puma/puma/issues/1502
I'm not entirely sure it's causing a real issue, but it is a nuisance.  I propose we regress to 3.10 until this is fixed.
Test Plan:
Tests
Security:
=> Regress Puma to 3.10 to fix “no implicit conversion of nil into String”

app/assets/stylesheets/theme/columns.scss, app/assets/stylesheets/theme/panels.scss, app/assets/stylesheets/theme/text.scss, app/views/layouts/publishers.html.slim, app/views/publishers/create_done.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/publishers/sign_up.html.slim
* Port the sign up page to Bootstrap 4
* Port the sign up completed page to Bootstrap 4
* Change `col-small-centered` to be a bit more friendly, not require internal `.row` elements
* Add `single-panel--wrapper--medium` which is larger than the default `single-panel--wrapper`
* Add `single-panel--content--email-sent` which adds padding and a paper plane background image, but only does so at a large viewport size.
* Errors during signup will suffer from the same style issues resolved by https://github.com/brave-intl/publishers/pull/510
* Remove these pages from the legacy viewport scaling.
TODO:
**Before: Sign up, large screen**
**After: Sign up, large screen**
**Before: Sign up, medium screen**
**After: Sign up, medium screen**
**Before: Sign up, small screen**
**After: Sign up, small …
=> Bootstrap4: Port sign_up and create_done

app/assets/stylesheets/_bootstrap-config.scss, app/assets/stylesheets/_bootstrap-custom.scss, app/controllers/publishers_controller.rb, app/views/layouts/application.html.slim, app/views/publishers/_login_link.html.slim, app/views/publishers/create_auth_token.html.slim, app/views/publishers/new_auth_token.html.slim, config/locales/en.yml
This is a follow-up to #490. I noticed during my testing this morning that we neglected to style the alert that appears if the email address can't be found during login.
I also performed some follow-up cleanup work that I think we should continue doing along the way during this transition to Bootstrap 4:
- Arrange the login flow translation strings so that they can use template-relative shorthand when possible.
- Sort our `bootstrap-config` variables to match the order that they appear in the original `bootstrap/variables` that they are modifying (with section header comments).
cc: @mixonic
=> Add Bootstrap 4 styling for login alert

app/views/publishers/create_auth_token.html.slim
A small style fix for the "login successful" page.
**Before**
**After**
=> Fix a style regression on the login successful page

app/views/publishers/create_done.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/publishers/sign_up.html.slim, app/views/static/index.html.slim, config/locales/en.yml, test/features/publishers_home_test.rb
I was working on this to be included in #511, but it got merged before I got the commit pushed. This does the same i18n refactoring for the sign up flow as I did earlier for the log in flow.
=> Refactor sign up i18n strings

app/assets/stylesheets/static.scss, app/controllers/publishers_controller.rb, config/locales/en.yml
- Refactors i18n alert strings handled by the `Publishers#create` action.
- Changes the redirect for these alerts to `sign_up_publishers_path` since the sign up form is no longer on the main landing page.
- Re-enables the Bootstrap 3 alerts CSS on the static landing page as I noticed those were unstyled when an alert redirected there (which I'm sure still affects some auth-related alerts).
=> Bootstrap 4: Sign up alerts

Gemfile, Gemfile.lock, app/assets/stylesheets/_colors.scss, app/assets/stylesheets/theme/panels.scss, app/controllers/publishers_controller.rb, app/views/application/_panel_flash_messages.html.slim, app/views/layouts/application.html.slim, app/views/publishers/create_auth_token.html.slim, app/views/publishers/create_done.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/publishers/sign_up.html.slim, config/locales/en.yml, test/controllers/publishers_controller_test.rb
This introduces unified support for `:alert`, `:notice` and `:warning` as flash messages for anywhere in the app and all have `_html_safe` variants as well.
This also introduces styles for different flash messages within a panel on the Bootstrap 4 pages. A panel template should use this render partial:
```slim
.single-panel--wrapper
= render "panel_flash_messages" // <------
.single-panel--content
h3.single-panel--headline Howdy user!
```
With that partial flash messages will no longer appear below the navbar, instead they will appear as part of that panel. For example:
**`flash[:alert] = message`**
**`flash[:notice] = message`**
edit: Colors here have changed, see https://github.com/brave-intl/publishers/pull/515#issuecomment-359998380
**`flash[:warning] = message`**
TODO:
=> Style alert, warning and notice messages in panels

app/views/application/_panel_flash_messages.html.slim, app/views/layouts/application.html.slim
This is a follow up to review of #515. The only change I make here is that I recommend that we stick to the convention within Slim templates of using static classes when possible in place of the `div` selector (or attached directly to other elements) and only use `class=""` for dynamically generated class names. IMO, this helps make it readily apparent which classes are statically applied vs. dynamically generated.
cc: @mixonic
=> Bootstrap 4: Panel flash followup

app/controllers/api/owners_controller.rb, app/serializers/publisher_serializer.rb, config/routes.rb, test/controllers/api/owners_controller_test.rb
~~This is built on #519 and it should not be merged until after that. Done for expediency since it will result in merge conflicts otherwise.~~ Fixed now that #519 was merged.
Implements #521
Example data:
```json
[
{
"owner_identifier": "publishers#uuid:8115922c-f8f5-48e6-b035-308a2525d933",
"email": "user2@gmail.com",
"name": null,
"phone": null,
"phone_normalized": null,
"channel_identifiers": []
},
{
"owner_identifier": "publishers#uuid:1beb20ad-dc87-4f9d-86bb-7aa03828c6fc",
"email": "user3@brave.com",
"name": "Marshall Rose",
"phone": null,
"phone_normalized": null,
"channel_identifiers": [
"youtube#channel:UCU4cR3CS1fHUGf_TTLYH8NQ"
]
}
]
```
Test Plan:
Tests
Security:
=> Owners data export

config/application.rb, config/environments/staging.rb, config/secrets.yml
env vars would be an easier way to toggle on/off verbose logs in dev/staging
=> use env var to log verbosely only sometimes

Gemfile, Gemfile.lock, app/controllers/api/owners_controller.rb, app/serializers/publisher_serializer.rb, config/secrets.yml, test/controllers/api/owners_controller_test.rb
Fixes #528, #521 
Test Plan:
Tests
Security:
=> Add show_verification_status to /api/owners endpoint, exclude blank fields and unverified owners

app/views/publishers/home.html.slim
This fixes a problem on `staging2` only - this change never made it to `staging`. Mea culpa, I introduced this problem while pattern matching on some other event handlers.
The default event handling must be allowed to proceed for the visibility checkbox and the currency selector, or else the elements themselves won’t reflect updates.
/cc @ayumi 
Test Plan:
Tests
Security:
=> BUGFIX: Remove unnecessary prevention of default event handling

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/btn.scss, app/assets/stylesheets/pages/two_factor_authentications.scss, app/assets/stylesheets/theme/columns.scss, app/assets/stylesheets/theme/error-group.scss, app/assets/stylesheets/theme/panels.scss, app/assets/stylesheets/theme/svg.scss, app/assets/stylesheets/theme/u2f.scss, app/views/layouts/two_factor_authentications.html.slim, app/views/two_factor_authentications/_totp.html.slim, app/views/two_factor_authentications/_u2f.html.slim, app/views/two_factor_authentications/index.html.slim
This converts the 2FA flows to Bootstrap 4.
* Adds `pages/` folder to the styles. This is for utility classes specific to a single page, not ones re-used across other pages on the site.
* Add `.btn-wide` for full-width buttons
* Tweak `.col-small-centered` and the single panel styles to have nicer responsiveness.
* Include a commit to add padding to the bottom of a page if the panel is taller than the viewport.
* Bring the error-group styles over from legacy
* Bring the `.js-feature-u2f-available` styles over from legacy
**Security key attempt**
**Security key error**
**TOTP**
**TOTP error**
**User only has security key, but is using an unsupported browser**
**User has security key and TOTP, but is using an unsupported browser**
TODO
=> Bootstrap4: Convert the 2FA flows

.travis.yml, app/models/publisher.rb, db/migrate/20180112150747_rename_recreate_totp_u2f.rb, db/migrate/20180116180231_rename_recreate_statements.rb, db/schema.rb, lib/legacy_data.rb, lib/tasks/temp/transform_legacy_data.rake, test/tasks/transform_legacy_data_test.rb
This rake task transforms the legacy publishers data to owners and channels. Legacy publishers which share an email address are consolidated to a single Publisher (Owner) record.
Each legacy publisher is also migrated to a channel associated with the common Owner created above. Channel type is either site or youtube.
* Sessions are being dropped.
* U2F registrations from all channels owned by the same owner are recreated with the owner.
* Existing Totp registrations are moved over only if there is a single one across the owner space.
An Owner's `visible` status is set to true if all the rolled up legacy publishers `show_verification_status` flags were true.
The rake task runs in a dry run mode unless the `commit` flag is provided:
```bash
bin/rake publishers:transform_legacy_data …
```
=> Introduce publishers:transform_legacy_data rake task

app/views/publishers/home.html.slim, test/features/publishers_home_test.rb
This allows the contact form to be submitted multiple times without refreshing the page.
Fixes #543
/cc @mixonic @ayumi 
Test Plan:
Tests
Security:
=> Re-enable submit button after submitting contact form

Gemfile
During development today, I received the following warning when running `bundle install`:
```
Your Gemfile lists the gem rails-controller-testing (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
```
It appears that both #519 and #515 introduced the `rails-controller-testing` gem, one inside the `group :test do` block and one inside the `group :development, :test do` block. Since this is a gem used for testing and #515 introduced it to development without making use of it, I'm going to guess that the introduction there was unintentional (and likely cropped up as part of a rebase or something).
I've removed the redundant listing inside of the `group :development, :test do` …
=> Remove duplicate rails-controller-testing

app/views/two_factor_authentications/_u2f.html.slim, config/locales/en.yml
From https://github.com/brave-intl/publishers/issues/551:
* Ensure the "security key unsupported" headline is not inside the small column.
* If user has U2F and TOTP but no U2F support change the message to: "Your preferred method of two-factor authentication is security key. But it's not supported by your current browser. Switch to Google Chrome or Opera or login using authentication code below."
* If user has U2F and no TOTP, but no U2F support change the message to: "Switch to Google Chrome or Opera to log in. We recommend setting up authenticator app as a backup method for two-factor authentication for this situation." and the title to "Security key not supported by your browser."
Really we're only looking at the content here. There is also a change in styles we want to do for these …
=> Change some warning content for U2F

app/serializers/publisher_serializer.rb, lib/tasks/temp/export_eyeshade_transition_data.rake, test/controllers/api/owners_controller_test.rb
A rake task to implement #548. Tests have not yet been added for this.
Run as:
```bash
bin/rake publishers:export_eyeshade_transition_data
```
Example of output file, which will be stored in the user's home directory and named "publishers_eyeshade_transition_file.json":
```json
[
{
"owner_identifier": "publishers#uuid:02e81b29-f150-54b9-9a08-ce75944f6889",
"email": "alice@default.org",
"name": "Alice the Pyramid",
"phone": "4159001420",
"phone_normalized": "+14159001420",
"show_verification_status": true
},
{
"owner_identifier": "publishers#uuid:8f3ae7ad-2842-53fd-8b63-c843afe1a33a",
"email": "alice@verified.org",
"name": "Alice the Verified",
"phone": "4159001421",
"phone_normalized": "+14159001421",
"channel_identifiers": [
"verified.org"
],
"show_verification_status": true
},
...
]
``` …
=> Add rake task to export eyeshade transition file

app/javascript/utils/dynamicEllipsis.js
An undeclared variable was preventing the dynamic ellipsis from functioning when doing things like generating statements on the dashboard.
This also modernizes the JS to favor `let` instead of `var`.
Test Plan:
Tests
Security:
=> Fix dynamic ellipsis

app/views/publishers/home.html.slim
Once Uphold connects dynamically via polling, the statement generation UI is now shown automatically without requiring a page reload.
I'm guessing that this fixes the problem @jenn-rhim is referencing in #542 
Note: I'd like to perform some comprehensive cleanup of the JS on the dashboard and move it to an external JS module, but I'm trying to keep the fixes targeted before release.
Test Plan:
Tests
Security:
=> Automatically show statement UI after uphold connection

app/controllers/channels_controller.rb, app/views/errors/shared.html.slim, app/views/layouts/error.html.slim, lib/error_handler.rb, test/controllers/api/owners_controller_test.rb, test/controllers/channels_controller_test.rb, test/serializers/publisher_serializer_test.rb
After handling exceptions with sentry raven the exceptions are re-raised so the standard rails exception handling can display the 500 error page.
The shared error page was updated with the thinker emoji and newer brave logo.
This change exposed an issue when rendering a 404 response when trying to delete a missing channel. The exception was getting swallowed. It's been changed to a redirect back to the dashboard. 
The api/owners controller tests were brittle and this broke them as well. Updated to a separate serializer test and simplified the api test.
Fixes #517
- [] Submitted a [ticket](https://github.com/brave-intl/publishers/issues) for my issue if one did not already exist.
Test Plan:
Tests
Security:
=> 500errorpage

app/services/site_channel_verifier.rb
A stopgap fix for #579. The verifications will still be attempted hourly, but this should stop the exceptions being caught by Sentry.
Test Plan:
Tests
Security:
=> handle case where channel being verified does not match eyeshade response

app/assets/stylesheets/legacy/application/publishers.sass, app/javascript/modal.js, app/views/layouts/application.html.slim, app/views/publishers/_remove_channel_modal.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml, test/features/publishers_home_test.rb, test/fixtures/publishers.yml
Closes #576. Stop using `window.confirm`, instead use our HTML dialog.
TODO:
**Confirming a channel removal, desktop**
**Confirming a channel removal, mobileish**
This page is not really responsive, but here is what  it looks like:
=> Use an HTML modal for channel removal confirmation

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
In the case when a publisher has not been assigned a wallet, this helper should return the `publishers.balance_error` message without also logging a Sentry exception.
Fixes #587
/cc @ayumi 
Test Plan:
Tests
Security:
=> Ensure that publisher_humanize_balance helper works without a wallet

config/locales/en.yml
This brings the changes @nvonpentz made in https://github.com/brave-intl/publishers/commit/2f058c4a53d6c88a787aefc27d83752d5559a5e9 and https://github.com/brave-intl/publishers/commit/00a26ffa797e2922be70f579fb409ff813feaad7 over to the multichannel code.
Fix #596
Test Plan:
Tests
Security:
=> Update wordpress plugin location

app/assets/stylesheets/legacy/application/site_channels.sass, app/controllers/site_channels_controller.rb, app/views/site_channels/verification_github.html.slim, app/views/site_channels/verification_public_file.html.slim, config/locales/en.yml
Shows filename for reference and adds note about not changing the filename.
Also fixed an issue with missing file content on public_file page introduced in the multichannel changes.
Fixes #598
WIP pending review by @jenn-rhim
Test Plan:
Tests
Security:
=> Add filename and note about not changing filename or contents

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
`publisher_converted_balance` should return `Unavailable` when there is no wallet set for a publisher.
This helper should _not_ raise sentry exceptions in this scenario.
/cc @ayumi 
Test Plan:
Tests
Security:
=> publisher_converted_balance helper should work when no wallet is set

app/controllers/publishers_controller.rb, app/models/publisher.rb, app/services/publisher_login_link_emailer.rb, db/migrate/20180207143046_make_email_index_case_insensitive.rb, db/schema.rb, test/controllers/publishers_controller_test.rb
Fixes #604
Test Plan:
Tests
Security:
=> use case insensitive find by email for logins

app/assets/stylesheets/theme/columns.scss, app/assets/stylesheets/theme/nav.scss, app/assets/stylesheets/theme/panels.scss, app/views/application/_nav.html.slim, app/views/layouts/publishers.html.slim, app/views/publishers/email_verified.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/publishers/sign_up.html.slim, test/controllers/publishers_controller_test.rb, test/features/publishers_home_test.rb
Port the `email_verified` page to Bootstrap 4. This page prompts the user to enter their name after signup. I've also added some tests around the flow.
Locally I'm getting test failures that seem related to Chrome beta/canary. For `fill_in` I get an error `call function result missing 'value'`. I'll keep looking into this, but I believe we should work around it by pinning Chrome versions where possible.
* https://stackoverflow.com/questions/48609069/org-openqa-selenium-webdriverexception-unknown-error-call-function-result-miss/48665237#48665237
**Before**
**After**
=> Port signup flow to Bootstrap 4

app/serializers/publisher_serializer.rb, test/fixtures/publishers.yml, test/serializers/publisher_serializer_test.rb
Note, this api filters out `blank` values. This includes false booleans. 
Fixes #616 
Test Plan:
Tests
Security:
=> Adds `default_currency` and `uphold_verified` to owners serializer

test/tasks/transform_legacy_data_test.rb
Resolves #621  
Test Plan:
Tests
Security:
=> Comment out transform legacy data test that was breaking the build

app/jobs/application_job.rb, test/test_helper.rb
This fixes the issue observer in #629 where tests jobs are entered into the development redis queue. it also sends the RecordNotFound errors to Raven. That shouldn't happen on production, but...
Fixes #629
Test Plan:
Tests
Security:
=> Job record not found exceptions

app/controllers/publishers/omniauth_callbacks_controller.rb, app/controllers/publishers_controller.rb, app/controllers/site_channels_controller.rb, app/helpers/publishers_helper.rb, app/views/application/_icon_circled_check.html, app/views/publishers/change_email.html.slim, app/views/publishers/change_email_confirm.html.slim, app/views/publishers/choose_new_channel_type.html.slim, app/views/publishers/email_verified.html.slim, config/initializers/devise.rb, config/locales/en.yml, config/routes.rb, test/controllers/api/owners_controller_test.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb, test/controllers/site_channels_controller_test.rb, test/fixtures/channels.yml, test/fixtures/publishers.yml, test/fixtures/youtube_channel_details.yml
This PR adds OAuth login for publishers that were created through the login attempt of a youtube channel.
Access to this login process is through a non public link "/publishers/auth/youtube_login".
The OAuth logins have also been reworked to handle login separately from channel authentication. The changes require the creation of two new "Authorized redirect URIs". For example these are the URIs for a development server, and must be [entered](https://console.developers.google.com/apis/credentials) before merging this PR:
`http://localhost:3000/publishers/auth/register_youtube_channel/callback`
`http://localhost:3000/publishers/auth/youtube_login/callback`
and we can remove the old one once the changes are deployed:
`http://localhost:3000/publishers/auth/google_oauth2/callback`
**Todo** …
=> Adding youtube login back in

app/assets/stylesheets/pages/two_factor_authentications.scss, app/assets/stylesheets/theme/columns.scss, app/assets/stylesheets/theme/panels.scss, app/views/application/_icon_circled_check.html, app/views/layouts/publishers.html.slim, app/views/layouts/totp_registrations.html.slim, app/views/layouts/two_factor_authentications.html.slim, app/views/layouts/two_factor_registrations.html.slim, app/views/layouts/u2f_registrations.html.slim, app/views/publishers/change_email.html.slim, app/views/publishers/change_email_confirm.html.slim, app/views/publishers/create_auth_token.html.slim, app/views/publishers/create_done.html.slim, app/views/publishers/email_verified.html.slim, app/views/publishers/expired_auth_token.html.slim, app/views/publishers/new_auth_token.html.slim, app/views/publishers/sign_up.html.slim, app/views/totp_registrations/new.html.slim, app/views/two_factor_authentications/_u2f.html.slim, app/views/two_factor_authentications/index.html.slim, app/views/two_factor_registrations/index.html.slim, app/views/two_factor_registrations/prompt.html.slim, app/views/u2f_registrations/new.html.slim
Introduce a more whitespace-friendly pane layout. Closes #552 
This changes the layout DOM, and introduces new ways to size content:
* `.single-panel--wrapper.` a wrapper with a max-width of 40em (1em is 16px, so 640px). It also has a min-height to ensure it looks good even if there is not a lot of content.
* `.single-panel--wrapper.single-panel--wrapper--medium` a wrapper with a max-width of 45em or 720px.
* `.single-panel--wrapper.single-panel--wrapper--large` a wrapper with a max-width of 50em or 800px.
* `.single-panel--padded-content` is used inside `.single-panel--content`. It provides padding of 2em or 32px on all sides until the extra small breakpoint, and ensures the content is vertically centered.
* `.col-small-centered` is 66% of a panel's width until the extra small …
=> Refactor panels to better show whitespace

app/javascript/analytics.js
Fix #636
I tried to manually trigger a tracking event on prod with:
`_paq.push(['trackEvent', 'test', 'console', 42])`
This led to an error about a Piwik tracker not being configured.
I hypothesize that the migration to webpacker removed global scope from our JS files. This PR assigns `_paq` to `window` to be sure it's global. I've deployed it to staging2, and it fixed the above error with tracker configuration.
Test Plan:
Tests
Security:
=> Fix piwik by using window._paq

app/controllers/api/tokens_controller.rb, app/jobs/enqueue_site_channel_verifications.rb, app/models/site_channel_details.rb, app/serializers/token_serializer.rb, config/routes.rb, test/controllers/api/tokens_controller_test.rb
Get the verification token information required by eyeshade. Will be a JSON array in the format of:
```json
[
{
"owner_identifier": "publishers#uuid:2dad1d64-570e-42b5-a5a8-f9affe30964b",
"brave_publisher_id": "some_site.com",
"verification_token": "511e9702aeb09d28ad7fe7696b7439467e85843655ad9900272bda355b40a8af",
"verification_id": "1b157ac5-68c0-4458-bb76-f5d9ac72deba"
}
]
```
Supports pagination (`page` and `per_page`) and a `max_age` parameter (in days) that sets how far back to consider tokens as active. The default is 42 days (6 weeks).
fixes #615
Test Plan:
Tests
Security:
=> Add /api/tokens endpoint to get unverified recent site channels for eyeshade

app/models/site_channel_details.rb, app/models/twitch_channel_details.rb, app/models/youtube_channel_details.rb, app/services/publisher_channel_setter.rb
Also underscores authorizer_email and authorizer_name for consistency with other ruby methods in the project. 
fixes #659
Test Plan:
Tests
Security:
=> Add missing authorizer methods to site_channel_details

app/views/layouts/publishers.html.slim
The same fix for #656 must also be applied for the YouTube auth accounts required to update their email.
/cc @nvonpentz @ayumi 
Test Plan:
Tests
Security:
=> Ensure Bootstrap4 styles are applied to update_email action

app/helpers/promos_helper.rb, app/services/promo_registrar.rb, app/views/promo_mailer/new_channel_registered_2018q1.html.slim, app/views/promo_mailer/promo_activated_2018q1_verified.html.slim, app/views/promo_registrations/_activated_verified.html.slim, app/views/promo_registrations/_active.html.slim, config/locales/en.yml
Resolves #667 
* Add PromoRegistrar# twitch_request_body
* Add PromosHelper# on_channel_type to display 'on Twitch' or 'on YouTube' next to channel name
Test Plan:
Tests
Security:
=> Add Twitch support for the referral promo

app/views/publishers/home.html.slim
The channel selection popup was firing from the header, however it must also fire from the prompt when no channel has been added. This ensures it fires from both locations:
=> Add channel selection popup from prompt

app/controllers/publishers_controller.rb, app/models/publisher.rb, config/locales/en.yml, test/mailers/publisher_mailer_test.rb, test/models/publisher_test.rb, test/services/publisher_unverified_calculator_test.rb
- Prevents pending email from being set to an email that already is
verified.
- Also handles the special case above where the pending email is being
changed to the current email.
Partially addresses #664. To close it we need to update the dashboard to handle the returned validation error.
Test Plan:
Tests
Security:
=> Add validations for pending_email

app/models/channel.rb
Resolves #686
I'll try and remedy this on promo services side, and write a PR that appends `youtube#channel:` and `twitch#channel` to the respective channel ids.
Test Plan:
Tests
Security:
=> Add comment explaining Channel#channel_id

app/controllers/publishers/omniauth_callbacks_controller.rb, app/helpers/publishers_helper.rb, app/views/application/_channel_taken.html.slim, config/locales/en.yml
Because Twitch offers no way for publishers to force the Twitch OAuth approval prompt to appear, we need to message to users that they may want to log out of their Twitch account to claim the correct account.
I confirmed Twitch does not honor the `prompt=consent` argument.
The improved messaging follows:
**User claims a Twitch account owned by someone else**
**User claims a Twitch account they have already claimed**
=> Improve messaging when claiming a claimed Twitch account

app/assets/stylesheets/legacy/application/publishers.sass, app/helpers/promos_helper.rb, app/views/promo_mailer/new_channel_registered_2018q1.html.slim, app/views/promo_mailer/promo_activated_2018q1_verified.html.slim, app/views/promo_registrations/_activated_verified.html.slim, app/views/promo_registrations/_active.html.slim, app/views/publishers/home.html.slim, config/secrets.yml, test/controllers/promo_registrations_controller_test.rb, test/mailers/promo_mailer_test.rb
Resolves #695 
* Remove PromosHelper#referral_url
* Rename PromosHelper#human_referral_url to #referral_url
* Only use the new #referral_url
* Up the width on the dashboard for the referral link since its longer
**Note:** We must add `https://` to the `BASE_REFERRAL_URL` env var when this is merged
cc @bbondy
Test Plan:
Tests
Security:
=> Use https:// for referral promo links always (emails + dashboard)

app/assets/stylesheets/legacy/application/publishers.sass, app/helpers/publishers_helper.rb, app/services/publisher_wallet_getter.rb, app/views/publishers/home.html.slim, config/locales/en.yml, lib/eyeshade/wallet.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb, test/helpers/publishers_helper_test.rb, test/models/publisher_test.rb, test/services/publisher_wallet_getter_test.rb, test/unit/wallet_test.rb
Closes https://github.com/brave-intl/publishers/issues/632. Previous PRs that addressed part of that ticket are https://github.com/brave-intl/publishers/pull/653 and https://github.com/brave-intl/publishers/pull/671.
Show the BAT balance for each verified channel.
* When the balance is unknown the `0.00` number would be replaced by the work `Unknown` in the same font/size.
* The promo screens are unchanged. I will confer with @nvonpentz on these.
* ~Introduces [Typhoeus](https://github.com/typhoeus/typhoeus) to allow the publisher wallet and channel requests to Eyeshade to run in parallel.~ I've removed typhoeus and moved to work to another branch. It requires some new testing infra (webmock doesn't support the easy path). WIP (works in dev) is at: …
=> Show balance by channel on publishers/home

app/views/publishers/new_auth_token.html.slim, config/locales/en.yml
Resolves #700 
Test Plan:
Tests
Security:
=> Add link for legacy youtube login on new_auth_token page

app/controllers/site_channels_controller.rb, app/models/channel.rb, config/locales/en.yml, test/controllers/site_channels_controller_test.rb
This adds a validation for a publisher trying to create a duplicate site channel to one already in process (verified channels were already prevented). The odd part of this PR is the validation is on the Channel, not on the SiteChannelDetails since it needs access to the Publisher which isn't available when the SiteChannelDetails haven't been saved.
Fixes #637 
Test Plan:
Tests
Security:
=> Prevent creating duplicate site channels for a publisher

app/views/application/_panel_flash_messages.html.slim, app/views/layouts/application.html.slim, test/controllers/site_channels_controller_test.rb
#709 to prevent site channel dupes referenced a flash selector which was replaced in #703.
This PR consolidates flash test selectors btwn panel flash and application layout flash, and fixes the test.
auditors: @lgebhardt @nvonpentz 
Test Plan:
Tests
Security:
=> Test: Update flash test selector and Fix SiteChannelsControllerTest

test/test_helper.rb
Use transactional tests instead of DatabaseCleaner non-capybara tests. This speeds up the full test suite on my system from 46s to 26s.
Use DatabaseCleaner with truncation for Capybara tests. The old setup was not correctly running the Capybara tests in a transaction due to the way Selenium runs in a separate thread. That allowed changes to leak and create the flappy tests, at least in the case of #676.
It remains to be seen if there are any more flappy tests.
Fixes #676
Test Plan:
Tests
Security:
=> Speed up tests and ensure Capybara tests don't alter the test data

app/assets/stylesheets/mailer.scss, app/views/layouts/mailer.html.slim, config/locales/en.yml
Resolves #532 
Resolves #533
For #533, The background color property was already set in Mailer.scss, and should display correctly, except gmail apparently filters out the css.
According to [stack overflow](https://stackoverflow.com/questions/9493922/gmail-html-email-background-color) there were a couple options:
* Wrap the body in a table with 100% width and height,
* Use inline css
I chose to use inline css.  We should test this on staging to make sure it works in gmail
Test Plan:
Tests
Security:
=> Resolve misc email UI problems

app/controllers/publishers_controller.rb, app/views/publishers/new_auth_token.html.slim, config/locales/en.yml
Fixes brave-intl/publishers#719
Test Plan:
Tests
Security:
=> Require the login email input to be populated

app/controllers/api/base_controller.rb, app/controllers/api/channels_controller.rb, app/controllers/api/owners_controller.rb, config/routes.rb, test/controllers/api/channels_controller_test.rb, test/controllers/api/owners_controller_test.rb
Implemented from slack conversations with @mrose17. @mrose17 should review before merging.
The `owner` `create` call creates verified Publishers and accepts `email`, `name`, and `phone` values. `phone` will be normalized. The created publisher will be email verified.
The `channel` `create` call creates a new site channel for the publisher specified in the route, and accepts the single `brave_publisher_id` value. After creating the new channel it is sent to eyeshade using the `SiteChannelDomainSetter`.
Payloads must be json.
Fixes #638
Test Plan:
Tests
Security:
=> Add Create API calls for Owners and Site Channels

app/assets/stylesheets/pages/site-channels.scss, app/views/site_channels/verification_dns_record.html.slim, app/views/site_channels/verification_github.html.slim, app/views/site_channels/verification_public_file.html.slim, app/views/site_channels/verification_support_queue.html.slim, app/views/site_channels/verification_wordpress.html.slim, config/locales/en.yml
Fixes #710 
Link takes you back to the dashboard. When you resume you will be back to the previous page.
Wordpress:
Hover state on link:
Test Plan:
Tests
Security:
=> Add "Complete Verification Later" button

app/javascript/packs/application.js, app/javascript/publishers/home.js, app/javascript/userMenu.js
Load the script to close the user menu in the application code and protect it from being used unless the user-menu element is on the page.
Fixes #726
Test Plan:
Tests
Security:
=> Move userMenu script to application and protect if menu isn't on page

app/mailers/publisher_mailer.rb, test/mailers/publisher_mailer_test.rb
Progresses towards #404 
As [anticipated](https://github.com/brave-intl/publishers/issues/404#issuecomment-353000312) by @ayumi, the debugging information I put in the `PublisherMailer#verify_email` method to address this [bug](https://sentry.io/brave-software/publishers-production-t2/issues/435856730/), does not work.  We're still getting this error so I've moved the publisher identifying information into the error message.
If there is a better way to do this, or better debugging information besides the `{publisher}.id` please comment.
Test Plan:
Tests
Security:
=> Correctly add sentry debugging information for PublisherMailer # verify_email

app/models/channel.rb, test/models/channel_test.rb
Fixes #724
Test Plan:
Tests
Security:
=> Allow verification status to be recorded despite validation errors

app/jobs/enqueue_site_channel_verifications.rb, app/models/site_channel_details.rb, test/controllers/api/tokens_controller_test.rb, test/fixtures/channels.yml, test/fixtures/site_channel_details.yml, test/jobs/enqueue_site_channel_verifications_test.rb, test/models/channel_test.rb, test/models/site_channel_test.rb
This will only enqueue channels for verification once the user has pressed Verify and the `verification_status` has been set to `starting`. In the event of a failure channels with a `verification_status` of `failed` will also be enqueued in order to try again. This will keep channels that have been paused from being verified. 
Fixes #731
Test Plan:
Tests
Security:
=> Stop autoverify until user presses Verify

README.md
The [twitch setup](https://github.com/brave-intl/publishers#twitch-api-setup)  incorrectly links to https://github.com/brave-intl/publishers/blob/staging/dev.twitch.tv/dashboard it should be https://dev.twitch.tv/dashboard
Test Plan:
Tests
Security:
=> Readme: Prefixed twitch setup link with https

app/controllers/publishers_controller.rb
Resolves #722 
Test Plan:
Tests
Security:
=> Use 'notice' instead of 'alert' for confirmation email resent notification

app/javascript/publishers/home.js, app/views/publishers/home.html.slim, config/locales/en.yml
Fixes https://github.com/brave-intl/publishers/issues/536
/cc @nvonpentz I pulled out the removed channel message from the locale then added to the element below, so I can set the flash message correctly inside the javascript. 
`.row.channel-row id=("channel_row_#{channel.id}") data-remove-message= t("shared.channel_removed")`
https://github.com/brave-intl/publishers/blob/8109d1ed6780a6c14a2f1cc674683de3244e3318/app/views/publishers/home.html.slim#L144
Test Plan:
Tests
Security:
=> Correct flash message on channel remove

app/assets/stylesheets/pages/site-channels.scss, app/views/site_channels/verification_wordpress.html.slim, config/locales/en.yml
Resolves #736 
This is a temporary measure until #711 fully addresses the verification UI problems.
Test Plan:
Tests
Security:
=> Add escape hatch for wordpress users to use DNS verification method

app/models/channel.rb, test/controllers/site_channels_controller_test.rb
Resolves #748 
Test Plan:
Tests
Security:
=> Allow two owners two create the same unverified site channel

app/assets/stylesheets/legacy/application/publishers.sass, app/assets/stylesheets/theme/panels.scss, app/controllers/publishers_controller.rb, app/views/layouts/publishers.html.slim, app/views/publishers/create_auth_token.html.slim, app/views/publishers/emailed_auth_token.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/publishers_controller_test.rb, test/features/log_in_test.rb, test/features/sign_up_test.rb
Resolves #574 
Test Plan:
Tests
Security:
=> Use a shared emailed_auth_token.html.slim for post sign_up and log_in

app/helpers/promos_helper.rb, app/views/promo_mailer/new_channel_registered_2018q1.html.slim, app/views/promo_mailer/promo_activated_2018q1_verified.html.slim, app/views/promo_registrations/_activated_verified.html.slim, app/views/promo_registrations/_active.html.slim, app/views/publishers/home.html.slim, config/secrets.yml, test/controllers/promo_registrations_controller_test.rb, test/mailers/promo_mailer_test.rb
Resolves #760 
* Create and use new method PromosHelper# https_referral_url
* Force twitter sharing to use https
Test Plan:
Tests
Security:
=> Fix https in referral promo share links

app/assets/stylesheets/legacy/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/javascript/publishers/home.js, app/jobs/upload_default_currency_job.rb, app/models/publisher.rb, app/services/publisher_default_currency_setter.rb, app/services/publisher_wallet_getter.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/helpers/publishers_helper_test.rb, test/jobs/upload_default_currency_job_test.rb, test/models/publisher_test.rb, test/services/publisher_default_currency_setter_test.rb, test/unit/wallet_test.rb
When the `default_currency` is successfully updated, a new `UploadDefaultCurrencyJob` will be triggered that will upload the change to eyeshade.
The UX has been tweaked slightly so that, for users with no default currency, a select option `— Select currency —` will appear as selected by default. This allows any other selection to trigger a change (since there’s no default chosen as was previously the case).
Fixes #767 
Test Plan:
Tests
Security:
=> Push default currency changes directly to eyeshade

app/assets/stylesheets/legacy/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/javascript/publishers/home.js, app/jobs/upload_default_currency_job.rb, app/models/publisher.rb, app/services/publisher_default_currency_setter.rb, app/services/publisher_wallet_getter.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/helpers/publishers_helper_test.rb, test/jobs/upload_default_currency_job_test.rb, test/models/publisher_test.rb, test/services/publisher_default_currency_setter_test.rb, test/unit/wallet_test.rb
* Fix use of dynamicEllipsis
Should use import rather than no-longer-existent global.
* Ensure that fetch polyfill is used
Instead of relying on global, ensure that `fetch` polyfill is used.
* Introduce PublisherDefaultCurrencySetter service
Updates a publisher’s default currency setting through a PATCH request to eyeshade.
* Introduce UploadDefaultCurrencyJob
Background job for uploading the default currency to eyeshade.
* Push default_currency updates to eyeshade
When the default_currency is successfully updated, an UploadDefaultCurrencyJob will be triggered that will upload the change to eyeshade.
The UX has been tweaked slightly so that, for users with no default currency, a select option `— Select currency —` will appear as selected by default. This allows any other selection to …
=> Release 2018-04-10

app/services/publisher_notifier.rb, config/secrets.yml
This will enable/disable eyeshade's use of the PublisherNotifier.
Resolves #775 
Test Plan:
Tests
Security:
=> Add should_send_notifications envar 

app/assets/stylesheets/legacy/application/publishers.sass, app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim, config/locales/en.yml
When no currencies are available, display a helpful message instead of failing.
Test Plan:
Tests
Security:
=> Display error message when currencies are unavailable

app/views/publishers/home.html.slim, config/routes.rb, test/features/publishers_home_test.rb
* Remove the ability to disable channels from UI
* Remove the delete route
* Temporarily comment out tests
Test Plan:
Tests
Security:
=> Disable channel removal (#798)

app/controllers/channels_controller.rb, app/views/publishers/home.html.slim, config/routes.rb, test/controllers/channels_controller_test.rb
Resolves #800 
* Allow the DELETE route
* Only allow unverified channels in ChannelsController#destroy
* Only allow unverified channels to have option to remove a channel in the UI
* Comment out test expecting the DeletePublisherChannelJob to run when a channel is deleted (only happens for verified channels)
* Add new test expecting unverified channels to be removed successfully
Test Plan:
Tests
Security:
=> Allow unverified channels to be removed

Gemfile, README.md, app/controllers/publishers_controller.rb, app/views/publishers/emailed_auth_token.html.slim, config/environments/development.rb, config/initializers/rack-attack.rb, config/locales/en.yml, docs/publishers-secrets.example.sh
Fixes issue where sometimes the reCAPTCHA is not shown and user instead sees 🎷
Supports rate limiting and reCAPTCHA in development and staging environments
Fixes #755, #791
Test Plan:
Tests
Security:
=> Add rate limiting and reCAPTCHA to resend_auth_email

app/jobs/clean_abandoned_site_channels_job.rb, app/jobs/clean_stale_uphold_data_job.rb
Resolves #808 
* In CleanStaleUoholdDataJob
* In CleanAbandonedSiteChannelJob
Test Plan:
Tests
Security:
=> Remove unhelpful Sentry calls

app/mailers/publisher_mailer.rb, test/mailers/publisher_mailer_test.rb
This adds to https://github.com/brave-intl/publishers/pull/806.  `PublisherMailer#verified_invalid_wallet` did not include the extra param which the `PublisherNotifier` sends. 
The tests missed this because we only check if the email is enqueued, not delivered:
https://github.com/brave-intl/publishers/blob/40f492594f02bac69762acdc20670512b136efdc/test/controllers/api/channels_controller_test.rb#L86-L88
We aren't able to update the test to see if the email is delivered because the mailing is asynchronous (`deliver_later`), and we cannot guarantee the mail will already delivered at the time the assertion executes:
https://github.com/brave-intl/publishers/blob/40f492594f02bac69762acdc20670512b136efdc/app/services/publisher_notifier.rb#L21-L24
Test Plan:
Reviewer …
=> Give PublisherMailer#verified_invalid_wallet an extra param

app/assets/stylesheets/legacy/application/publishers.sass, app/controllers/publishers_controller.rb, app/helpers/publishers_helper.rb, app/javascript/publishers/home.js, app/jobs/disconnect_uphold_job.rb, app/models/publisher.rb, app/services/publisher_wallet_disconnector.rb, app/views/publishers/_disconnect_uphold_modal.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml, config/routes.rb, test/controllers/publishers_controller_test.rb, test/helpers/publishers_helper_test.rb, test/jobs/disconnect_uphold_job_test.rb, test/models/publisher_test.rb, test/services/publisher_wallet_disconnector_test.rb
This introduces a new UX and new capabilities to the Uphold panel on the dashboard.
A status message and status change link now always appear at the top of the panel.
When connected, the user now has the option to disconnect:
This link will raise the following confirmation prompt:
If the user chooses to disconnect, Uphold will show as "Not Connected", and eyeshade will be notified:
If the user then reconnects to Uphold, the "Connecting" status will pulse until a connection has been confirmed:
If communication problems occur and the browser is unable to get an updated status, the following timeout message will eventually appear: 
Closes #133 
/cc @nvonpentz @jenn-rhim 
Test Plan:
Tests
Security:
=> Allow Uphold account to be disconnected / changed

README.md, config/secrets.yml
Fix #608
This lets you run tests and the app without special environment variables.
Test Plan:
Tests
Security:
=> Provide default UPHOLD_AUTHORIZATION_ENDPOINT

app/models/publisher.rb, test/models/publisher_test.rb
Resolves #847 
Test Plan:
Tests
Security:
=> Fix publisher channel details association

app/models/publisher.rb, test/models/publisher_test.rb
When eyeshade responds that Uphold authorization / reauthorization is needed, the `uphold_verified` status should not be revoked immediately, because this status can be resolved either by a user or by Uphold without involving Brave. Instead `:reauthorization_needed` should be viewed as a a substate of `:verified`.
This approach also fixes the case in which a user has explicitly disconnected their Uphold account. They will always be shown a status of “Not connected” and never be shown “Connection problems”.
This PR also removes the now unused `Publisher#uphold_complete?` method.
Fixes #841
Test Plan:
Tests
Security:
=>  Resolve Uphold disconnection / reauthorization issues

app/controllers/publishers_controller.rb, app/jobs/sync_publisher_promo_stats_job.rb, app/services/publisher_promo_stats_fetcher.rb, test/jobs/sync_publisher_promo_stats_job_test.rb
Resolves #821 
* Use SyncPublisherPromoStatsJob in `PublishersController#home` to make stats refresh async
* Adjust SyncPublisherPromoStatsJob to be able to be used for a single publisher
* Adjust SyncPublisherPromoStatsJobTest
* Remove `publisher` from sentry call in PublisherPromoStatsFetcher
Test Plan:
Tests
Security:
=> Update promo stats sync logic

app/jobs/sync_publisher_statement_job.rb, app/services/publisher_statement_syncer.rb, test/services/publisher_statement_syncer_test.rb
If a publisher’s statement is returned as an empty string, then we don’t want to notify the publisher that it is ready.
We need to check that `contents.present?` instead of just the truthiness of `contents`. In this way, the same logic is applied in both PublisherStatementSyncer and SyncPublisherStatementJob for evaluating the presence of a statement’s contents.
This fixes an error that resulted because eyeshade was returning statement URLs that required a redirect to fetch.
Test Plan:
Tests
Security:
=> Better handle scenarios in which a publisher statement is empty

config/secrets.yml
To use Eyeshade in dev currently requires editing out the secrets.yml `dev.api_eyeshade_offline` which is not obvious. This fixes it so if you specify env API_EYESHADE_BASE_URI it will work as expected, and otherwise fallback to offline mode.
Test Plan:
Tests
Security:
=> Dev: Easier to use local Eyeshade

config/secrets.yml
Secrets must be overridable to allow for proper testing in dev environment. This change favors `ENV` vars but still falls back to defaults if custom settings have not been configured.
Test Plan:
Tests
Security:
=> Allow ENV vars to override defaults for dev env

app/helpers/publishers_helper.rb, app/javascript/publishers/statements.js, app/views/publishers/home.html.slim, app/views/publishers/statements.html.slim, test/controllers/publishers_controller_test.rb
* Ensure that the short date (`Jun` instead of `June`) will always be used for statements
* Track statement downloads with piwik
* Converts the "Dashboard" title on the home page to a link for consistency with the statements page
Test Plan:
Tests
Security:
=> Fix minor issues with new statements page

.travis.yml, app/javascript/example.js, karma.conf.js, package.json, test/javascript/example-test.js, yarn.lock
Enables unit testing of JS modules, in isolation from the app itself.
An `example.js` module and `example-test.js` are included.
The karma test server can be started with `yarn run start`.
A full headless test run can be run with `yarn test`.
Travis has been updated to run `yarn test`.
Test Plan:
Tests
Security:
=> Enable JS unit testing with karma + qunit

app/controllers/totp_registrations_controller.rb, app/jobs/clean_stale_uphold_data_job.rb, app/services/promo_registrar.rb, app/services/publisher_promo_token_generator.rb, app/services/site_channel_verifier.rb
Resolves #932 
Test Plan:
Tests
Security:
=> Obfuscate publisher information in slack and papertrail logs

app/models/json_builders/identity_json_builder.rb
Removes hyphens in first two sections, which are under Publishers control and not used
Escapes the last hyphen as a valid character for twitch or youtube ids
Fixes #919 
Test Plan:
Tests
Security:
=> Handles unescaped hyphens in regex

test/controllers/admin/publishers_controller_test.rb
Stop overriding the `remote_ip` method and set the ip in the header.
Fixes #968
Test Plan:
Tests
Security:
=> Fix flappy test

app/assets/stylesheets/pages/home.scss, app/helpers/publishers_helper.rb, app/views/publishers/home.html.slim, config/locales/en.yml, test/helpers/publishers_helper_test.rb
Note, I display the date as "July 8th" instead of "July 8". I can change this back if that's not desired.
Fixes #947, #938
Test Plan:
Tests
Security:
=> Auto calculated Next Deposit Date

app/models/json_builders/identity_json_builder.rb, test/controllers/api/public/channels_controller_test.rb
Closes #977
Test Plan:
Tests
Security:
=> Do a lookup on multiple fields for twitch channels

app/models/json_builders/identity_json_builder.rb, test/controllers/api/public/channels_controller_test.rb
2. Properly display SLD, RLD, and QLD by checking against PublicSuffix
Closes #978
Test Plan:
Tests
Security:
=> 1. Always show exclusion even if the domain is not a publisher

app/services/site_channel_host_inspector.rb
Adds the domain to the logs to aid in troubleshooting host inspection errors.
Doesn't fix an issue, but should help with #253 
Test Plan:
Tests
Security:
=> Log brave_publisher_id for PublisherHostInspector failures

Gemfile, Gemfile.lock, app/models/login_activity.rb, app/models/publisher.rb, config/initializers/login_activities.rb, db/migrate/20180613134700_create_login_activities.rb, db/schema.rb, test/controllers/publishers_controller_test.rb, test/fixtures/login_activities.yml, test/models/login_activity_test.rb
This only records the logins and user-agent details. A follow on feature could make use of this data in the admin dashboard, or for analytics purposes.
Fixes #946
Test Plan:
Tests
Security:
=> Track successful logins with browser details

app/models/json_builders/identity_json_builder.rb, test/controllers/api/public/channels_controller_test.rb
Closes #993
(2) Handle channels not present in our *_channel_details tables.
Closes #992.
Test Plan:
Tests
Security:
=> (1) Handle domains marked for exclusion

app/controllers/admin/publishers_controller.rb, app/models/publisher.rb, config/routes.rb
Resolves #974 
This PR uses a single search bar for searching by publisher and channel. 
I also removed an unused route.
Test Plan:
Tests
Security:
=> Allow admins to search by channel

app/views/two_factor_registrations/index.html.slim
Resolves #991 
- [] Added/updated tests for this change (for new code or code which already has tests).
- [] Addressed or ignored all brakeman warnings
Test Plan:
Tests
Security:
=> Enable U2F for all users

app/assets/stylesheets/admin/style.scss, app/controllers/admin_controller.rb, app/models/channel.rb, app/services/site_channel_verifier.rb, app/views/admin/publishers/show.html.slim, config/routes.rb, config/secrets.yml, test/controllers/admin/publishers_controller_test.rb, test/controllers/channels_controller_test.rb, test/helpers/channels_helper_test.rb, test/models/channel_test.rb
Resolves #1005 
Before approval
After approval
Test Plan:
Tests
Security:
=> Allow admins to approve restricted site channels

app/helpers/publishers_helper.rb, app/models/publisher.rb, app/views/publishers/_confirm_default_currency_modal.html.slim, app/views/publishers/home.html.slim, test/features/publishers_home_test.rb
In the case of a connection issue between publishers and eyeshade, the publisher’s wallet will not be present. However, the dashboard should still be viewable and “BAT unavailable” should be displayed.
Fixes #1039
/cc @yachtcaptain23 @nvonpentz 
Test Plan:
Tests
Security:
=> Ensure that dashboard can be loaded even if wallet cannot

app/assets/stylesheets/admin/style.scss, app/views/admin/publishers/show.html.slim
This PR moves the statement section into the same row as the publisher information.
Now:
After this PR:
Test Plan:
Tests
Security:
=> Move statements into publisher info section on admin dashboard

db/migrate/20180628164707_add_object_changes_to_versions.rb, db/schema.rb
This allows easier comparison for between versions of an instance of a model.
Usage:
```
irb(main):007:0> publisher.versions.last.changeset
=> {"id"=>[nil, "7e916581-6679-40dd-86c0-175277ab2a5c"], "pending_email"=>[nil, "nickvonpentz@gmail.com"], "created_at"=>[nil, 2018-06-28 16:58:41 +0000], "updated_at"=>[nil, 2018-06-28 16:58:41 +0000]}
```
Resolves #1034 
Test Plan:
Tests
Security:
=> Add object_changes column to versions

app/controllers/admin/publishers_controller.rb, app/models/publisher.rb, app/views/admin/publishers/index.html.slim, test/fixtures/publisher_status_updates.yml, test/fixtures/publishers.yml, test/models/publisher_test.rb
Resolves #1029 
Test Plan:
Tests
Security:
=> Allow admins to filter publishers by suspended status

app/views/layouts/site_channels.html.slim, app/views/site_channels/verification_wordpress.html.slim, config/locales/en.yml, test/features/site_channel_verification_test.rb
Resolves #1022 
Test Plan:
Tests
Security:
=> Replace Cancel button with Choose Different Verification Method on verification pages

app/javascript/publishers/home.js, app/views/publishers/home.html.slim, test/features/publishers_home_test.rb
This prevents the default currency modal from automatically appearing.  This also removes the link to change default currency which would normally trigger the default currency modal.
Test Plan:
Tests
Security:
=> Prevent default currency modal from appearing

app/assets/stylesheets/admin/style.scss
Before this PR
After this PR
Test Plan:
Tests
Security:
=> Add z-index to admin top nav

config/locales/en.yml
Brave supports U2F now, so this PR adds Brave to the list of browsers we instruct publishers to use.
Test Plan:
Tests
Security:
=> Add Brave to list of browsers that support U2F

app/services/publisher_wallet_getter.rb, test/controllers/api/tokens_controller_test.rb, test/fixtures/channels.yml, test/fixtures/publishers.yml, test/fixtures/site_channel_details.yml, test/models/site_channel_test.rb, test/services/publisher_wallet_getter_test.rb
Resolves #1058 
Resolves https://github.com/brave/browser-laptop/issues/14658
Test Plan:
Tests
Security:
=> Only request individual balances for verified channels

config/locales/en.yml
=> Fix missing translation in suspend_publisher email

README.md, app/services/channel_stats_services/youtube_channel_stats_service.rb
to determine whether to perform yt stats offline.  Also Update README with instructions to get youtube API keys.
Cleans up #1082.
Test Plan:
Tests
Security:
=> Use presence of YOUTUBE_API_KEY instead of API_TWITCH_BASE_URI

app/services/channel_stats_services/youtube_channel_stats_service.rb
Related to #1082 
The SyncChannelStatsJob fails on staging because some some of the youtube channels that we attempt to collect stats for do not actually exist (they are only google accounts - with no youtube channel), and thus return an error.  In this case we should just return nil, so the job can continue for the other youtube channels.
This occurs for 'non existent' youtube channels. That is, google accounts with no
associated youtube channels.
Test Plan:
Tests
Security:
=> Rescue Yt::Errors::NoItems errors in YoutubeChannelStatsService

app/services/publisher_balance_getter.rb, app/services/publisher_wallet_getter.rb, test/services/publisher_balance_getter_test.rb, test/services/publisher_wallet_getter_test.rb
Refs #1095 
* Look for "account_id" instead of "account" in /balances response
* Specify Faraday::FlatParamsEncoder so params with the same name are not lost (ie. with '&account=')
* Ensure we do not sum over the owner balance if given
* Update tests
Test Plan:
Tests
Security:
=> Update PublisherBalanceGetter and PublisherWalletGetter

app/controllers/admin_controller.rb, app/controllers/publishers_controller.rb
In Rails 5 `render nothing` is deprecated, and we should use `head` instead according to this [stack overflow](https://stackoverflow.com/questions/4632271/render-nothing-true-returns-empty-plaintext-file)
Resolves #1083
Test Plan:
Tests
Security:
=> Replace render nothing with head

app/helpers/channels_helper.rb, app/views/admin/payout_reports/index.html.slim
Resolves #1122 
Resolves #1123 
* Fix missing translation
* Display payout report in BAT, not probi
Test Plan:
Tests
Security:
=> Resolve misc frontend issues

app/jobs/generate_payout_report_job.rb, app/models/twitch_channel_details.rb, app/services/publisher_balance_getter.rb, app/views/publishers/home.html.slim
Resolves #1134 
* Add TwitchChannelDetails#author_identifier
* Use #author_identifier to replace other ways of writing 'twitch#author'
* Look for twitch channel balances using the twitch#author identifier to display on dashboard
Test Plan:
Tests
Security:
=> Ensure twitch per channel balances are displayed

app/services/site_channel_verifier.rb
=> Don't use cache when attempting to use the SiteVerifier. Closes #1152

app/views/admin/payout_reports/index.html.slim
Fix #1142 
Test Plan:
Tests
Security:
=> Only display payout reports with non nil amounts

app/models/site_channel_details.rb, test/models/site_channel_test.rb
Resolves #1148 
Only enqueue site channels for verification that are:
* Not verified
* Have a verification method
* Were updated as recently
Test Plan:
Tests
Security:
=> Update criteria for EnqueueSiteChannelVerifications

app/controllers/admin/publishers_controller.rb
Resolves #1107 
Admins will be able to search with or without the channel/owner prefixes.
Test Plan:
Tests
Security:
=> Allow admins to search for publishers by publisher.id and channel.id

app/services/publisher_wallet_getter.rb, lib/eyeshade/balance.rb, lib/eyeshade/wallet.rb, test/controllers/publishers_controller_test.rb, test/helpers/publishers_helper_test.rb
The last settlement balance returned by eyeshade in the /wallet response is the amount that was settled, so it already has taken fees into account.  However, when we display a publishers last settlement balance we are applying the fee twice.
This happens in two places:
1. When we calculate the last settlement balance with ruby in PublishersHelper#publisher_humanize_last_settlement and PublishersHelperpublisher_converted_last_settlement
2.  When the default currency is changed, we us JS to get the latest balance and update the DOM. 
since we use `probi` instead of `probi_before_fees` in the wallet JSON that's sent to the dashboard.
https://github.com/brave-intl/publishers/blob/08928c4c12cda5cd0d0d5228ef44ec4f27056fed/app/models/json_builders/wallet_json_builder.rb#L47-L49
This might lead …
=> Do not apply fee twice to last settlement balance

Aptfile, bin/wkhtmltopdf-with-xvfb.sh
Use wkhtmltopdf binary name instead of path to binary and add libxcomposite1 to Aptfile
Test Plan:
Tests
Security:
=> Fix wkhtmltopdf on heroku

config/sidekiq.yml
From once every three hours to once a day.
Test Plan:
Tests
Security:
=> Lower frequency of SyncPublisherPromoStatsJob

app/controllers/publishers/site_banners_controller.rb
Closes #1237
Test Plan:
Tests
Security:
=> Prevent users from adding site banners if they're not in the whitelist

app/assets/stylesheets/admin/pages/unattached_promo_registrations.scss, app/controllers/admin/unattached_promo_registrations_controller.rb, app/views/admin/unattached_promo_registrations/index.html.slim, test/controllers/admin/unattached_promo_registrations_controller_test.rb
This PR allows the dashboard to load in the case when the last stats updated was not stored in redis.  This value is only set by the AdminSyncPromoStats job, which can only complete after a code has been created.  This change will simplify deploying the code because we will not need to create a code via rails console, then run the AdminSyncPromoStats job via rails console before we can use the feature.
Also this PR restricts the number of codes that an admin can create to 50 per click.  Currently it is unbounded and thus admins have the ability to accidentally crash the system and enter huge amounts of data directly into two databases.
Lastly, this PR also iterates on the infinity codes admin dashboard frontend.  After this PR it will look like:
Test Plan:
Reviewer …
=> Prepare infinity code dashboard for release

app/models/publisher.rb, app/models/twitch_channel_details.rb, app/models/twitter_channel_details.rb, app/models/youtube_channel_details.rb, app/services/publisher_statement_getter.rb, app/services/publisher_transactions_getter.rb, test/models/publisher_test.rb, test/services/publisher_statement_getter_test.rb
Resolves https://github.com/brave-intl/publishers/issues/1273
* Replace account identifier with "All" if the 'channel' is an owner id
* Add the account prefixes as constants to models
* Add Publisher#find_by_owner_identifier
Test Plan:
Tests
Security:
=> Modify PublisherStatementGetter to accept txs where the 'channel' is an owner id

app/services/promo_registrar.rb, app/services/promo_registration_getter.rb, app/views/publishers/home.html.slim, test/services/promo_registrar_test.rb, test/services/promo_registration_getter_test.rb
Resolves https://github.com/brave-intl/publishers/issues/1291
Blocked by https://github.com/brave-intl/vault-promo-services/pull/56
More information found in https://github.com/brave-intl/vault-promo-services/pull/56.
* Update the url used by the PromoRegistrationGetter - this ensures
the referral code owned by the channel_id supplied is returned
* No longer update the referral server when a channel has changed
owners via the PromoRegistrationsGetter
* Allow publishers to remove verified channels
* Remove dead tests
Test Plan:
Tests
Security:
=> Update promo registration flow for channels that have previously registered

app/services/promo_registrar.rb, app/services/promo_registration_getter.rb, app/views/publishers/home.html.slim, test/services/promo_registrar_test.rb, test/services/promo_registration_getter_test.rb
* Update promo registration flow for channels that have previously registered
* Update the url used by the PromoRegistrationGetter - this ensures
the referral code owned by the channel_id supplied is returned
* No longer update the referral server when a channel has changed
owners via the PromoRegistrationsGetter
* Allow publishers to remove verified channels
* Remove dead tests
* Improve PromoRegistrar code style
* PromoRegistrar#register_channel now returns a hash containing
the referral_code, and whether or not the referral server
should be updated with the new owner
* Add test to cover new/existing PromoRegistrar logic
* More style changes
Test Plan:
Tests
Security:
=> Release 2018-10-31 (2)

app/assets/stylesheets/pages/home.scss, app/views/promo_registrations/_activate.html.slim, app/views/publishers/home.html.slim, config/locales/en.yml
Resolves #1215 
Remove references to 'limited time promo' and update button colors and text.  I did not update the polygon image in the background, but can figure that out if we believe it's important or high priority.
Dashboard promo panel:
Activate promo screen:
Test Plan:
Tests
Security:
=> Update referral messaging on dashboard and on activate screen

app/controllers/admin/unattached_promo_registrations_controller.rb, app/controllers/publishers_controller.rb, app/jobs/sync/channel_promo_registrations_stats_job.rb, app/jobs/sync/channel_stats_job.rb, app/jobs/sync/publisher_promo_stats_job.rb, app/jobs/sync/unattached_promo_registrations_stats_job.rb, app/jobs/sync_channel_promo_registrations_stats_job.rb, app/jobs/sync_unattached_promo_registrations_stats_job.rb, app/models/promo_registration.rb, app/services/promo_registrations_stats_fetcher.rb, app/services/promo_report_generator.rb, config/sidekiq.yml, test/jobs/sync/publisher_promo_stats_job_test.rb, test/models/promo_registration_test.rb, test/services/promo_registrations_stats_fetcher_test.rb
Implements the first stage of #1337.
This PR adds a background job to save all channel referral stats to the promo registrations table.  Previously stats were saved to the publisher.  This does not change from which table the referral stats are sourced to display to the user, they will still be sourced from the `promo_stats_2018q1` column in the publishers table.  But when we do switch to the stats column in the promo_registrations table, this will ensure that the data will already be there.
Test Plan:
Resolves 
Tests
Security:
=> Save referral stats for channel owned codes to the promo registrations table

app/controllers/publishers_controller.rb, app/models/ability.rb, app/models/publisher.rb
Basis for the forthcoming `Partner` role as mentioned in @mandar-brave's v1.1 
Using the console `Publisher` can be set to `Partner` like so:
```ruby
record.role = "partner"
record.save
```
`partner` will not have access to admin privileges.
Closes #1327
=> Partner Role

app/controllers/publishers_controller.rb, app/helpers/promos_helper.rb, app/models/promo_registration.rb, app/models/publisher.rb, app/services/promo_registrar.rb, app/views/publishers/home.html.slim, config/sidekiq.yml, db/migrate/20181115160802_add_publisher_to_promo_registration.rb, db/schema.rb, lib/tasks/database_updates/add_publisher_id_to_existing_channel_promo_registrations.rake, lib/tasks/database_updates/set_default_promo_registration_kind.rake, test/fixtures/channels.yml, test/fixtures/promo_registrations.yml, test/fixtures/publishers.yml, test/fixtures/site_channel_details.yml, test/fixtures/youtube_channel_details.yml, test/helpers/promos_helper_test.rb, test/mailers/promo_mailer_test.rb, test/models/promo_registration_test.rb, test/services/promo_registrar_unattached_test.rb
Part two of #1337.  Blocked until https://github.com/brave-intl/publishers/pull/1338 is in production for a couple days to propagate stats to PromoRegistration#stats.
This makes promo registrations polymorphic.  So a channel promo_registration now belongs to one channel and one publisher. A publisher has many promo registrations.
Now we can do things like `publisher.promo_registrations` to get all the promo registrations associated with the publisher. This allows us to easily sum the stats for all promo registrations belonging to a publisher and display them to the publisher.
Part 3 of #1337 will include removing `promo_stats_2018q1q1` from the publishers table and other clean up.
Test Plan:
Tests
Security:
=> Allow publishers to own referral codes, do not display publisher#promo_stats_2018q1

app/controllers/publishers_controller.rb, config/locales/en.yml
Our form was raising a 500 in production when the `@publisher` was nil.
=> Ensure publisher isn't nil when requesting new auth

app/services/promo_registrations_stats_fetcher.rb, test/services/promo_registrations_stats_fetcher_test.rb
**NOTE** This PR is directly against master.
We are unable to successfully request/save the stats from the promo server because the request URI is too long.  It's too long because each referral code is supplied as a query string parameter,  e.g.
```
GET /api/2/promo/statsByReferralCode?referral_code=PRO123&referral_code=PRO456
```
This PR updates the PromoRegistrationsStatsFetcher to make the request in batches of 1000, so each URI is ~31 kb.  According to [stack overflow](https://stackoverflow.com/questions/32763165/node-js-http-get-url-length-limitation) the limit is 80kb, so we should be well under.
This PR is directly against master since https://github.com/brave-intl/publishers/pull/1350 was merged in to staging.  Since that was merged in to staging, we can't merge `master <- …
=> Request referral code stats in batches of 1000

app/services/promo/unattached_registrar.rb, app/services/promo/unattached_registration_status_updater.rb, config/secrets.yml, test/services/promo/unattached_registration_status_updater_test.rb
Resolves #1393 
Fixed a flappy test, and also makes the unattached codes have an offline mode when no promo server is attached.
Test Plan:
Tests
Security:
=> Fix promo flappy test and add offline mode for unattached codes

lib/tasks/database_updates/backfill_potential_payments.rake
Testing on staging found this edgecase.  If a report has no payments, we don't need to create any PotentialPayments.
Test Plan:
Tests
Security:
=> Do not attempt to backfill potential payments for an empty legacy report

app/models/json_builders/payout_report_json_builder.rb, test/models/potential_payment_test.rb
Noticed this was missing on staging as well.
This also includes an unrelated test to ensure potential payments are not deleted when their corresponding publisher or channel's are destroyed.
Test Plan:
Tests
Security:
=> Include URL in payout report json

app/views/admin/payout_reports/index.html.slim
UI says the unit is BAT but the unit is probi.  Changing to display in BAT rounded to two decimal places.
Test Plan:
Tests
Security:
=> Display total payout report stats in BAT not probi

app/controllers/admin/payout_reports_controller.rb, app/jobs/update_payout_report_contents_job.rb, app/models/payout_report.rb, app/views/admin/payout_reports/index.html.slim, config/routes.rb, config/sidekiq.yml, db/schema.rb, lib/tasks/database_updates/backfill_potential_payments.rake, test/controllers/admin/payout_reports_controller_test.rb, test/jobs/update_payout_report_contents_job_test.rb, test/tasks/backfill_potential_payments_test.rb
Resolves #1408 
This adds a UpdatePayoutReportContentsJob that refreshes the payout report contents.  Admins now can trigger this job via the admin dashboard.
This also makes some changes to the backfill_potential_payments script.  Namely we do not backfill for non-legacy reports, and we do not terminate the script if a potential payment is.  The values on the dashboard are advisory only, as the accounting is Eyeshade's responsibility.
Test Plan:
Tests
Security:
=> Refresh payout report contents in the worker process

app/views/admin/unattached_promo_registrations/index.html.slim
Default checked
Closes #1395
Test Plan:
Tests
Security:
=> Auto-select end-date for tomorrow to cover timezone issues

app/controllers/admin/publishers_controller.rb, app/controllers/concerns/search.rb, test/controllers/admin/publishers_controller_test.rb
I rewrote the query that was originally there because it was very unoptimized. 
Before: `cost=24226.35..26190.97 rows=20150 width=749`
After: `cost=17396.52..17446.89 rows=20150 width=749`
It's now 40% faster
Closes #1270
=> Search by referral code

Gemfile, Gemfile.lock, package.json
The webpacker version was moved to `devDependencies` which isn't installed. 
The only problem left is that the `webpack-dev-server` doesn't work. We can fix this by downgrading to an appropriate version. Or waiting until webpack v4 comes out.
```
~/r/publishers ❯❯❯ wds                                                                                                                                                                                                                   ✘ 130 
/Users/cory/repos/publishers/node_modules/webpack-dev-server/bin/webpack-dev-server.js:363
throw err;
^
TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
at addHooks (/Users/cory/repos/publishers/node_modules/webpack-dev-server/lib/Server.js:114:49)
at new Server …
```
=> Fix webpack deploy

app/controllers/publishers_controller.rb, app/javascript/packs/banner_editor.jsx
Improves the flow for users in the case where they have:
`Not added any channels but created a default banner`
`Then have added their first channels`
=> Move no-channels edge case logic from UI to server

app/services/site_channel_verifier.rb
Currently there are >23,000 events in Sentry for this error. Since we're aware of it, might as well capture it and at least do something about it 
https://sentry.io/brave-software/publishers-production-t2/issues/676099431/?query=is%3Aunresolved
=> Resolve Dnsruby::ServFail

app/services/promo/publisher_channels_registrar.rb
We're currently seeing the error "Validation failed: Referral code has already been taken"
In order to determine what is occurring I propose we add a little bit more logging and capture these exceptions
=> Log additional attributes in channel_registrar

app/services/promo/registration_stats_report_generator.rb, test/services/promo/registration_stats_report_generator_test.rb
This is a small change that ensures empty events and real events, when combined, are still sorted by date.
Test Plan:
Tests
Security:
=> Ensure empty events and real events are sorted by date

app/services/promo/registration_stats_report_generator.rb
Resolves https://sentry.io/brave-software/publishers-staging/issues/829492362/?query=is%3Aunresolved
Tested locally with copy of promo staging db.
Test Plan:
Tests
Security:
=> Use empty string for string comparison instead of nil when grouping geo reports by date

Procfile.dev, app/jobs/enqueue_publishers_for_payout_job.rb
This way the job can be run on the time schedule set in sidekiq.yml.
Also add the heavy worker to the dev Procfile.
Resolves https://sentry.io/brave-software/publishers-production-t2/issues/827898110/?query=is%3Aunresolved
I tested this locally and ensured that payout reports set off manually do not send notifications if the `should_send_notifications` box isn't checked.
Test Plan:
Tests
Security:
=> Give EnqueuePublishersForPayoutJob default arguments

app/services/payout_report_publisher_includer.rb, test/services/payout_report_publisher_includer_test.rb
Fix #1510 
Test Plan:
Tests
Security:
=> Ensure emails are sent to publishers with only contributions but no wallet address

app/controllers/admin/payout_reports_controller.rb, test/controllers/admin/payout_reports_controller_test.rb
Refreshing the payout report json is a long process that likely to time out.  This should be done via the 'refresh payout report json' button on the admin dashboard.
When https://github.com/brave-intl/publishers/pull/1409/files was implemented, I forgot to remove this line.
Test Plan:
Tests
Security:
=> Do not update payout report json when downloading payout reports

base.yml, docker-compose.yml
Sometime recently the rates service within the bat-ledger repo was moved to it's own service, but we haven't yet updated our docker-compose implementation which depends on these rates.  You might get an error "config.currency.access_token: undefined" as a result.
This PR adds those environment variables into the docker-compose setup.  Since bat-ratios has not been dockerized, we need to use the staging url for development.  This will require environment variables that you will need to get from another dev.
Test Plan:
Tests
Security:
=> Update docker compose set up to work with bat-ratios

app/controllers/admin/payout_reports_controller.rb, app/jobs/enqueue_publishers_for_payout_job.rb, app/jobs/enqueue_publishers_for_payout_notification_job.rb, app/jobs/include_publisher_in_payout_report_job.rb, app/services/payout_report_publisher_includer.rb, app/views/admin/payout_reports/index.html.slim, config/routes.rb, config/sidekiq.yml, test/controllers/admin/payout_reports_controller_test.rb, test/jobs/enqueue_publishers_for_payout_notification_job_test.rb, test/services/payout_report_publisher_includer_test.rb
Resolves #1528 
This pr creates a new job, EnqueuePublishersForPayoutNotification, which only sends notifications and does not create potential payments.  EnqueuePublisherForPayout no longer sends notifications.
EnqueuePublishersForPayoutNotification will run on the 23rd of every month, giving publishers about a week to reconnect before the payout report is created on the 1st.
Admins can also trigger notifications manually:
Test Plan:
Tests
Security:
=> Separate publisher notification from payout report generation

config/locales/en.yml
This answer on Stack Overflow says that even if you rename a plugin the url will stay the same. https://stackoverflow.com/a/33139685
Until we test https://github.com/brave-intl/brave-payments-verification/pull/13 we can have the URLs be the previous ones
=> Wordpress URL

app/controllers/admin/publishers_controller.rb, app/controllers/concerns/search.rb, app/mailers/publisher_mailer.rb, app/models/publisher.rb, app/services/payout_report_publisher_includer.rb, app/views/admin/publishers/show.html.slim, app/views/publisher_mailer/uphold_member_restricted.html.slim, config/locales/en.yml, db/migrate/20190116001651_add_uphold_id_to_publisher.rb, db/schema.rb, lib/eyeshade/wallet.rb, test/controllers/admin/payout_reports_controller_test.rb, test/services/payout_report_publisher_includer_test.rb
Changed the following
* We can actually search by a UUID now
* We can search for identical Uphold accounts
* Rewrote the `payout_report_publisher_includer_test` to handle more permutations of statuses
* Sorting by Last Signed In will show the null values last so we can see who was the most recent signed in user
=> Expose Uphold Status and ID

app/helpers/promos_helper.rb, app/services/promo/registration_stats_report_generator.rb, test/services/promo/registration_stats_report_generator_test.rb
Resolves #1540 
This will now automatically calculate the install/download ratio and 30 days/install ratio for each referral code within date period given for standard reports and for each referral code x country pair for geo reports.
Test Plan:
Tests
Security:
=> Include install/download and 30 days/eligible install in referral reports

package.json, yarn.lock
🔨 Fixes our builds! 🔧
```sh
~/r/publishers ❯❯❯ yarn audit
yarn audit v1.13.0
0 vulnerabilities found - Packages audited: 95118
✨  Done in 1.84s.
```
=> Upgrade Jest to remove security vulnerabilities

app/models/json_builders/payout_report_json_builder.rb, test/models/json_builders/payout_report_json_builder_test.rb
I accidentally used snake case for uphold id.
Test Plan:
Tests
Security:
=> Use camel case for payout report json

app/models/promo_registration.rb
Resolves #1655
Test Plan:
Tests
Security:
=> PromoRegistration may not have a publisher_id associated with it

config/environments/production.rb, config/environments/staging.rb, config/secrets.yml
=> Use api key instead of sendgrid account credentials for transactional emails for prod

app/services/payout_report_publisher_includer.rb, test/services/payout_report_publisher_includer_test.rb
Resolves #1676 
Test Plan:
Tests
Security:
=> Don't return early from PayoutReportPublisherIncluders if publisher is suspended

app/controllers/admin/publishers_controller.rb, app/models/channel.rb, app/models/publisher.rb, app/views/admin/publishers/index.html.slim, app/views/admin/publishers/show.html.slim, test/models/channel_test.rb, test/models/publisher_test.rb
Resolves #1674 
* Enforce consistent capitalization
* Hide suspended and reauthorization needed unless those are true
Test Plan:
Tests
Security:
=> Clean admin publisher pages

app/javascript/views/referrals/referralsCard/ReferralsCard.tsx, app/javascript/views/referrals/referralsHeader/ReferralsHeader.tsx, app/javascript/views/referrals/referralsInformation/ReferralsInformation.tsx, app/services/promo/owner_registrar.rb
* Fixes issue partners were seeing in creating campaigns and promo registrations
* Also updates the copy link feature to use the correct url 
* Bug was related to the false assumption that the promo server would provide stats `{0, 0, 0}` for a new promo_registration, this is not the case. Rewrote code to handle this. 
* On a staging environment (or environment with promo-server running) login as a partner
* Navigate to `Referrals`
* Try creating Campaigns and Promo Registrations, codes should appear.
=> Partner promo registration bugfixes 🏷 

.postcssrc.yml, package.json, yarn.lock
Thin out package.json
Test Plan:
Tests
Security:
=> Remove postcss-cssnext from .postcssrc.yml

app/controllers/publishers_controller.rb, app/javascript/wallet.js, app/javascript/wallet.test.tsx, app/jobs/create_uphold_cards_job.rb, app/services/publisher_wallet_getter.rb, lib/eyeshade/wallet.rb, test/controllers/publishers_controller_test.rb, test/helpers/publishers_helper_test.rb, test/jobs/create_uphold_cards_job_test.rb, test/models/publisher_test.rb, test/services/publisher_wallet_getter_test.rb, test/unit/wallet_test.rb
Resolves #1725 
Should be deployed after https://github.com/brave-intl/bat-ledger/pull/582
Test Plan:
Tests
Security:
=> Create Uphold cards when the wallet address is blank

app/jobs/create_uphold_cards_job.rb, app/services/payout_report_publisher_includer.rb, test/services/payout_report_publisher_includer_test.rb
Resolves #1731 
Test Plan:
Tests
Security:
=> Automatically create uphold cards during payout

app/controllers/admin/payout_reports_controller.rb, app/models/json_builders/manual_payout_report_json_builder.rb
There was a small issue in downloading manual reports, the existing code would overwrite the `authority` field with the currently signed in `admin`. For `manual reports` we want the `authority` field to display the admin that `finalized the invoice`. 
* Manual report `authority` is not overwritten by the currently signed in `admin`
* Manual report `authority` field now displays the `e-mail address` instead of the `name` 
* For regular payout reports, the default `authority` field is null, it is set when the `download` button is clicked. 
* As an `admin` request an `invoice` on a `partner`
* Finalize the `invoice`
* Log in as a different `admin`
* Generate a `manual payout report`, ensure the `authority` field is the first `admin` 
* Generate a `regular payout report`, ensure the …
=> Manual Report Download Fix 🔧 

app/models/json_builders/manual_payout_report_json_builder.rb, app/models/potential_payment.rb, app/views/admin/payout_reports/index.html.slim, app/views/admin/publishers/show.html.slim
Resolves #1685 
A missing address causes the transaction to fail at execution time.  However that failure serves as an alert that there may be a bug with us or uphold, which we would likely miss if this pr goes in as is.
I think we may need one more component to this pr that makes sure we're aware if many people didn't make it into the payout report.  Maybe another column on the payout report page displaying # payments with of missing addresses for unknown reasons would do the job.
Test Plan:
Tests
Security:
=> Do not include publishers with missing addresses in payout report

app/models/payout_report.rb
Exclude `manual` payout reports from `most_recent_final_report` which will allow publisher payout data to show up again on their page.
=> Fix missing payout info on Admin Publisher Page 🏷 

app/views/two_factor_authentications/index.html.slim, config/locales/en.yml
Move Lost 2FA links to the 2fa auth page, to account for the new landing page. 
1. Create a Publisher with U2F
2. Attempt Login
3. Create a Publisher with 2FA
4. Attempt Login
=> Move 2fa removal links 🏷 

app/controllers/publishers/omniauth_callbacks_controller.rb, app/models/json_builders/channels_json_builder.rb, test/controllers/publishers/omniauth_callbacks_controller_test.rb
This is the bug, where we saw multiple channels transfer to more than one user. 
The problem is that when the user was transferring their channel, we found the first Channel with the same id. However the channel that we found was not the original verified channel.
1. Create 3 publisher accounts `a@a.com`, `b@b.com`, `c@c.com`
2. Add a channel to `a@a.com`
3. Sign into `b@b.com` add the same channel
4. Sign into `c@c.com`, add the same channel
5. Sign back into `b@b.com` channel should be gone.
6. Reject the transfer for `c@c.com`, channel should be successfully rejected.
=> Prevent chaining of channel transfers

app/controllers/admin/payout_reports_controller.rb, app/views/admin/invoices/show.html.slim
Due to the settlement tools removing the `documentId` attribute from the list we must find by the owner and the amount to mark things as paid.
Once an invoice was paid users were able to click "Edit" which was a mistake
1. Create a partner
2. Create an invoice
3. Mark that invoice as ready to be paid out
4. Copy the publisher id and the amount put it in the JSON below
5. Upload this settlement report JSON file
```json
[
{
"altcurrency": "BAT",
"authority": "user@brave.com",
"amount": "4321",
"commission": "0",
"currency": "BAT",
"address": "redacted",
"owner": "publishers#uuid:d2d9c735-522c-484c-90a6-e2da78e12c99",
"fees": "0",
"probi": "redacted",
"hash": "redacted",
"publisher": "",
"signedTx": "",
"status": "completed",
"transactionId": "redacted",
"fee": "0",
"type": "manual", …
```
=> Minor fixes for invoices

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
This reverts the calculation of the next deposit date, Since the job runs after midnight UTC users will believe that the next time they get paid is in the month afterwards
Closes #1809
=> Fix payout date rollover before SetPayoutInProgressJob is run

lib/eyeshade/last_settlement_balance.rb, test/helpers/publishers_helper_test.rb, test/services/publisher_wallet_getter_test.rb, test/unit/wallet_test.rb
Closes #1792
When we did the Eyeshade refactor we miscalculated the last settlement balance. Basically we assumed that the `settlement_amount` was always going to be in BAT when in reality it is set to the default currency that has set. 
Because of this we were effectively double converting the last settlement and obtaining incorrect information on the last settlement amount. 
You might have to connect to eyeshade to effectively test. Basically to code this I connected to our prod instance and figured out what entries that eyeshade was returning for the transactions. For example
```json
[
{
"channel": "REVOKED",
"created_at": "2019-05-09T07:16:50.772Z",
"description": "payout for referral",
"amount": "-12411.568331542155128098",
"settlement_currency": "USD",
"settlement_amount": …
```
=> Fix calculation of last settlement

app/jobs/delete_publisher_channel_job.rb, app/models/publisher.rb
Handles the edge case where a user is attempting both a `Two Factor Removal` and `Channel Transfer` at the same time. 
Fixes - 
https://sentry.io/organizations/brave-software/issues/1016272053/?project=225116&query=transaction%3A%22Sidekiq%2FTwoFactorAuthenticationRemovalJob%22&statsPeriod=14d
1. Try performing a 2FA Removal on an account with a Channel that's also contesting
=> 2FA Removal Patch 🏷 

app/models/publisher.rb, app/views/admin/publishers/show.html.slim, app/views/layouts/admin.html.slim
During my development of the notes page I included the tribute.css in the main Admin section. I later extracted it into it's on "Tribute" file so I could isolate it's loading to just the publishers show page.
Well I forgot to take that out and so it's causing an error on staging. This is a pull request to fix that.
1. I deployed this branch to staging so try logging in there :alien:
=> Fix pack tag

app/controllers/api/v1/stats/publishers_controller.rb, config/routes.rb, test/controllers/api/v1/stats/publishers_controller_test.rb, test/fixtures/uphold_connections.yml
Opens up `/api/v1/stats/publishers/channel_and_kyc_uphold_and_email_verified_signups_per_day` which tracks publishers who have 
1. Verified their `e-mail`
2. Added a verified channel 
3. Added an uphold account
4. KYC'd their uphold account
Closes #1524 
1. Create a publisher account with the above criteria satisfied
2. Request `/api/v1/stats/publishers/channel_and_kyc_uphold_and_email_verified_signups_per_day` and ensure the publisher is logged there
=> Stats for KYC'd Uphold accounts 🏷 

app/jobs/cache_browser_channels_json_job.rb, config/environments/production.rb, config/environments/staging.rb
* Reduce the redis timeout to prevent our app from timing out when trying to write
* Add in retry logic
* Create a slack message every time we fail so that we have more awareness than just a sentry message
=> Decrease Redis timeout, retry logic, slack msg

app/controllers/admin/channels_controller.rb, app/javascript/packs/views/admin/publishers/Duplicates.js, app/models/channel.rb, app/views/admin/channels/duplicates.html.slim, app/views/admin/publishers/index.html.slim, app/views/admin/shared/_sidebar.html.slim, app/views/layouts/admin.html.slim, config/database.yml, config/routes.rb, db/schema.rb
This is so we can properly figure out what is happening when we have duplicate channels. The last time this happened we had a sentry issue but weren't aware that duplicates were an issue of the bug
1. Log in, create a duplicate channel
=> Alert for duplicate channels

Gemfile, Gemfile.lock, app/views/publishers/_choose_channel_type.html.slim, test/controllers/publishers/omniauth_callbacks_controller_test.rb, test/controllers/site_channels_controller_test.rb
This adds the following gem which resolves the vulnerability.
https://github.com/cookpad/omniauth-rails_csrf_protection
This was recommended based on the discussion here
https://github.com/omniauth/omniauth/pull/809#issuecomment-497376674
1. Add your youtube channel, twitch, twitter, etc
2. It sucessfully adds
Closes https://github.com/brave-intl/publishers/issues/1944
=> Resolve CVE-2015-9284

app/jobs/cache/piwik_data_job.rb, config/heavy_sidekiq.yml, config/sidekiq.yml
Moves scheduled to be less important than the default queue
Also moved the transaction queue to scheduler queue. This is because the following in the README
>I don't recommend having more than a handful of queues. Lots of queues makes for a more complex system and Sidekiq Pro cannot reliably handle multiple queues without polling. M Sidekiq Pro processes polling N queues means O(M*N) operations per second slamming Redis.
https://github.com/mperham/sidekiq/wiki/Advanced-Options
=> Fix queue priority

app/models/channel.rb, app/services/publisher_statement_getter.rb
Bugfix: Users who have removed a channel can still view their statements
Basically what is happening is that we're trying to find a channel that doesn't exist and so we have a `NoMethodError` on `nil`. 😢 
**This fixes the following sentry errors**
(7 issues are here because of this)
https://sentry.io/organizations/brave-software/issues/?project=225116&query=find_by_channel_identifier&statsPeriod=14d
1. Have the eyeshade response return something that is currently not in the table
2. Try to download a statement
3. Downloads and doesn't 500
=> Fix 500 on statements

lib/tasks/email_tos_update.rake
* Allows you to resume if there was an exception found
```sh
Emailing 4 users
.
Rescued from exception: idk timeout or somethin
Could not send email to e086cf4e-efc5-4a42-a132-f8fb47ca5742 - Restart the job by running the following
rake email:tos_update["e086cf4e-efc5-4a42-a132-f8fb47ca5742"]
```
Now if you run 
```sh
~/r/publishers ❯❯❯     rake email:tos_update["e086cf4e-efc5-4a42-a132-f8fb47ca5742"]
2019-06-19 13:57:12 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
Emailing 2 users
.
Done
```
=> TOS Email update - Add in some optional parameters

.travis.yml, app/assets/stylesheets/pages/home.scss, app/controllers/admin/publishers/publisher_status_updates_controller.rb, app/helpers/admin/publishers_helper.rb, app/javascript/views/admin/components/userNavbar/components/TopNav/TopNavStyle.ts, app/jobs/delete_publisher_channel_job.rb, app/jobs/include_publisher_in_payout_report_job.rb, app/models/channel.rb, app/models/promo_registration.rb, app/models/publisher.rb, app/models/publisher_status_update.rb, app/services/promo/publisher_channels_registrar.rb, app/views/admin/publishers/publisher_status_updates/index.html.slim, app/views/publishers/home.html.slim, test/controllers/site_channels_controller_test.rb, test/fixtures/publisher_status_updates.yml, test/fixtures/publishers.yml, test/tasks/launch_promo_test.rb
- Create new state called "only user funds"
- Remove promo registrations when they are being deleted
- Handle new 409 statuses being returned when promo server has user under `no-ugp` owner state.
Prereqs
- Have the promo server running
- Be able to create many channels
1. Create a channel that will be able to generate a promo code
2. Insert into our publisher into the the promo server
```sql
INSERT INTO owner_states (owner_id, state) VALUES ('3a1dd608-7552-40f2-ad49-92439bb91fa2', 'no-ugp');
```
3. Try to add another channel
4. No promo registration will be created for it 🎉
5. Move publisher over to the `only user funds` state.
6. It deletes all the `PromoRegi`strations
=> Create "only  user funds" state

app/services/promo/models/owner_state.rb
🐛 Fixes duplicate slash in service call which prevented administrators from viewing publishers
=> Release 2019-07-02

app/jobs/create_uphold_cards_job.rb, app/jobs/migrate_uphold_access_parameters_job.rb
During the staging migration we received a lot of slack alerts. This led me to find that if Uphold returns a 401 (`invalid_token`) then we continue down and try to create an uphold card for that user. 
This will improve performance during the migration
=> Remove useless slack message and skip 

app/views/publishers/home.html.slim
When a user connects a brand new uphold account they are presented with the default currency screen. They should not be presented with this
=> Don't show default currency modal on pending accounts

app/controllers/admin/publishers_controller.rb, test/controllers/admin/publishers_controller_test.rb, test/fixtures/publishers.yml
In production we're only returning the defaultCurrency for the publisher in this. Instead we should be returning the name, id, etc
=> Fix Case Assignments

app/views/admin/payout_reports/index.html.slim, app/views/admin/publishers/index.html.slim
The "Remove payout in progress" and "Set payout in progress" buttons on the payout report were.
Also modified the design of the filters a little bit to correspond with Ross's original design
=> Fix indentation and align filter

app/services/manual_payout_report_publisher_includer.rb
This fix the manual payout report. Before we were filtering out the reauthorization needed. This was a problem because the logic was reversed
closes #2120
1. Kick off a manual payout report with people who should be on it.
2. Refreshing the JSON works
3. The report contains entrise
=> Fix manual payout publisher includer

Gemfile, Gemfile.lock, app/controllers/admin/stats/contributions_controller.rb, app/controllers/admin/stats/referrals_controller.rb, app/controllers/api/v3/public/base_controller.rb, app/controllers/api/v3/public/channels_controller.rb, app/jobs/application_job.rb, app/jobs/cache_browser_channels_json_job_v3.rb, app/models/channel.rb, app/models/github_channel_details.rb, app/models/json_builders/channels_json_builder_v3.rb, app/models/publisher.rb, app/models/reddit_channel_details.rb, app/models/site_banner.rb, app/models/twitch_channel_details.rb, app/models/twitter_channel_details.rb, app/models/vimeo_channel_details.rb, app/models/youtube_channel_details.rb, app/views/admin/stats/_top_eyeshade_wallets.html.slim, config/environments/development.rb, config/routes.rb, test/fixtures/uphold_connection_for_channels.yml, test/models/json_builders/channels_json_builder_test_v3.rb
Closes #2142 
- Adds support for non-KYC'd publishers to have their tips held as "pending" on the browser
- Generates statistical totals based on the JSON and not what we have in our database (Reflective of the actual system) 
- Reduces the amount of queries executed / minor performance gains
| Version | Time (seconds)| Channels Generated|
| -------- | ---- | ---------------------- |
|  V1 | 1524.278572 | 251,094 |
| V2 | 1244.177728  | 83,917 |
| V3 | 1617.463192 | 251,094 | 
<i>* Generated using Ruby Benchmark using Production data</i>
Here's the results from the latest `/api/v3/channels/totals` endpoint
```JSON
{
"site": {
"verified": 12935,
"connected": 11830,
"total": 24765
},
"all_channels": {
"verified": 83927,
"connected": 97974,
"total": 181901
},
"twitch": {
"verified": 5586, …
```
=> Publisher Channels V3 API

app/jobs/create_uphold_cards_job.rb, app/jobs/create_uphold_channel_card_job.rb, test/controllers/publishers_controller_test.rb, test/jobs/create_uphold_cards_job_test.rb
Some of the publishers that have existing cards linked are having their cards link automatically to their wallet. This adds some additional logic to try and prevent that and add deterministic lookups when `CreateUpholdCardsJob` is called.
**The strategy is:**
We look up the existing address on the connection If it’s the same currency as the uphold_connection then we don’t modify anything.
If it’s not, then we get a list of the uphold’s users cards, then iterate on each one of them to ensure that
1. they aren’t for a channel (we haven’t stored them in the Uphold
2. they don’t have a private address (This one requires an API card per card to /card/:id/addresses
If there are no results that match that then we simply create the card
=> Fix Publisher Uphold Cards

app/models/json_builders/channels_json_builder_v3.rb
On the exclusion list we accidentally are specifying false instead of an empty string
=> [V3] Use empty string instead of false for excluded channels

app/jobs/create_uphold_channel_card_job.rb
=> Fix create_uphold_channel_job

app/models/channel.rb
It seems like when a user adds a new channel then the job fails on the first time. I googled this and found that this is a fairly common "gotcha" 
https://www.justinweiss.com/articles/a-couple-callback-gotchas-and-a-rails-5-fix/
This fix should allow users to have their channels be created successfully
=> Move create_uphold_cards to be after_commit

Gemfile, Gemfile.lock, app/controllers/publishers_controller.rb, app/javascript/publishers/home.js, app/models/publisher.rb
closes #2171 
- Improve validations on emails
- Removes the use of `innerHTML` for user based strings
- Removes unused email validator gem
1. Create a valid account
2. Remove the HTML `type="email"` on the Update Contact section of the publishers dashboard
3. Update fails
I tested this on a variety of different emails and everything seems to be working 🎉
=> Remove Self-XSS for pending_email

.rubocop.yml, app/jobs/create_uphold_cards_job.rb, app/jobs/create_uphold_channel_card_job.rb, app/models/uphold_connection.rb, app/models/uphold_connection_for_channel.rb, db/migrate/20190828175151_add_uphold_id_to_uphold_connection_for_channel.rb, db/schema.rb, test/jobs/create_uphold_channel_card_job_test.rb
Because we weren't tracking Uphold IDs on the card connections we ran into an issue where if someone tries and create new cards then there will be an error.
=> Fix error on homepage load

app/jobs/create_uphold_channel_card_job.rb, app/models/uphold_connection.rb
Before this change if a user had a previous channel card created and the existing card_id was not found on their account. Then they would run into this duplicate collision. 
Here are the changes
- Moved the creation and find logic to the same place
- Put all the card id logic in one place 
This way anytime we try to create cards it will always either find the connection, or create a new one.
Then it will try to find the card id, if it can't find it, then tries to find one that aligns with the existing card data. Then if it can't find anything it creates a new one.
After that it tries to find or create the address on that card and updates the existing DB connection with the values.
=> Fix unique card collision 

app/jobs/create_uphold_channel_card_job.rb
If a channel is deleted or re-added like in the case of Uphold.com we need to update the reference to the new channel_id
=> Update Channel ID when a channel is being transferred

app/jobs/delete_publisher_channel_job.rb
We've been seeing users report that the 2fa removal job is failing. This is due to one of the publishers channels being transferred to the account which is having the 2fa removed. 
Closes #2289
=> Reject transfer for deleting channels undergoing transfer

app/services/publisher_statement_getter.rb
While pulling the statements if the account doesn't have the correct scope then they will get an exception. We should rescue and ensure that they can still view their normal Eyeshade-based transaction. 
Closes #2299
=> Fail gracefully when we don't have access to uphold transactions

app/views/layouts/application.html.slim, app/views/layouts/promo_registrations.html.slim, config/locales/en.yml
- Removes the whitespace
- Updates the page with correct info
=> Fix Getting Started Page

app/services/payout_report_publisher_includer.rb
We should not spam publishers who have less than 5 BAT with KYC emails
=> Enable a threshold before emailing publishers to KYC

app/controllers/admin/channels_controller.rb, app/models/channel.rb, app/views/admin/channels/destroy.js.erb, app/views/admin/publishers/_channel.html.slim, config/routes.rb, test/models/channel_test.rb
Closes #2117
- Adds ability for administrators to delete Publisher's channel (with record)
- Add additional validation to prevent duplicate channels
=> Prevent Duplicate Channels for same publishers

app/mailers/publisher_mailer.rb, app/services/payout_report_publisher_includer.rb, app/views/publisher_mailer/uphold_kyc_incomplete.html.slim, app/views/publisher_mailer/wallet_not_connected.html.slim, config/locales/en.yml, test/mailers/previews/publisher_mailer_preview.rb, test/mailers/publisher_mailer_test.rb, test/services/payout_report_publisher_includer_test.rb
Closes #2346
- Put the total amount of BAT that a user will be paid if they verify their Uphold account
=> Show total amount during KYC emails

app/controllers/admin/payout_reports_controller.rb
Last payout cycle when the final settlement report was uploaded the file wasn't able to be uploaded for some reason and so we need to warn when this happens
=> Warn when settlement report can't be uploaded

app/services/eyeshade/referrals.rb
Closes #2404
Our call to Eyeshade is not returning any valid data due to an incorrect id that is being passed in.
=> Use owner identifier for Eyeshade call

app/controllers/admin/unattached_promo_registrations_controller.rb
Redirecting is an array, so when we call `.reject` on the params this causes an error
=> Minor redirect bug

app/views/publisher_mailer/login_email.html.slim, config/locales/en.yml
=> Copyable link embedded in login url

app/services/eyeshade/referrals.rb
Since the keys on this endpoint weren't symbolize the calculations for the referral codes aren't displaying properly in the following code.
https://github.com/brave-intl/publishers/blob/40f0ab2b4c5175bfa1da5daf0cd3c0cf2634f729/app/controllers/publishers/promo_registrations_controller.rb#L27-L29
When the keys are properly symbolized this logic will be able to function correctly.
Log into production via Heroku
Copy / paste change
Run the linked code above
Counts are properly going for codes.
=> Symbolize keys from Eyeshade response

app/services/promo/registration_stats_report_generator.rb
Minor copy/paste mistake when referring to end_date
=> Use end_date instead of start_date

app/services/promo/registration_stats_report_generator.rb
🐛 Use end_date instead of start_date (#2445)
=> Release 2019-12-13 (2)

Gemfile.lock, app/assets/stylesheets/admin/pages/publisher.scss, app/controllers/admin/publishers_controller.rb, app/helpers/payout_helper.rb, app/jobs/enqueue_publishers_for_payout_job.rb, app/jobs/enqueue_publishers_for_payout_notification_job.rb, app/jobs/include_publisher_in_payout_report_job.rb, app/models/payout_message.rb, app/models/payout_report.rb, app/services/payout_report_publisher_includer.rb, app/services/publisher_wallet_getter.rb, app/services/uphold_request_access_parameters.rb, app/views/admin/publishers/show.html.slim, app/views/publishers/_payout_status.html.slim, app/views/publishers/home.html.slim, config/initializers/sidekiq.rb, config/locales/en.yml, db/migrate/20200114024815_create_payout_messages.rb, db/schema.rb, test/controllers/admin/payout_reports_controller_test.rb, test/jobs/enqueue_publishers_for_payout_job_test.rb, test/jobs/enqueue_publishers_for_payout_notification_job_test.rb, test/services/payout_report_publisher_includer_test.rb
It's currently very hard to debug why a publisher might not have been included in a payout. We introduce a new table to help diagnose and debug reasons why a publisher might not have been included. 
- Introduce PayoutMessage
- Introduce a field for `include_transactions` on PublisherWalletGetter. Transactions are not needed during payout report.
=> Create Payment Message for reporting

config/initializers/sidekiq.rb
In production we currently get a `TypeError` which shows as an HTTP 500. By removing Sidekiq saving sessions this fixes the error and also fixes being logged out from Publisher's when you have both the UI and are logged in
=> Fix Sidekiq UI

app/helpers/payout_helper.rb
`locked?` isn't a method on a string :) We should check the string value instead
=> Fix Locked Check on Payout Helper

app/controllers/publishers/registrations_controller.rb, public/robots.txt
Closes #2535 
- Removes expired_auth_token from google search results
- Filters out email if someone gains access to a publisher id and accesses the page
=> Filter out email addresses for resend_authentication_email

app/controllers/api/v1/transactions_controller.rb, app/services/uphold/models/transaction.rb, config/routes.rb
Closes #2491
For user funded auto-contribute we need to verify that a given transaction happened for a given a channel identifier. 
This gets the amount that was verified and ensures the transaction happened for the right channel.
=> Create Internal API for Uphold Transactions

config/initializers/rack-attack.rb
Closes #2515 
🐛 Fixes a bug where path 
1. Run `rails dev:cache`
2. Hit the registrations controller about 60 times 
3. Should get a http code `420`
=> Fix rate limit on registration

app/controllers/concerns/browser_channels_dyno_caching.rb
Fix #2592, which `Time.at` is trying to be run against a string instead of an int.
=> [Bug] Fix an reading dyno cache error

app/models/site_channel_details.rb, config/sidekiq.yml
It seems ridiculous to ping every hour for 6 weeks. This is cutting into running other jobs.
=> Decrease the number of pings we use for site channel verifications.

app/controllers/publishers_controller.rb, app/models/publisher.rb, test/controllers/publishers_controller_test.rb
Users shouldn't be able to enter a really long name as it messes with the styling and formatting of the website.
=> Limit the length of a name

app/services/uphold_request_access_parameters.rb, config/heavy_sidekiq.yml, config/sidekiq.yml
(1) I don't think we really use V1 or V2 though it seems someone is still hitting the API. Let's enqueue it only daily
(2) We're hitting Youtube quota limits, so this will be one fix to allow people to signup without issue.
=> Change when jobs get enqueued

app/javascript/locale/en.ts, app/javascript/views/statements/Statements.tsx, app/javascript/views/statements/statements/StatementDetails.tsx, app/javascript/views/statements/statements/statementDetails/DetailSection.tsx, app/jobs/cache_uphold_tips.rb, app/models/cached_uphold_tip.rb, app/models/views/user/statement_overview.rb, app/models/views/user/statements.rb, app/services/publisher_statement_getter.rb, app/services/uphold/models/transaction.rb, db/migrate/20200510205028_change_cached_uphold_tips_to_uuid.rb, db/schema.rb
🐛 UpholdConnectionForChannel was `BigInt` rather than `UUID`
🐛 Fix issue where only the first page would be returned if there weren't any previously cached values
🐛 Fix grouping of Statements due to DateTime vs Date mismatch
🐛 Only return and display transactions that were made from the browser to the uphold card
✨ Provide a link to the Uphold card that the deposits were made on. 
✨ Fix overview page to show more specifically the total brave deposited and Uphold tips
=> Fix Statement Bugs

Gemfile.lock
Currently users aren't able to connect their Twitch accounts due to a "Client id" not being passed in via headers
=> Upgrade Twitch Gem

app/controllers/concerns/browser_channels_dyno_caching.rb
Related to https://github.com/redis/redis-rb/issues/524
=> Close the connection after setnx is called. 

db/migrate/20200527071037_add_index_contested_by_channel_id.rb, db/schema.rb
Details in https://rpm.newrelic.com/accounts/2604309/applications/592980707_h592981222/datastores#/overview/All/drilldown?metric=Datastore%252Fstatement%252FPostgres%252FChannel%252Ffind
=> Fix perf issue when looking up contested_by_channel_id

public/creators-landing/public/index.html
Our SEO consultant flagged the `og:url` meta tag on creators.brave.com as being an SEO concern due to using `http` instead of `https`.
=> Change http to https on meta og:url tag

.rubocop.yml
When running rubocop we were seeing seeing the following errors
```
~/r/publishers ❯❯❯ bundle exec rubocop
/Users/cory/repos/publishers/.rubocop.yml: Warning: no department given for AlignParameters.
/Users/cory/repos/publishers/.rubocop.yml: Warning: no department given for Documentation.
/Users/cory/repos/publishers/.rubocop.yml: Warning: no department given for LineLength.
```
After this change we get the following result.
```
~/r/publishers ❯❯❯ bundle exec rubocop      
Inspecting 93 files
.............................................................................................
93 files inspected, no offenses detected
``
=> Fix .rubocop.yml Warnings

lib/tasks/expire_promo_codes.rake
`pry` is a dependency used for setting breakpoints. The gem is only required in development and test mode. https://github.com/brave-intl/publishers/blob/staging/Gemfile#L177
As part of the application loading this rake task it fails to find the gem causing the deployment to fail.
=> Fix dev dependency being required

config/application.rb, config/initializers/fastly.rb, config/services.yml
Support Fastly being fronted by publishers by adding the list of proxy IPs to Rails trusted proxies list 
1. Deploy to staging
2. Ensure you can access the rails admin console using the brave VPN
=> Fastly trusted_proxies list

app/jobs/cache/browser_channels/responses_for_prefix.rb
Seems odd, but this is what we do in V3: https://github.com/brave-intl/publishers/blob/staging/app/models/json_builders/channels_json_builder_v3.rb#L73
=> Handle cases where there isn't an uphold_connection for a channel

app/jobs/cache/browser_channels/responses_for_prefix.rb
🐛 Handle cases where there isn't an uphold_connection for a channel (#2789)
=> Release 2020-06-30

config/initializers/rack-attack.rb
Closes #2791
This change fixes the bug where Rack::Request wasn't filtering the `trusted_proxies` based on Rail's configuration. This change access the ActionDispatch middleware of the calculated ip address or the existing rack IP.
=> Fix rack attack

app/services/payout/potential_payment/uphold_service.rb, test/services/payout/potential_payment/uphold_service_test.rb
🐛 Fixes bug where card address wasn't being reloaded once it was modified.
✨ Unit tests pass
=> Reload uphold connection

app/models/json_builders/manual_payout_report_json_builder.rb, app/models/json_builders/payout_report_json_builder.rb
This adds the wallet provider as a field to our JSON formatted payout reports.
1. Generate a payout report
2. Download it and ensure `walletProvider` is a field in the payout entries
=> add wallet provider to generated payout report json

app/views/publishers/settings/index.html.slim
Closes #2600
:bug: Don't call send_emails on nil class
1. Update your publisher account to have the `uphold_connection` set to nil. `send_emails`
=> Don't call send_emails on nil class

app/models/uphold_connection.rb
Closes  #2793
:bug: Fixes error when `valid_card?` returns Faraday::ClientError
1. Sign into Uphold
1. Sign into Publishers 
1. Connect your uphold account. **DON'T SET DEFAULT CURRENCY**
1. Change you password on Uphold
1. On your Publishers account set default Currency
1. Page reloads and works as intended.
=> Fix ClientError

app/controllers/admin_controller.rb, app/views/admin/errors/not_authorized.html.slim, test/controllers/admin/channels_controller_test.rb, test/controllers/admin/faq_categories_controller_test.rb, test/controllers/admin/payout_reports_controller_test.rb, test/controllers/admin/publishers_controller_test.rb
🐛 Don't show a 500 when a user who isn't signed in tries to access the admin workflow
1. Don't sign in
`http://localhost:3000/admin/publishers`
2. See the following
=> Show error screen when user isn't logged in

Gemfile, Gemfile.lock
=> Upgrade Sidekiq to 6.1.0, prevent logs from being polluted Redis#exists(key)

app/controllers/admin/payout_reports_controller.rb
This removes the call to Eyeshade when marking Invoices as paid or not.
1. Create an invoice
1. Upload a settlement report with the invoice information
1. Go and load the Publishers page
1. See that the invoice was marked paid
=> Remove Eyeshade Call when uploading Invoices

app/controllers/api/v1/promo_registrations_controller.rb, app/mailers/publisher_mailer.rb, app/views/publisher_mailer/suspend_publisher_for_brand_bidding.slim, app/views/publisher_mailer/suspend_publisher_for_brand_bidding_and_impersonation.slim, config/locales/en.yml, config/routes.rb, test/controllers/api/v1/promo_registrations_controller_test.rb
POST /api/v1/promo_registrations/:referral_code/publisher_status_updates
The endpoint is the same as the existing publisher_status_updates
endpoint (a note, status, and admin are required) except a referral
code is supplied in the url param.  The controller action looks up
the publisher associated with that code, then updates the publisher's
status.
1. Step one
2. Step two
3. Step three
=> Add API to suspend publishers by referral_code

app/views/publishers/_channel.html.slim
Looking at when a user has not completed their KYC but previously had referral codes enabled they are still able to see a referral code
1. Register for a channel 
1. Sign up for the promo program
1. Connect your Uphold account
1. Disconnect your Uphold account
1. See that there is no referral link shown for your attached channel
=> Hide Referral Links on Channels

app/services/payout/potential_payment/uphold_service.rb, test/services/payout/potential_payment/uphold_service_test.rb
We should filter these countries out in the anti-fraud stage rather than preventing them from being included at the beginning.
=> Fix country exclusions from start

app/controllers/payment/connection/gemini_connections_controller.rb, app/models/gemini_connection.rb, app/services/gemini.rb
Closes #2836 
Closes #2835
✨  De-duplicates some code with in the GeminiConnections controller. 
🐛 Fixes edge case where Gemini returns multiple users and only one `is_verified`
=> Update Scope and Gemini Verified Status

app/views/admin/publishers/index.html.slim, db/migrate/20200903184106_add_performance_improvements.rb, db/schema.rb
We're seeing some reliability issues with the Publisher's dashboard. Some of that is due to Postgres load. Especially while searching this takes some time. 
To reduce the load temporarily i've 
* Introduced an index that should improve the `site_banner_lookup` while building the channels.
* Removes infrequently used columns and joins from the index page.
=> Minor performance improvements

app/controllers/api/v1/publishers_controller.rb
If an API request is made to change a user out of only_user_funds we ignore it.
=> Do not automatically move publishers out of only_user_funds

config/environments/production.rb, config/environments/staging.rb, config/initializers/content_security_policy.rb
This reverts commit 4fc569e2a741f9cf4c888e599901ccfb19c73ef3.
The CSP policy was breaking due to an outdated `styled-components` in Brave-UI. https://github.com/brave/brave-ui/issues/128
I will be taking this on when I have capacity, but until then we need to revert this commit.
=> Revert "Set a Content-Security-Policy (#2580)"

.dockerignore, lib/tasks/assets.rake, package.json, public/service-worker.js
* Remove the `yarn build` step. 
We don't technically need this right now. This was originally added so that if a change is made on the public site but "yarn build" isn't run then the latest changes will still be deployed.
* Reverse engineer the Rails Webpacker and Sprockets pipeline so that we can use an arbitrary digest.
=> Simplify deploy by using commit hash as digest

lib/tasks/assets.rake
```
[user@work:~/source/publishers]% irb
irb(main):001:0> sha = `git rev-parse HEAD`
irb(main):002:0> sha
=> "18ff828bfb6c463f4ef7909997d800ea02268a1b\n"
irb(main):004:0> sha = `git rev-parse HEAD`.strip()
irb(main):005:0> sha
=> "18ff828bfb6c463f4ef7909997d800ea02268a1b"
```
=> strip newline from git sha used in asset compilation

lib/tasks/assets.rake
We were seeing some weirdness with some of the assets being replicated. This was because the hex regex improperly matched assets that were structured like `choose-channel-1a2b3e4c.svg`. Where the first character was like a hex. 
To fix this I've updated the regex that 8 characters must match a hex, up to the `.`
=> Update assets regex

Dockerfile
We were seeing this error on the creators.bsg.brave.com page when uploading an image 
This adds the `imagemagick` to the Dockerfile to support image resizing
🐛 Fixes the Imagemagick dependency on creators.bsg.brave.com
✅  Tests pass / `make docker` works.
=> Add Imagemagick to Dockerfile

app/models/site_banner_lookup.rb
Uses the guide from [Rails](https://edgeguides.rubyonrails.org/active_record_multiple_databases.html) to connect to the secondary follower database to read and reduce load from the primary database.
=> SiteBannerLookup reads from other database

app/controllers/publishers/promo_registrations_controller.rb, app/models/concerns/referral_promo.rb, app/views/publishers/_promo_panel.html.slim
:bug: Fix promo status for existing users
In many places in the code we use the `may_register_promo?` which shows or hides the existing promo logic based on the users' status. 
When we introduced the `return false` on `valid_promo_country?` we disabled the promos site-wide. 
This change removes that logic, allowing the existing referral program to continue to function but disables all new signups except in development mode.
=> Fix promo status for existing users

app/services/base_api_client.rb
Reverts brave-intl/publishers#2931
Another change might be causing issues in staging. We'll merge and test separately
=> Revert "added if statement for adding proxy"

app/assets/stylesheets/pages/home.scss, app/controllers/admin/publishers_controller.rb, app/controllers/publishers_controller.rb, app/views/admin/publishers/show.html.slim, app/views/publishers/home.html.slim
most elegant solution, as it causes a full page reload when going from
page to page, but the current impression is that the vast majority of
users have less than 20 channels.
Loading the channels could also be improved by figuring out a way
to join the data across multiple tables, but I have not figured out
how to get this to work with partials.
=> Limit number of channels rendered per page down to 20. This isn't the

app/controllers/admin/publishers_controller.rb, app/controllers/publishers_controller.rb
The underlying partial for channels has some N+1 queries. This cuts down the N+1 queries from before in half.
=> Decrease loads for channel down to 10

app/services/payout/gemini_service.rb, app/services/payout/service.rb
This handles an edge case in which a publisher has an UpholdConnection and a GeminiConnection, but the Uphold connection is the selected connection. 
Currently in this case the code will attempt to create a Gemini payment, but it will fail since the `selected_wallet_provider` (removed on line 10) will return an Uphold connection, and the UpholdConnection does not have the field `recipient_id`, used later.
The current code will also not create an Uphold payment because (even though it is active), since there exists a gemini connection.
This PR does two things:
* It removes the assumption that the `selected_wallet_provider` has to be a GeminiConnection in the Gemini payout service
* It allows the creation of Uphold payments even if there exists a GeminiConnection for the publisher if the …
=> Payout reports quick fix

app/jobs/enqueue_publishers_for_payout_job.rb, app/jobs/payout/gemini_job.rb, app/jobs/payout/paypal_job.rb, app/jobs/payout/uphold_job.rb
For each provider payout job, only enqueue publishers that have that
wallet provider as their selected wallet provider, or have no wallet
provider selected.
=> Be more selective about which payout jobs to enqueue

app/views/admin/publishers/_note.html.slim, app/views/admin/publishers/index.html.slim
Closes https://github.com/brave-intl/publishers/issues/2960
This PR allows hyperlinks to appear due to the String object being marked HTML safe.
=> Fix links for admin publisher notes

app/jobs/cache/browser_channels/responses_for_prefix.rb, config/secrets.yml
I don't think we need this PR anymore, as the issues with getting the prefix uploaded no longer seems to result in an error as seen by the following curl:
`curl -v https://pcdn.bravesoftware.com/publishers/prefixes/ce55 > g.txt`
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< content-type: binary/octet-stream
< content-length: 2000
< date: Thu, 21 Jan 2021 04:32:43 GMT
< last-modified: Fri, 08 Jan 2021 08:30:08 GMT
< etag: "c6562e183b511bb632c5999f858551d3"
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Miss from cloudfront
< via: 1.1 bdb686e41bd85ffb1c6e5b48947e5566.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO53-C1
< x-amz-cf-id: l3qGhuuX2kSxB7apjJS_V1GGDk6p7jrybq7fS4mcxRvsUJacj9qg6w==
<
{ [2000 bytes data]
100  2000  100  2000    0     0   6578 …
```
=> Revert "fixed permission control for s3_rewards2"

Gemfile, Gemfile.lock, app/controllers/health_checks_controller.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb
connection object like the following:
REDIS.with do |conn|
conn.set('a', 'b')
end
result = REDIS.with do |conn|
conn.get('a')
end
2. Also change the health_checks_controller by getting rid of the
migration checks, as it seems that if a migration is occurring, then
Kubernetes pods will be thrown into a boot loop.
Closes https://github.com/brave-intl/publishers/issues/3006
=> 1. Add connection pooling option to Publishers App. One can use a

app/jobs/cache/browser_channels/main.rb, app/jobs/cache/browser_channels/responses_for_prefix.rb, app/jobs/verify_site_channel.rb
uses `ActiveRecord::Base.connection_pool` to wait for a connection to be available instead of starting many at once and erring if it takes longer than 5 seconds
1. Step one
2. Step two
3. Step three
=> scoped connection for verify site

.env.example, README.md
Updates the README with newer Oauth instructions
As I went through the README, I noticed that some of the
instructions are out-of-date. At the same time, I'd like
to start moving references to the app to 'creators' instead
of 'publishers' wherever possible to start unifying on the
new name.
=> Updates the README with newer Oauth instructions

app/services/publisher_token_authenticator.rb
excess before_save/after_save/after_update hooks during the
authentication process.
Closes https://github.com/brave-intl/publishers/issues/3146
=> Fix perf issue when a user tries signing in and we're doing a lot more

Dockerfile
Uses jemalloc, which was previously being used on Heroku for reducing memory consumption.
=> Use jemalloc for containers

app/jobs/cache/browser_channels/responses_for_prefix.rb, test/jobs/cache/browser_channels/responses_for_prefix_test.rb
Details of how the separate write and read databases should be properly handled is described in https://github.com/rails/rails/issues/38548
Given that the jobs are consuming what seem to be the primary database's resources, this PR properly moves the work to the replica.
=> Perf improvements for reading the database

app/controllers/publishers/promo_registrations_controller.rb, app/models/channel.rb, app/models/concerns/referral_promo.rb, app/views/admin/publishers/_wallet_info.html.slim, app/views/publishers/home.html.slim, test/controllers/publishers/promo_registrations_controller_test.rb, test/fixtures/publishers.yml, test/models/channel_test.rb
The `promo_enabled_2018q1` column in `publishers` was being used to turn on/off promo registrations for users. We changed the default behavior so that this flag is false, but we're essentially causing an erroneous double feature-flag for users. 
In a later PR, a migration will be used to remove the column in `publishers`.
=> Partial fix before full deprecation of the 2018q1 flag

app/controllers/application_controller.rb, app/controllers/publishers_controller.rb, test/controllers/publishers_controller_test.rb
Fix a double authentication issue due to a redirect on the before_action authentication_via_token.
The solution in place is to use a separate before_action to set the
params in the locale.
Refactored the locale logic in the ApplicationController a bit to make
it cleaner.
Closes https://github.com/brave-intl/publishers/issues/3193
1. Sign-in with an existing user, make sure page loads
2. Sign-in with an existing Japanese user, make sure page loads in Japanese
3. Sign-in with a new Japanese user, make sure Japanese locale params are apparent and the page loads in Japanese
=> Fix a double authentication issue due to a redirect on the before_action authentication_via_token

config/environments/development.rb
When testing a recent PR in dev, I was not connected to
redis. Instead of give me a warning, the app switched to
null store which caused me to waste a bunch of Albert's
time asking why a PR didn't work.
With this change, if we can't connect to redis, we throw
an exception. Also, in general, if there are any issues with
redis this will also throw an exception which is desirable in
development.
=> Throw an exception if redis down in development

app/controllers/admin/publishers_controller.rb
While generating the payout report, this query becomes slow
reading from the follower DB. This may be due to the high
number of connections that happen at that time, jumping from
50 to 250 as all the sidekiq jobs process, or just from general
DB slowness as the query goes from 8 seconds (already slow)
to 330. We need to look into the root cause of this, but for now
we can have this query run on the primary DB.
=> Read from primary DB for admin creator search

package.json, test/features/admin_test.rb, yarn.lock
A recent yarn upgrade brought with it an updated styled-components
which broke the admin payments page. I've rolled that back and
added a simple capybara test to ensure it doesn't happen again.
=> Fix JS error on admin payments

app/jobs/enqueue_publishers_for_payout_job.rb, test/jobs/enqueue_publishers_for_payout_job_test.rb
Paypal is no longer supported, so don't run it. Later on, after the BitFlyer job is successful, we will remove the Paypal payment code.
=> Remove Paypal Payment job

app/jobs/cache/browser_channels/responses_for_prefix.rb, protos/channel_responses.proto, protos/channel_responses.rb, test/fixtures/gemini_connections.yml, test/jobs/cache/browser_channels/responses_for_prefix_test.rb, test/models/gemini_connection_test.rb
We need to tell the browser which Gemini wallet a user has for direct deposits. We use the protobuf prefix responses for this, and this PR adds Gemini wallet support for that.
Closes #3227
=> Add prefix response support for Gemini wallets

app/services/payout/bitflyer_service.rb, test/fixtures/bitflyer_connections.yml, test/services/payout/bitflyer_service_test.rb
We also don't need to generate potential payments
for referrals for Bitflyer for the time being, until
we dedide we want to.
Note that display_name is only set on successful authentication, so will be blank if oauth didn't complete, but then so will deposit_id. I made a task to clean this filtering up later https://github.com/brave-intl/publishers/issues/3257
=> Pass the display_name to antifraud

app/controllers/payment/connection/uphold_connections_controller.rb, app/jobs/two_factor_authentication_removal_job.rb, app/models/bitflyer_connection.rb, app/models/gemini_connection.rb, app/models/uphold_connection.rb, test/controllers/publishers_controller_test.rb, test/jobs/two_factor_authentication_removal_job_test.rb, test/models/uphold_connection_test.rb
We need to keep track of deletions of wallet connections, so
we add papertrail on gemini and bitflyer.
We also now just destroy the uphold connection when disconnecting,
this will fix the issue with TwoFactorAuth removal as well as
bring it into line with the other connection types.
=> Destroy Uphold Wallets Instead of Clearing

app/javascript/locale/en.ts
There's a typo in `statements.overview.upholdCardLink` which creates a broken link to Uphold.
Closes https://github.com/brave-intl/publishers/issues/3329.
Click on the Uphold card link.
=> Fixing typo in `statements.overview.upholdCardLink`.

app/javascript/locale/en.ts
Closes https://github.com/brave-intl/publishers/issues/3327
=> Don't show displayName for bitflyer accounts

app/jobs/promo/email_breakdowns_job.rb, app/models/concerns/user_feature_flags.rb, app/views/admin/publishers/edit.html.slim, test/models/concerns/user_feature_flags_test.rb
month-to-previous day.
Closes https://github.com/brave-intl/publishers/issues/3328
=> Allow referral emails to be sent as disabled, the previous day, or

Dockerfile, Gemfile, Gemfile.lock, config/database.yml, config/initializers/add_column_types_to_null_db.rb
The monkey patch we introduced for rotating attr-encrypted fields
causes the deploy to fail since when we go to precompile assets,
we need to connect to the DB. There is no DB at that point, so use
a fake one.
=> Use NULLDB to compile assets when no DB available

app/jobs/promo/email_breakdowns_job.rb
To support month-to-date, we should show the date column rather than just hiding it. 
Furthermore, fix an issue where when we got confirmations, we didn't include the data from 30 days ago for that particular date in the CSV's row.
=> Show date for CSV

app/jobs/two_factor_authentication_removal_job.rb, lib/tasks/database_updates/reset_permalocked_users.rake
Fix an issue where a user could be put in a permanent "locked" state after resetting their 2FA twice.
Closes https://github.com/brave-intl/publishers/issues/3387
=> Fix double locked publisher status

app/jobs/enqueue_publishers_for_payout_job.rb
This lets us eager load polymorphic associations for when we call `publication_title` in `gemini_service`, `uphold_service`, `bitflyer_service`.
Rails doesn't support polymorphic eager loading through `includes`, only though `preload`.
=> Eager load the polymorphic channel details

app/services/uphold/refresher.rb, test/services/uphold/refresher_test.rb
We shouldn't skip refresh if we have an expired auth. That's the whole point of refresh.
=> Refresh the Uphold token if authorization expired

app/javascript/modal.js, app/javascript/packs/admin_case.js, app/javascript/packs/case.jsx, app/javascript/publishers/home.js, app/javascript/site_channels/siteChannels.js, app/javascript/utils/flash.js, app/javascript/utils/spinner.js, app/javascript/views/walletServices/braveConnection/CurrencySelection.tsx, app/javascript/views/walletServices/braveConnection/VerifyButton.tsx, app/views/publishers/cases/update.js.erb, config/initializers/content_security_policy.rb, package.json, yarn.lock
fixes all the alerts in https://github.com/brave-intl/publishers/security/code-scanning
=> Fix codeql alerts and prepare to enforce trusted types

app/models/uphold_connection.rb
When we check the connection details, we don't sync first, and then we wipe out the details that currently exist. This PR removed the wiping out of details and forces a sync before returning the details.
=> Uphold don't erase 401

app/models/uphold_connection.rb, app/services/uphold/refresher.rb
This will not call to reauthorize if the current authorization is still good. Note that previously we were checking if the expired at time was still in the future and then returning that we were expired if it was. This has been reversed.
=> Fix authorization expired

app/jobs/enqueue_publishers_for_payout_job.rb, app/models/publisher.rb, app/models/uphold_connection.rb
When generating the payout report, the publisher statuses
were not being properly accounted for after switching to the new
much speedier, eager loaded payout report generation. When eager loading,
Rails was dropping the default ordering on the publisher statuses
table and instead just ordering by ID. I played around with added a new
scope that would only let us pull in the latest status update. The scope
looked like this:
```
has_one :latest_status_update, class_name: "PublisherStatusUpdate", primary_key: :latest_publisher_status_id, foreign_key: :publisher_id
scope :with_latest_status, lambda {
select(
"publishers.*,
(
SELECT publisher_id as latest_publisher_status_id
FROM publisher_status_updates
WHERE publisher_id = publishers.id
ORDER BY created_at DESC
LIMIT 1
)"
)
}
```
But in the …
=> Fix Potential Payments ordering bug

app/jobs/promo/email_breakdowns_job.rb
Also the data in referral_downloads is not grouped and summed to get
the total confirmations for a region per code per day, so we do that on
our end. Previously we had too many rows in the report.
=> Add referral code to promo email contributions

app/controllers/publishers_controller.rb, app/models/uphold_connection.rb, test/models/uphold_connection_test.rb
Since we no longer update the status during potential payment generation, do it when visiting the homepage. Appropriately cached so that we don't hit Uphold multiple times in the same request, but a further optimization will be to background this, perhaps with a backoff of up to a few days in case the Uphold API is down for some reason. In this way, we could avoid immediately update to a bad status per #3468
=> 401 reapply with homepage sync

app/models/uphold_connection.rb, app/services/uphold/refresher.rb
This will help us track down if we are parsing the expiration date correctly from Uphold when refreshing the oauth tokens.
=> Retry Uphold details fetch after 401

app/controllers/publishers_controller.rb, app/services/bitflyer/wallet_connection_syncer.rb, app/services/gemini/wallet_connection_syncer.rb, app/services/uphold/wallet_connection_syncer.rb, app/services/util/wallet/connection_syncer.rb, config/initializers/login_activities.rb, test/services/util/wallet/connection_syncer_test.rb
We don't want to update on home page view, and we want to cover
all wallet providers. Currently we won't sync Bitflyer since I need to 
verify refreshing works properly and this is
mainly addressing Uphold, for the moment. Will need to come back and
turn that on for Bitflyer, though it's not as big of a priority since
at connection, the user is already KYCd.
=> Add Wallet Syncer which Updates on Login

app/jobs/promo/email_breakdowns_job.rb
The promo system doesn't set the finalized=true until 30 days have passed,
so this nightly report will only report up until a month ago. That is, where a
retrieval = download from site
download = actual download and then launch
The Referral download table is a view on the download table, that is,
first launches. That table also tracks usage pings so a column gets updated
daily in it. That column is the finalized_ts, which is very unfortunate
and in fact, much of the naming here is.
So we get a finalized_ts that gets set daily, but the finalized column
itself doesn't get set until a month later.
So if you are looking at this report on Dec 6, the report's latest date
will be Nov 5, i.e. when a particular download was created. It's finalized
column was updated today, and it's finalized_ts …
=> We were over reporting the nightly stats email

app/models/site_banner.rb, config/secrets.yml, test/controllers/publishers/site_banners_controller_test.rb
When we migrated to ruby-wasmer, we removed an activestorage plugin we had written which essentially just sets the URL to a cloudfront URL. Restoring that functionality.
=> Serve the public cloudfront URL instead of the private

db/migrate/20211208230135_add_proper_index_to_site_banner_lookups.rb, db/schema.rb
The call to find the SiteBannerLookup
https://github.com/brave-intl/publishers/blob/staging/app/jobs/cache/browser_channels/responses_for_prefix.rb#L23
`@site_banner_lookups = SiteBannerLookup.where("sha2_base16 LIKE ?", prefix + "%")`
was doing a table scan and not using the index. Through experimentation,
I found out that we aren't using the current indexes because the collation
is off. This corrects that. I ran a full upload to the pcdn and verified
that the 504s are gone. This should greatly improve responsiveness both
for the admin panel and stats hitting our API.
=> Resolved 504s during pCDN upload

Gemfile
Disable `sorbet` on anything !x86_64.
This is required to develop on foreign platforms.
Revert this change when multi-arch support is added to `sorbet`
1. Download on non x86_64 Linux architecture
2. Prepare the environment
3. Test if it starts properly
=> Gemfile: disable sorbet when arch is not x86_64

app/services/builder_base_service.rb, test/services/builder_base_service_test.rb
We introduce a union type which can be distinguished by pattern matching
The reason for this is we want Sorbet to help us as much as possible. If
we have an error, we don't want to accidentally put those in a success
callback. With the fields of the success/error structs being different,
sorbet can now help prevent sensitive information escaping.
An example of usage:
```ruby
case res = ChildService.build.call
when BFailure
puts "I can access errors! #{res.errors}"
problem("1")
when BSuccess
puts "I can access result!"
pass(res.result.add(2))
else
T.absurd(res)
end
```
=> Builder Base Class changes

Dockerfile, app/controllers/u2f_authentications_controller.rb, app/controllers/u2f_registrations_controller.rb, app/javascript/u2f/registrationPage.js, app/models/u2f_registration.rb, app/services/builder_base_service.rb, app/services/two_factor_auth/webauthn_registration_service.rb, app/services/two_factor_auth/webauthn_verify_service.rb, app/views/u2f_registrations/new.html.slim, config/initializers/service_result_types.rb, config/initializers/webauthn.rb, db/migrate/20220202213910_add_format_to_u2f_registrations.rb, db/schema.rb, lib/tasks/database_updates/u2f.rake, test/controllers/u2f_registrations_controller_test.rb, test/services/two_factor_authentication/webauthn_registration_service_test.rb, test/test_helpers/service_class_helpers.rb
The old U2F protocol is being phased out. The new Webauthn protocol is
more flexible and nicer to work with. Since most of the registrations are
in U2F, we just keep them there but mark the format. All new registrations
will be done using the Webauthn format. Note we must run the u2f rake job
in prod after deploy to mark them and standardize the base64 encoding of
the already-stored keys.
Tested locally with both a Yubikey that was registered using U2F and a
separate one under Webauthn. With both registered I could log in using
both.
Currently in draft as service refactoring and tests are needed.
=> This adds the ability to add a security key using webauthn

app/helpers/publishers_helper.rb, test/helpers/publishers_helper_test.rb
fix: Ensure bat channel balance is never negative
1. Step one
2. Step two
3. Step three
=> fix: Ensure bat channel balance is never negative

lib/eyeshade/balances.rb, lib/eyeshade/client.rb, lib/eyeshade/types.rb, test/lib/eyeshade/balances_test.rb, test/lib/eyeshade/client_test.rb, test/test_helpers/eyeshade_helper.rb
Typed Eyeshade::Client and Eyeshade::Balances
I'm effectively V2'ing Eyeshade::Wallet, PublisherBalancesGetter, and PublishersTransactionsGetter (among others) in favor of typed objects with immutable data containers.  The financial aspect of the eyeshade interactions is far too important to leave untyped and in it's current format.
1. Step one
2. Step two
3. Step three
=> Typed Eyeshade::Client and Eyeshade::Balances

.github/workflows/audit.yml, .github/workflows/lint.yml
I closed the previous PR as I was testing triggers, but I think the changes here should satisfy the concerns.  We can merge/deploy into staging so we can iterate quickly, but to deploy to prod we need to have passing builds on PR for security audits.
=> Run security audits on production/master PR. Run tests/lint on push

Dockerfile.dev, app/models/publisher.rb, app/views/publishers/settings/index.html.slim, lib/tasks/admin.rake
* task: Update dev Dockerfile
The previous command seemed to be overly complicated and I suspect that
it was masking failures.  This seems to work just fine
* feat: Countries Dropdown and minimal location form
Testing: Should be fully backwards compatible/feature flagged.  Settings section should not be visible for staging/production users unless feature is enabled via rake task or console.
=> Release 3/28/22: Addition of country dropdown data to Settings [ Feature Flagged ]

test/test_helper.rb
This unblocks the basic need to run unit tests from within a docker
container on an M1 device.  The core issue of selenium not working in
aarch64 however remains.
=> task: Unpin version on ARM

db/migrate/20220314225313_add_oauth_failure_dates.rb, db/schema.rb
We want to unify the way we deal with wallet connections and associated
failures to refresh tokens.
We want to run monthly jobs to refresh all the wallets that were paid out
last month. New wallets since then we'll consider OK since they were
created within 30 days.
We're going to need 2 jobs:
Monthly job that runs and refreshes all wallets that were paid out
last month. If a failure occurs, notes this in the DB.
Monthly email job. Finds all noted failures and emails the creator.
Notes in the DB that the creator was emailed. Only one email will be sent.
The PotentialPayout table will also take emailed failures into account.
=> We want to unify the way we deal with wallet connections and associated

app/models/uphold_connection.rb, test/models/uphold_connection_test.rb
This just implements the actual pieces required to denote an authentication failure.  I forgot to add it before because I originally didn't have the database migrations.
=> task: Implement failure recording API

lib/oauth2/structs.rb, test/test_helpers/mock_oauth2_responses.rb
Scope is being returned from the refresh token response and the struct is failing to initialize because of it (scope is optional) in response types.
=> fix: Add scope as optional for refresh token response

app/models/gemini_connection.rb
Oauth flow URL is different from the gemini api url.
=> fix: Use oauth url not api url

app/models/oauth2/authorization_code_base.rb, test/jobs/oauth2_refresh_job_test.rb, test/models/gemini_connection_test.rb
Several new relic errors were being raised because UnknownError takes params and rather than raising the result/instance I was raising the class.
=> fix: Raise instance instead of class

app/javascript/locale/en.ts, app/javascript/views/statements/Statements.tsx, app/javascript/views/statements/statements/StatementDetails.tsx
Closes #3607 .  Because the app doesn't have access to direct tipping information, the values in that column will always be 0.  Removed both the 'Direct User Tips' column on the statements page, and the 'Direct User Tips' row on the statement detail view.
=> task: Delete "Direct User Tips" column in Statements

README.md, docker-compose.yml
Ensures local directory does not override content of node_modules installed by docker.  I rebuilt from scratch several times and confirmed though I did not test what the behavior was when you had a pre-existing node-modules directory.
See: https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
Closes #3651
=> task: Persist node_modules on container

app/jobs/sync/bitflyer/update_missing_deposit_job.rb, app/jobs/sync/bitflyer/update_missing_deposits_job.rb, app/services/bitflyer/update_deposit_id_service.rb, app/services/builder_base_service.rb, app/services/wallet/refresh_failure_notification_service.rb, app/services/wallet/structs.rb, config/initializers/service_result_types.rb, sorbet/rails-rbi/mailers/publisher_mailer.rbi, test/jobs/oauth2_refresh_job_test.rb, test/services/bitflyer/update_deposit_id_service_test.rb
I think I overdid it here.  Initially I was thinking the email notification service would be useful, but I'm not so sure it actually is.  Whatever, it's optional.  If it turns out to not be worth it I'll just drop it and use refresh_authorization! alone.
=> refactor: Abstract deposit id into service and add specs/types

app/jobs/sync/bitflyer/update_missing_deposit_job.rb
In an abundance of caution I'm disabling retries until I have a better sense of actual production behavior here.
=> task: Disable Retry

app/models/channel.rb, app/services/bitflyer/update_deposit_id_service.rb, sorbet/rails-rbi/models/bitflyer_connection.rbi, sorbet/rails-rbi/models/channel.rbi
This adds the sorbet exhaustiveness check.  The core value here is that these are the only possible responses that can be returned from the service.  It is self documenting and statically typed.  We should basically end any sorbet typed function this way (which was something I didn't appreciate before).
T.absurd() implies the end of code execution so this always has to be at the end of the function (which I didn't know).
=> improvement: Add exhaustiveness checks

config/sidekiq.yml
Runs every day at 4, will only run against missing deposit ids that have not failed an oauth2 connection attempt.  Retry it set to 0 so maximum impact is low.  Will monitor once deployed.
=> task: Re-enable deposit sync job

app/models/channel.rb, app/services/bitflyer/update_deposit_id_service.rb, config/sidekiq.yml, sorbet/rails-rbi/models/bitflyer_connection.rbi, sorbet/rails-rbi/models/channel.rbi
This should hopefully resolve any outstanding bitflyer associated channels that are missing their deposit ids.  I've manually updated quite a few and they have been confirmed successful.  This runs daily and the number of possible updates after an initial run is very low.
=> Production Release 5.17.22 - Re-enable Bitflyer deposit id update task

app/jobs/create_gemini_recipient_ids_job.rb
We are calling a lot of jobs including cases that may be redundant/async and cause race conditions.   I don't think there is a ton of reason to retry this over and over again as these jobs get executed A LOT.
=> fix: Do not retry

app/models/gemini_connection.rb, test/jobs/sync/wallet_connection_job_test.rb
There is some sort of state that causes broken gemini connections to get caught in the UI and this prevents it.  Not sure of the root cause, it probably has something to do with async tasks.  It's a specific pathway to get to this state and it doesn't appear that anyone in prod has hit it yet, so let's move this out quickly and go from there.
=> hotfix: Do not call refresh unless expired

app/services/redis_count_service.rb, test/services/redis_count_service_test.rb
Generally useful for caching values and keeping track of how many times they've been seen over an interval.  Can be used for rate limiting etc.
=> feat: Redis counter

config/application.rb
This actually notifies in the sidekiq container instead of web... but it is more than nothing.  Also having a clear notice of when a build has actually succeeded would be really helpful in general.
=> improvement: Notify commit and environment after initialiation

app/jobs/sync/bitflyer/update_missing_deposits_job.rb, app/models/channel.rb, test/controllers/channel_transfer_controller_test.rb, test/controllers/site_channels_controller_test.rb, test/jobs/channels/transfer_channels_job_test.rb, test/services/channels/contest_channel_test.rb
1. The wrong value was being passed into the update deposits job and was failing in the async context (despite actually having synchronous specs that pass...)
2. Uphold card jobs are enqueued for all channels because all publishers have an uphold connection (😮‍💨 )
3. Bitflyer clearly does rate limit deposit id requests because I hit it when manually debugging in prod.
Should finally fix the issue with brave-intl/creators-private-issues#62 which has been very difficult to debug.
=> Deposits job fixes and channel improvements.

app/models/channel.rb
This was failing silently for years and is overwhelmingly noisy.
=> task: Redirect notifications back to appropriate channel

app/models/channel.rb
Points event stream back to previously configured channel.
=> Production Release: Tweak Slack Notifications - 6/8/22

app/controllers/publishers_controller.rb
Removes the arbitrary empty uphold connection step that happens whenever a user logs in.
I tested this locally with a brand new user and didn't encounter any issues on a cursory glance.  Probably worth exploring channel creation etc, but I had some difficulty doing that in local dev.
#3668
=> task: Do not create empty connection

app/controllers/publishers/statements_controller.rb, app/controllers/publishers_controller.rb, lib/oauth2/config.rb, test/lib/oauth2/config_test.rb
1. Removes the action that creates an empty uphold connection for every user in the system.
2. Fixes a call to the statements controller that expects a truthy uphold connection for all users
3. Fix the oauth2 production config for bitflyer redirect url.  Valid redirect url at bitflyer users publishers.basicattentiontoken.org
Closes #3668 
Fixes brave-intl/creators-private-issues#93
=> Production Release: Fixes and artifacts

app/models/uphold_connection.rb, app/services/uphold/find_or_create_card_service.rb, lib/uphold/connection_client.rb, test/lib/uphold/connection_client_test.rb, test/services/uphold/find_or_create_card_service_test.rb
This stand alone replaces the full set of functionality found in Jobs::CreateUpholdCardsJob.  Once implemented it will also patch the bug (with specs) that allows users who have changed the label of their uphold card to set a wallet address that is != to whatever the default currency is in creators.  This bug is probably what caused the payout issue for DDG
=> feat: Uphold::FindOrCreateCardService

app/jobs/create_uphold_cards_job.rb, test/jobs/create_uphold_cards_job_test.rb
1. Updates the card creation job to use newly created services and adds specs for additional cases
brave-intl/creators-private-issues#94
=> refactor: Use service for uphold cards job

app/jobs/create_uphold_cards_job.rb, app/models/uphold_connection.rb, app/services/uphold/find_or_create_card_service.rb, lib/uphold/connection_client.rb, test/jobs/create_uphold_cards_job_test.rb, test/lib/uphold/connection_client_test.rb, test/services/uphold/find_or_create_card_service_test.rb
1. Refactors uphold card create job (which is critical for payout), extends specs, adds typing and exhaustiveness checks.
2. Resolves a bug where a connection could be set to a value other than it's default_currency due to a bad matching condition.
Fixes brave-intl/creators-private-issues#94
=> Production Release: Refactor Uphold Card create job/Fix assignment of wrong currency to connection

app/controllers/publishers_controller.rb, app/models/publisher.rb, app/services/publisher_token_authenticator.rb, test/models/publisher_test.rb
Do not update the email unless a successful step-up has occurred.
This allows securing the padlocked account from
session-hijacking+account takeover tentative.
Relates to https://github.com/brave-intl/publishers/issues/3616#issuecomment-1130264573
*: update email only after step-up
Update email only after a successful step-up (if a step-up method is available).
1. Create an account
2. Click on the confirmation email to Login
3. Setup 2FA (WebAuthN or TOTP are either working good)
4. Change the email
5. Click on the confirmation email to change the email
A 2fa prompt should show and the email should not be changed unless the 2fa is successful
=> Update email only after a successful step-up (if a step-up method is available).

app/controllers/oauth2_controller.rb, test/controllers/payment/connection/bitflyer_connections_controller_test.rb, test/controllers/payment/connection/uphold_connections_controller_test.rb
If the state token has expired just redirect and give a generic flash message and log it.
=> fix: Redirect instead of raise when state token mismatches

app/controllers/oauth2_controller.rb
Resolves a rare exception where this case (which I don't even understand how it would return from uphold) was returning a T::Struct and not an Error.
=> fix: Pass error not response

app/jobs/oauth2_batch_refresh_job.rb, config/sidekiq.yml
Default should be async otherwise we end up blocking for a long time on our refresh tasks.
=> fix: Set default to true

app/controllers/csp_violations_report_controller.rb
Patches a JSON parser failure throwing 500s in staging. See newrelic for specific error log.
=> fix: Fix 500 error for invalid csp reports

app/models/uphold_connection.rb
Refresh values weren't actually being assigned.  The various linters + encrypted attrs rekt me on this one.
=> fix: Assign to correct value

config/database.yml
Our configuration is incorrect, as we need to have a pool big enough for all of the sidekiq threads we have running on a node.
=> Make Redshift pool same size as sidekiq concurrency

app/services/base_api_client.rb, lib/uphold/cards.rb
Calls to create card were failing with a seemingly impossible error, the issue was that the content-type was not set for the POST request and the resulting error was a missing param 400.
=> fix: Ensure content type header is passed to create card call

app/models/publisher.rb
I must have been sleepy when I wrote the previous implementation, this sets a proper message in admin so indicate suspension rationale.
=> fix: Ensure note is properly set

app/jobs/sync/channel_promo_registrations_stats_job.rb, app/jobs/sync/promo_registration_stats_job.rb, app/models/promo_registration.rb, app/services/promo/registrations_stats_fetcher.rb, config/sidekiq.yml, test/jobs/sync/channel_promo_registrations_stats_job.rb, test/jobs/sync/promo_registrations_stats_job_test.rb
Refactors the existing jobs to be generally more performant, trying to process fewer at a higher frequency.  This allows me to test out the full batch job in safety and also get a sense of how well promos handles consistent low volume requests.
=> perf: Hopefully make this job not crash all the things

app/jobs/sync/channel_promo_registrations_stats_job.rb, app/models/promo_registration.rb
I tested the previous merge in prod and it worked as expected, but evidently like it was still doing 99% more than it needed to.  This should strongly cut down on any scheduled burden coming from this side of things.
=> Production Release: Scope to only users in referral program (#3847)

app/models/uphold_connection.rb, config/newrelic.yml, test/models/uphold_connection_test.rb
I think this should do it for the majority of errors we see in newrelic.  They were not excluded originally because it was important to have visibility into them while I rewrote the entire set of oauth integrations.
=> task: Ignore known failure states for uphold connections

app/services/promo/unattached_registrar.rb
Who knows how many instances of this are present in creators.  Http clients should be clients that handle the entirety of their configuration, services should implement clients, models, and other services and mediate their interactions.
=> fix: This is why we shouldn't write services this way

app/jobs/cache/browser_channels/responses_for_prefix.rb
When the recipient_id is blank, errors are sent to newrelic because nil is not the correct type for address, it needs to be a string.  Similar to how we handle blank uphold addresses, missing recipient_ids for gemini wallets will be set to empty strings.
=> add catch for blank gemini recipient_id

app/controllers/admin/payout_reports_controller.rb, app/controllers/api/v3/public/channels_controller.rb, app/controllers/api/v3_p1/public/channels_controller.rb, app/controllers/concerns/browser_channels_dyno_caching.rb, app/helpers/publishers_helper.rb, app/jobs/application_job.rb, app/mailers/partner_mailer.rb, app/mailers/publisher_mailer.rb, app/services/paypal/refresh_identity.rb, app/services/promo/assign_promo_to_channel_service.rb, app/services/publisher_balance_getter.rb, app/services/youtube_channel_getter.rb, config/environments/production.rb, config/environments/staging.rb, lib/error_handler.rb, lib/error_handler_delegator.rb, sorbet/rails-rbi/mailers/partner_mailer.rbi, sorbet/rails-rbi/mailers/publisher_mailer.rbi
Replaces sentry error logging with LogException, which logs to both sentry and new relic.  Sentry can be explicitly removed in another ticket.
=> Replace references to sentry with LogException

.reviewdog.yml
Fix an issue with `semgrepignore` being ignored
=> .reviewdog: use commit as a source of truth for file selection

Gemfile.lock, app/services/enqueue_publishers_for_payout_service.rb, app/services/payout/bitflyer_service.rb, app/services/payout/gemini_service.rb, app/services/payout/service.rb, app/services/payout/uphold_service.rb, test/controllers/admin/payout_reports_controller_test.rb, test/fixtures/uphold_connections.yml, test/jobs/enqueue_publishers_for_payout_job_test.rb, test/jobs/payout/enqueue_top_referrer_payout_job_test.rb, test/services/enqueue_publishers_for_payout_service_test.rb, test/services/payout/uphold_service_test.rb
Ensure that Potential Payments don't get generated for wallets in unallowed countries.
Closes https://github.com/brave-intl/creators-private-issues/issues/108
=> Don't include Potential Payments from wallets in unallowed countries

app/models/publisher.rb, app/views/publishers/home.html.slim, test/features/locale_test.rb, test/features/log_in_test.rb, test/features/statements_test.rb
hiding the statements panel from non-referrers, since it is no longer relevant to them.  Also noticed some legacy code in the `valid_payable_gemini_creators` scope that could be updated.
=> Hide statements from non-referrers

app/controllers/api/v3/channels_controller.rb
Looks like there may a few accounts with older, non-functional wallets (to be cleaned up) which for a small number made the old logic here invalid.
=> Use the selected_wallet_provider for country validation check

app/controllers/api/v1/publishers_controller.rb, app/services/publisher_status_updater.rb, lib/tasks/update_publisher_statuses.rake, test/services/publisher_status_updater_test.rb
Add the ability to bulk update creators from a CLI script. Leverage the same code an API action uses, but break that out into a separate service for reuse.
=> Add status updater rake task

app/jobs/create_uphold_cards_where_missing_job.rb, app/models/publisher.rb, config/sidekiq.yml
In the case that creating the Uphold Cards fails, due to a flake on the part of the Uphold API, we should ensure that these are created in a timely manner. This job runs nightly and checks for those who have verified channels and Uphold connections, but who don't have cards. It then launches a job to create them.
Closes https://github.com/brave-intl/creators-private-issues/issues/126
=> Create Uphold cards for those who should have them

app/views/publishers/_home_balances.html.slim, config/locales/en.yml, test/features/payout_in_progress_test.rb
Referrers will now see this on their home page to better explain their payouts.
Closes https://github.com/brave-intl/creators-private-issues/issues/133
=> Update payout wording for referrers

app/models/gemini_connection.rb, app/models/publisher.rb, test/fixtures/gemini_connections.yml
A referrer was not being included in `PotentialPayout` generation due to a lack of a `blocked_country_exception` check.
We had 2 separate scopes for similar checks, this combines them. We also move away from hard-coding for the country check.
=> Refactor Gemini payable scope to not include hardcoded country

app/controllers/oauth2_controller.rb, app/services/base_api_client.rb, app/services/log_exception.rb, test/cassettes/test_code_redirects.yml, test/controllers/oauth2_controller_test.rb, test/features/publishers_home_test.rb, test/test_helper.rb
Also just assume we have GZIPd content and use a standard fallback if not, python style.
=> Allow redirects to Uphold and Gemini

app/jobs/uphold_refresh_job.rb
We previously discovered not all Uphold wallets were regularly refreshing because of this limit. For now, remove it.
=> Not all connections are refreshing due to this limit

app/assets/stylesheets/theme/nav.scss
Closes https://github.com/brave-intl/creators-private-issues/issues/1605
The logo was too low on small screens, removed the top padding fixed it.
=> Fix logo out of place on small screens

Gemfile, Gemfile.lock, Procfile, Procfile.dev, README.md, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb, config/initializers/session_store.rb
Closes https://github.com/brave-intl/creators-private-issues/issues/1638
Use overmind for running locally without Docker. This boots all services with one command. 
This required a switch to redis for sessions since the activerecord module is no longer receiving updates, it seems.
This is in draft since we need the encrypted columns change to go to production first.
=> Redis sessions & overmind

app/javascript/admin/dashboard/unattached_promo_registration.js
Not sure this code is relevant anymore, but this prevents an errors being throw if the elements don't exist on the page.
Closes [Issue #391](https://github.com/brave-intl/creators-private-issues/issues/391)
=> Handle for missing promo registration elements 

config/locales/en.yml, config/locales/ja.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/481
Updates expired auth token copy to now say 3 hours instead of 30 minutes
Verified that 3 hours in the correct time [here](https://github.com/brave-intl/publishers/blob/63c93f82a26029006f968fa572e5f46d10df3bc5/app/services/publisher_token_generator.rb#L4-L5/) 
Changed the Japanese Kanji from `30分` (30 minutes) to `3時間` (3 hours)
=> Updates expired auth token copy to correct time

app/views/publishers/_channel.html.slim
Resolves https://github.com/brave-intl/creators-private-issues/issues/1639
Removes broken uphold link from Channel card
=> Removes broken uphold url on channel card

app/controllers/api/v3/public/channels_controller.rb, config/routes.rb, public/creators-landing/src/sections/signoff/index.js, test/controllers/api/v3/public/channels_controller_test.rb
Replace's the static `1,000,000` count in the sign-off section of the landing page with a count of verified channels from the database
Removes original code  for the PublicChannelsController since it is missing the associated file to work correctly
**Note:** The test DB only has 54 verified channels
=> Replaces static count with verified channels count to landing page

.audit-ci.json, Gemfile.lock, bin/setup, package.json, yarn.lock
There's a call to yarn in the new `bin/setup` file that seems unnecessary and is breaking deployments.
=> removing unnecessary call to yarn

package.json, public/creators-landing/package.json, public/creators-landing/yarn.lock
Audit was failing from the following vulnerability https://github.com/advisories/GHSA-j8xg-fqg3-53r7
`word-wrap` dependency was replaced with working fork
=> Use `word-wrap` sub-dependency alternative

config/locales/en.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1652
Updates the original copy to the following:
"We noticed some unusual activity associated with your account. As a result, access to your account has been suspended in order to protect your account and the Brave Creators platform.
If you have an idea about what might have triggered this alert, or if you believe your account was mistakenly suspended, you can reach out to us at [suspensions@brave.com](mailto:suspensions@brave.com). A dedicated member of our support team will personally review and respond to your message."
=> Update 'Account Under Review' copy

app/assets/stylesheets/theme/panels.scss, app/mailers/publisher_mailer.rb, app/views/publishers/reject_transfer_success.html.slim, config/locales/en.yml, config/locales/ja.yml, config/routes.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1660
When a user clicks the "Reject Transfer" button in the corresponding email, they will now be taken to a static success page.
=> Add Reject Transfer Cancel Success page

app/views/publishers/_channel.html.slim
Resolves: https://github.com/brave-intl/creators-private-issues/issues/1674
Removes unused "allow-ads" toggle from channels card
=> Removes FE code for the allow-ads toggle

app/javascript/views/admin/payments/Payments.tsx
It looks like certain Brave-UI components now require a theme. I've added the Brave-UI theme provider to the payments page to fix this issue
=> fix: adds theme provider to payments page

.vscode/settings.json, app/controllers/api/nextv1/publishers_controller.rb, config/routes.rb, nextjs/package.json, nextjs/src/app/[locale]/publishers/settings/page.tsx
Resolves https://github.com/brave-intl/creators-private-issues/issues/1698
Allow users to delete their account via the settings page
* Also adds back in the .vscode directory
* Adds the (broken) Nala Input component
=> feat: allow user to delete account

docker-compose.yml
We were having an issue where the node_modules directory was not effectively cached or shared between ours host system and the container. 
It looks like the issue was due to excluding node_modules too late in the process.
=> fix: have docker correctly update node_modules

nextjs/scripts/create-local-server.js
https://github.com/brave-intl/creators-private-issues/issues/1695
url.parse uses a lenient, non-standard algorithm for parsing URL strings.
It is prone to security issues such as host name spoofing and incorrect handling of usernames and passwords
This change maintains the previous behaviour of stripping the querystring
and hash from the URL before redirecting (just using the path).
not sure
=> Use WHATWG URL API rather than deprecated url.parse

app/helpers/publishers_helper.rb, app/views/admin/publishers/_channel.html.slim, app/views/publishers/_channel.html.slim
using `asset_url` instead of `image_tag` tries to load assets from `web:3000` instead of `localhost:5001` when using the new UI.
=> remove use of asset_url method

app/javascript/packs/banner_editor.jsx, app/javascript/publishers/home.js, nextjs/package.json, nextjs/src/app/[locale]/publishers/layout.tsx, nextjs/src/app/[locale]/publishers/settings/page.tsx, package.json, yarn.lock
Resolves https://github.com/brave-intl/publishers/security/dependabot/197
=> remove babel-preset-react

app/helpers/application_helper.rb, app/javascript/analytics.js, app/javascript/packs/application.js, app/javascript/packs/static.js, app/javascript/views/statements/statements/StatementDetails.tsx, app/javascript/views/walletServices/braveConnection/BitflyerConnection.tsx, app/javascript/views/walletServices/braveConnection/GeminiConnection.tsx, app/javascript/views/walletServices/braveConnection/NotConnected.tsx, app/views/application/_choose_channel_type.html.slim, app/views/faqs/index.html.slim, app/views/layouts/application.html.slim, app/views/layouts/error.html.slim, app/views/layouts/headless.html.slim, app/views/layouts/no_js.html.slim, app/views/layouts/public.html.slim, app/views/layouts/static.html.slim, app/views/publishers/promo_registrations/_activate.html.slim, app/views/publishers/registrations/log_in.html.slim, app/views/publishers/registrations/sign_up.html.slim, app/views/publishers/security/index.html.slim, app/views/site_channels/_verification_failed_modal.html.slim, app/views/site_channels/new.html.slim, app/views/site_channels/verification_choose_method.html.slim, app/views/site_channels/verification_dns_record.html.slim, app/views/site_channels/verification_github.html.slim, app/views/site_channels/verification_public_file.html.slim, app/views/static/no_js.html.slim, app/views/totp_registrations/new.html.slim, app/views/u2f_registrations/new.html.slim, config/secrets.yml
Resolves https://github.com/brave-intl/creators-private-issues/issues/1839
=> Remove piwik

app/controllers/api/nextv1/home_controller.rb, nextjs/src/lib/api.ts
Fixes issue noticed here: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1727879448793799
We weren't redirecting to the 2fa prompt when a new user navigated to the homepage.  I added that back in.  
While next.js allows redirects on the front end, there doesn't seem to be any particularly good way of having the server redirect the front-end.  This may be necessary from time to time in reaction to information that exists on the server but doesn't exist on the front end (either because it would require an unnecessary api request to get the information, or because it's information we don't want exposed to the client.) I added a step to our API logic that allows for 302 redirects, in the same way we allow 400s requests to redirect the user to the login page.
=> add redirect for 2fa prompt on signup

app/controllers/api/nextv1/contribution_page_controller.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1641
This won't pass lint.  for some reason, standardrb's lint replaces `File.write` with `File.binwrite`, which are not equivalent and I believe is the source of the problem.
=> get rid of binwrite

.audit-ci.json
Adding `GHSA-76p7-773f-r4q5` to allowlist because serialize-javascript has already been manually updated to the patched 6.0.2.  See https://github.com/brave-intl/publishers/pull/4609
=> update yarn packages

app/controllers/api/nextv1/publishers_controller.rb, nextjs/src/app/[locale]/publishers/settings/page.tsx
Resolves: https://github.com/brave-intl/creators-private-issues/issues/1905
=> store new email as pending and re-enable the confirmation flow

app/services/two_factor_auth/webauthn_verify_service.rb
Resolves https://github.com/brave-intl/creators-private-issues/issues/1914
Fixes a bug introduced in https://github.com/brave-intl/publishers/pull/4753.  Reading through the webauthn code, we shouldn't need to specify an rp_id (it should read it from the `domain` variable we are already supplying), but apparently it's necessary.  Also removing the u2f check, since there's no longer a difference in the verify methods.
=> specify rp_id
